// apps/web/src/lib/components/dataset/details/CurrentTransactionViewPanel.svelte
<!--
  T5.1 — CurrentTransactionViewPanel

  Foundry's "Current transaction view" surfaces the transaction at
  HEAD of the active branch: type, author, timestamp, file count,
  total bytes, plus a list of every transaction whose contribution is
  still part of the live view.
-->
<script lang="ts">
  import type { DatasetTransaction } from '$lib/api/datasets';

  type Props = {
    head: DatasetTransaction | null;
    composedOf: DatasetTransaction[];
    fileCount: number;
    totalBytes: number;
  };

  const { head, composedOf, fileCount, totalBytes }: Props = $props();

  function operationTone(op: string): string {
    const u = op.toUpperCase();
    if (u === 'SNAPSHOT')
      return 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300';
    if (u === 'APPEND')
      return 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300';
    if (u === 'UPDATE')
      return 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300';
    if (u === 'DELETE')
      return 'bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-300';
    return 'bg-slate-100 text-slate-700 dark:bg-gray-800 dark:text-gray-300';
  }

  function fmtBytes(b: number): string {
    if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
    return `${(b / (1024 * 1024)).toFixed(1)} MB`;
  }
</script>

<section class="space-y-4">
  <header>
    <div class="text-xs uppercase tracking-[0.22em] text-gray-400">Current transaction view</div>
    <h2 class="mt-1 text-lg font-semibold">HEAD of branch</h2>
    <p class="mt-1 text-sm text-gray-500">The transaction whose contents make up the live view.</p>
  </header>

  {#if !head}
    <div class="rounded-xl border border-dashed border-slate-300 px-4 py-8 text-center text-sm text-gray-500 dark:border-gray-700">
      No transactions have been committed yet.
    </div>
  {:else}
    <div class="rounded-xl border border-slate-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
      <div class="flex items-center justify-between gap-3">
        <span class="font-mono text-xs">{head.id}</span>
        <span class={`rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide ${operationTone(head.operation)}`}>
          {head.operation}
        </span>
      </div>
      <dl class="mt-3 grid grid-cols-2 gap-3 text-sm">
        <div>
          <dt class="text-xs uppercase tracking-wide text-gray-400">Status</dt>
          <dd class="mt-0.5">{head.status}</dd>
        </div>
        <div>
          <dt class="text-xs uppercase tracking-wide text-gray-400">Branch</dt>
          <dd class="mt-0.5 font-mono text-xs">{head.branch_name ?? '—'}</dd>
        </div>
        <div>
          <dt class="text-xs uppercase tracking-wide text-gray-400">Created</dt>
          <dd class="mt-0.5">{new Date(head.created_at).toLocaleString()}</dd>
        </div>
        <div>
          <dt class="text-xs uppercase tracking-wide text-gray-400">Committed</dt>
          <dd class="mt-0.5">
            {head.committed_at ? new Date(head.committed_at).toLocaleString() : '—'}
          </dd>
        </div>
        <div>
          <dt class="text-xs uppercase tracking-wide text-gray-400">Files</dt>
          <dd class="mt-0.5">{fileCount.toLocaleString()}</dd>
        </div>
        <div>
          <dt class="text-xs uppercase tracking-wide text-gray-400">Total size</dt>
          <dd class="mt-0.5">{fmtBytes(totalBytes)}</dd>
        </div>
      </dl>
      {#if head.summary}
        <p class="mt-3 text-sm text-gray-600 dark:text-gray-300">{head.summary}</p>
      {/if}
    </div>
  {/if}

  {#if composedOf.length > 0}
    <div>
      <div class="text-xs uppercase tracking-wide text-gray-400">Composed of</div>
      <ul class="mt-2 divide-y divide-slate-100 overflow-hidden rounded-xl border border-slate-200 bg-white dark:divide-gray-800 dark:border-gray-700 dark:bg-gray-900">
        {#each composedOf as tx (tx.id)}
          <li class="flex items-center justify-between gap-3 px-3 py-2 text-sm">
            <span class="flex items-center gap-2">
              <span class={`rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide ${operationTone(tx.operation)}`}>
                {tx.operation}
              </span>
              <span class="font-mono text-xs">{tx.id.slice(0, 12)}…</span>
            </span>
            <span class="text-xs text-gray-500">
              {new Date(tx.created_at).toLocaleString()}
            </span>
          </li>
        {/each}
      </ul>
    </div>
  {/if}
</section>

// apps/web/src/lib/components/dataset/details/CurrentTransactionViewPanel.tsx
import type { DatasetTransaction } from '@/lib/api/datasets';

interface CurrentTransactionViewPanelProps {
  head: DatasetTransaction | null;
  composedOf: DatasetTransaction[];
  fileCount: number;
  totalBytes: number;
}

const TONE: Record<string, { background: string; color: string }> = {
  SNAPSHOT: { background: '#1e3a8a', color: '#bfdbfe' },
  APPEND: { background: '#022c22', color: '#86efac' },
  UPDATE: { background: '#78350f', color: '#fde68a' },
  DELETE: { background: '#7f1d1d', color: '#fecaca' },
};

function fmtBytes(b: number) {
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / (1024 * 1024)).toFixed(1)} MB`;
}

function tone(op: string) {
  return TONE[op.toUpperCase()] ?? { background: '#1e293b', color: '#cbd5e1' };
}

export function CurrentTransactionViewPanel({ head, composedOf, fileCount, totalBytes }: CurrentTransactionViewPanelProps) {
  return (
    <section style={{ display: 'grid', gap: 16 }}>
      <header>
        <div className="of-text-muted" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.22em' }}>Current transaction view</div>
        <h2 style={{ margin: '4px 0 0', fontSize: 18, fontWeight: 600 }}>HEAD of branch</h2>
        <p className="of-text-muted" style={{ margin: '4px 0 0', fontSize: 13 }}>The transaction whose contents make up the live view.</p>
      </header>

      {!head ? (
        <div className="of-text-muted" style={{ padding: 32, textAlign: 'center', borderRadius: 12, border: '1px dashed var(--border-default)', fontSize: 13 }}>
          No transactions have been committed yet.
        </div>
      ) : (
        <div className="of-panel" style={{ padding: 16 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}>
            <code style={{ fontSize: 11 }}>{head.id}</code>
            <span style={{ ...tone(head.operation), padding: '2px 8px', borderRadius: 999, fontSize: 10, textTransform: 'uppercase', fontWeight: 500 }}>
              {head.operation}
            </span>
          </div>
          <dl style={{ marginTop: 12, display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12, fontSize: 13 }}>
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-muted)' }}>Status</dt>
              <dd style={{ margin: '2px 0 0' }}>{head.status}</dd>
            </div>
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-muted)' }}>Branch</dt>
              <dd style={{ margin: '2px 0 0', fontFamily: 'var(--font-mono)', fontSize: 11 }}>{(head as DatasetTransaction & { branch_name?: string | null }).branch_name ?? '—'}</dd>
            </div>
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-muted)' }}>Created</dt>
              <dd style={{ margin: '2px 0 0' }}>{new Date(head.created_at).toLocaleString()}</dd>
            </div>
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-muted)' }}>Committed</dt>
              <dd style={{ margin: '2px 0 0' }}>{head.committed_at ? new Date(head.committed_at).toLocaleString() : '—'}</dd>
            </div>
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-muted)' }}>Files</dt>
              <dd style={{ margin: '2px 0 0' }}>{fileCount.toLocaleString()}</dd>
            </div>
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: 'var(--text-muted)' }}>Total size</dt>
              <dd style={{ margin: '2px 0 0' }}>{fmtBytes(totalBytes)}</dd>
            </div>
          </dl>
          {head.summary && <p style={{ marginTop: 12, fontSize: 13 }}>{head.summary}</p>}
        </div>
      )}

      {composedOf.length > 0 && (
        <div>
          <div className="of-text-muted" style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.04em' }}>Composed of</div>
          <ul className="of-panel" style={{ marginTop: 8, padding: 0, listStyle: 'none' }}>
            {composedOf.map((tx) => (
              <li
                key={tx.id}
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  gap: 12,
                  padding: '8px 12px',
                  borderBottom: '1px solid var(--border-subtle)',
                  fontSize: 13,
                }}
              >
                <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span style={{ ...tone(tx.operation), padding: '2px 8px', borderRadius: 999, fontSize: 10, textTransform: 'uppercase', fontWeight: 500 }}>{tx.operation}</span>
                  <code style={{ fontSize: 11 }}>{tx.id.slice(0, 12)}…</code>
                </span>
                <span className="of-text-muted" style={{ fontSize: 11 }}>{new Date(tx.created_at).toLocaleString()}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}
