// apps/web/src/lib/components/dataset/details/FilesTab.tsx
import { useEffect, useState } from 'react';

import { datasetFileDownloadUrl, listDatasetFiles, type DatasetFilesResponse } from '@/lib/api/datasets';

export type RetentionPurgeMarker = {
  policyName: string;
  daysUntilPurge: number;
};

interface FilesTabProps {
  datasetRid: string;
  branch?: string;
  viewId?: string;
  initialPrefix?: string;
  retentionPurges?: Record<string, RetentionPurgeMarker>;
  onOpenRetention?: () => void;
}

function fmtBytes(value: number) {
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  if (value < 1024 * 1024 * 1024) return `${(value / (1024 * 1024)).toFixed(1)} MB`;
  return `${(value / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

function shortSha(value?: string | null) {
  if (!value) return '—';
  return value.length > 12 ? `${value.slice(0, 12)}…` : value;
}

export function FilesTab({
  datasetRid,
  branch = 'master',
  viewId,
  initialPrefix = '',
  retentionPurges = {},
  onOpenRetention,
}: FilesTabProps) {
  const [response, setResponse] = useState<DatasetFilesResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [prefix, setPrefix] = useState(initialPrefix);

  useEffect(() => {
    if (!datasetRid) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    listDatasetFiles(datasetRid, { branch, view_id: viewId, prefix: prefix || undefined })
      .then((r) => { if (!cancelled) setResponse(r); })
      .catch((cause: unknown) => {
        if (!cancelled) {
          setError(cause instanceof Error ? cause.message : 'Files listing failed.');
          setResponse(null);
        }
      })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [datasetRid, branch, viewId, prefix]);

  const files = response?.files ?? [];

  return (
    <section style={{ display: 'grid', gap: 12 }}>
      <header className="of-panel" style={{ padding: 16, display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
        <div>
          <div style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--text-muted)', letterSpacing: '0.18em' }}>Files</div>
          <h2 style={{ margin: '4px 0 0', fontSize: 18, fontWeight: 600 }}>Backing filesystem</h2>
          <p className="of-text-muted" style={{ margin: '4px 0 0', fontSize: 13 }}>
            {files.length.toLocaleString()} file{files.length === 1 ? '' : 's'} on branch <code>{response?.branch ?? branch}</code>
          </p>
        </div>
        <input
          value={prefix}
          onChange={(e) => setPrefix(e.target.value)}
          placeholder="Filter by prefix…"
          className="of-input"
          style={{ fontSize: 12, fontFamily: 'var(--font-mono)', minWidth: 200 }}
        />
      </header>

      {loading && <div className="of-panel" style={{ padding: 16, fontSize: 13 }}>Loading files…</div>}
      {error && <div className="of-status-danger" style={{ padding: 16, borderRadius: 12, fontSize: 13 }}>{error}</div>}

      {response && (
        <div className="of-panel" style={{ overflow: 'auto' }}>
          <table style={{ width: '100%', fontSize: 12, borderCollapse: 'collapse' }}>
            <thead>
              <tr>
                {['Path', 'Size', 'SHA256', 'Tx', 'Modified', 'Status', ''].map((h) => (
                  <th key={h} style={{ textAlign: 'left', padding: '8px 12px', borderBottom: '1px solid var(--border-default)', fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.04em', color: 'var(--text-muted)' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {files.map((f) => {
                const purge = retentionPurges[f.id];
                const downloadUrl = datasetFileDownloadUrl(datasetRid, f.id);
                return (
                  <tr key={f.id} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                    <td style={{ padding: '8px 12px', fontFamily: 'var(--font-mono)' }}>
                      {f.logical_path}
                      {purge && (
                        <button
                          type="button"
                          onClick={onOpenRetention}
                          style={{ marginLeft: 8, fontSize: 10, padding: '1px 6px', borderRadius: 999, background: '#7f1d1d', color: '#fecaca', border: 'none', cursor: 'pointer', fontWeight: 600 }}
                        >
                          Purges in {purge.daysUntilPurge}d
                        </button>
                      )}
                    </td>
                    <td style={{ padding: '8px 12px' }}>{fmtBytes(f.size_bytes)}</td>
                    <td style={{ padding: '8px 12px', fontFamily: 'var(--font-mono)', fontSize: 11 }}>{shortSha(f.sha256)}</td>
                    <td style={{ padding: '8px 12px', fontFamily: 'var(--font-mono)', fontSize: 11 }}>{f.transaction_id?.slice(0, 8) ?? '—'}…</td>
                    <td style={{ padding: '8px 12px', color: 'var(--text-muted)' }}>{new Date(f.modified_at).toLocaleString()}</td>
                    <td style={{ padding: '8px 12px' }}>
                      <span style={{ padding: '2px 8px', borderRadius: 999, fontSize: 10, textTransform: 'uppercase', fontWeight: 500, ...(f.status === 'active' ? { background: '#022c22', color: '#86efac' } : { background: '#7f1d1d', color: '#fecaca' }) }}>
                        {f.status}
                      </span>
                    </td>
                    <td style={{ padding: '8px 12px' }}>
                      <a href={downloadUrl} className="of-button" style={{ fontSize: 11, padding: '2px 8px', textDecoration: 'none' }}>Download</a>
                    </td>
                  </tr>
                );
              })}
              {files.length === 0 && !loading && (
                <tr>
                  <td colSpan={7} style={{ padding: 16, textAlign: 'center', color: 'var(--text-muted)' }}>No files match the current filter.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </section>
  );
}

// apps/web/src/lib/components/dataset/details/FilesTab.svelte
<!--
  P3 — Files tab.

  Foundry-style listing backed by `dataset-versioning-service`'s
  `GET /v1/datasets/{rid}/files`. Surfaces the logical path, the
  size, sha256 (when present), the transaction that introduced it,
  the modified_at timestamp, and a badge for active vs deleted-in-
  current-view files. The download button hits the 302 endpoint so
  the browser follows the presigned URL.

  Virtualization: simple sliding window over the row array. The
  preview tab uses a richer virt component, but Files needs fewer
  columns (logical_path, size, sha256, txn, modified, status, action)
  and the dataset typically holds < 10k entries, so a plain windowed
  list is enough.
-->
<script lang="ts">
  import {
    datasetFileDownloadUrl,
    listDatasetFiles,
    type DatasetBackingFile,
    type DatasetFilesResponse,
  } from '$lib/api/datasets';

  /** P4 — retention purge marker keyed by file id. */
  export type RetentionPurgeMarker = {
    policyName: string;
    daysUntilPurge: number;
  };

  type Props = {
    datasetRid: string;
    branch?: string;
    viewId?: string;
    /** Initial prefix applied to the filter input. */
    initialPrefix?: string;
    /** Retention purge markers, keyed by dataset_files.id. */
    retentionPurges?: Record<string, RetentionPurgeMarker>;
    /** Click handler for the purge badge — typically routes the page
     *  to the Retention tab. */
    onOpenRetention?: () => void;
  };

  const {
    datasetRid,
    branch = 'master',
    viewId,
    initialPrefix = '',
    retentionPurges = {},
    onOpenRetention,
  }: Props = $props();

  let response = $state<DatasetFilesResponse | null>(null);
  let loading = $state(false);
  let errorMessage = $state<string | null>(null);
  // Seeded once from `initialPrefix`; subsequent edits live entirely in
  // the local `$state`. The `$effect` below re-fetches whenever the
  // prefix or other inputs change.
  let prefix = $state('');
  $effect(() => {
    if (initialPrefix && !prefix) prefix = initialPrefix;
  });
  let lastKey = $state('');

  $effect(() => {
    const key = JSON.stringify({ datasetRid, branch, viewId, prefix });
    if (!datasetRid) return;
    if (key === lastKey) return;
    lastKey = key;
    void load();
  });

  async function load() {
    loading = true;
    errorMessage = null;
    try {
      response = await listDatasetFiles(datasetRid, {
        branch,
        view_id: viewId,
        prefix: prefix || undefined,
      });
    } catch (cause) {
      errorMessage = cause instanceof Error ? cause.message : 'Files listing failed.';
      response = null;
    } finally {
      loading = false;
    }
  }

  function fmtBytes(value: number): string {
    if (value < 1024) return `${value} B`;
    if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
    if (value < 1024 * 1024 * 1024) return `${(value / (1024 * 1024)).toFixed(1)} MB`;
    return `${(value / (1024 * 1024 * 1024)).toFixed(2)} GB`;
  }

  function fmtDate(value: string): string {
    return new Date(value).toLocaleString();
  }

  function shortSha(value?: string | null): string {
    if (!value) return '—';
    return value.length > 12 ? value.slice(0, 12) + '…' : value;
  }

  const files: DatasetBackingFile[] = $derived(response?.files ?? []);
</script>

<section class="space-y-3" data-component="files-tab">
  <header class="flex flex-col gap-2 rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950 md:flex-row md:items-center md:justify-between">
    <div>
      <div class="text-xs uppercase tracking-[0.18em] text-slate-400">Files</div>
      <h2 class="mt-1 text-lg font-semibold">Backing filesystem</h2>
      <p class="mt-1 text-sm text-slate-500">
        {files.length.toLocaleString()} file{files.length === 1 ? '' : 's'} on branch
        <span class="font-mono">{response?.branch ?? branch}</span>
      </p>
    </div>
    <div class="flex flex-wrap items-center gap-2">
      <input
        type="search"
        placeholder="Filter by prefix"
        class="w-56 rounded-md border border-slate-300 bg-white px-2 py-1 text-sm dark:border-gray-700 dark:bg-gray-900"
        bind:value={prefix}
        data-testid="files-prefix-filter"
      />
      <button
        type="button"
        class="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-sm hover:bg-slate-50 dark:border-gray-700 dark:bg-gray-900 dark:hover:bg-gray-800"
        onclick={() => void load()}
      >
        Refresh
      </button>
    </div>
  </header>

  {#if loading}
    <div class="rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-300" role="status">
      Loading files...
    </div>
  {:else if errorMessage}
    <div class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800 dark:border-rose-900/50 dark:bg-rose-950/40 dark:text-rose-100" role="alert" data-testid="files-error">
      {errorMessage}
    </div>
  {:else if files.length === 0}
    <div class="rounded-lg border border-slate-200 bg-white px-4 py-6 text-center text-sm text-slate-500 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-400">
      No files visible on this branch / view.
    </div>
  {:else}
    <div class="overflow-x-auto rounded-lg border border-slate-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-950">
      <table class="min-w-full divide-y divide-slate-200 text-xs dark:divide-gray-800">
        <thead class="text-left uppercase tracking-wide text-slate-500">
          <tr>
            <th class="px-3 py-2">Logical path</th>
            <th class="px-3 py-2">Size</th>
            <th class="px-3 py-2">SHA-256</th>
            <th class="px-3 py-2">Transaction</th>
            <th class="px-3 py-2">Modified</th>
            <th class="px-3 py-2">Status</th>
            <th class="px-3 py-2"></th>
          </tr>
        </thead>
        <tbody class="divide-y divide-slate-100 font-mono dark:divide-gray-800" data-testid="files-rows">
          {#each files as file (file.id)}
            <tr data-testid="file-row" data-file-status={file.status} data-file-name={file.logical_path}>
              <td class="px-3 py-2 break-all">{file.logical_path}</td>
              <td class="px-3 py-2 whitespace-nowrap">{fmtBytes(file.size_bytes)}</td>
              <td class="px-3 py-2" title={file.sha256 ?? ''}>{shortSha(file.sha256)}</td>
              <td class="px-3 py-2" title={file.transaction_id}>{file.transaction_id.slice(0, 8)}</td>
              <td class="px-3 py-2 whitespace-nowrap">{fmtDate(file.modified_at)}</td>
              <td class="px-3 py-2">
                <span class={`rounded-full px-2 py-0.5 ${
                  file.status === 'active'
                    ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-200'
                    : 'bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-200'
                }`}>
                  {file.status === 'active' ? 'active' : 'deleted in current view'}
                </span>
                {#if retentionPurges[file.id]}
                  {@const marker = retentionPurges[file.id]}
                  <button
                    type="button"
                    class="ml-1 inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-amber-800 hover:bg-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:hover:bg-amber-900/60"
                    onclick={() => onOpenRetention?.()}
                    title={`Open the Retention tab — purge driven by ${marker.policyName}`}
                    data-testid="files-retention-badge"
                  >
                    Will be purged
                    {#if marker.daysUntilPurge <= 0}now{:else}in {marker.daysUntilPurge}d{/if}
                    by {marker.policyName}
                  </button>
                {/if}
              </td>
              <td class="px-3 py-2">
                {#if file.status === 'active'}
                  <a
                    class="text-blue-600 hover:underline dark:text-blue-300"
                    href={datasetFileDownloadUrl(datasetRid, file.id)}
                    data-testid="file-download"
                    target="_blank"
                    rel="noopener"
                  >
                    Download
                  </a>
                {:else}
                  <span class="text-slate-400">—</span>
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>
