// apps/web/src/lib/components/dataset/details/SchemaPanel.tsx
import { useState } from 'react';

export interface SchemaField {
  name: string;
  type: string;
  nullable?: boolean;
  description?: string;
  subSchemas?: SchemaField[];
  arraySubType?: SchemaField;
  mapKeyType?: SchemaField;
  mapValueType?: SchemaField;
  precision?: number;
  scale?: number;
}

interface SchemaPanelProps {
  fields: SchemaField[];
  options?: Record<string, string | number | boolean>;
  format?: string;
}

function isComplex(t: string) {
  const u = t.toUpperCase();
  return u.startsWith('STRUCT') || u.startsWith('ARRAY') || u.startsWith('MAP');
}

function renderType(field: SchemaField): string {
  const t = field.type.toUpperCase();
  if (t === 'DECIMAL' && field.precision !== undefined) return `DECIMAL(${field.precision},${field.scale ?? 0})`;
  return t;
}

function typeBadge(t: string) {
  const u = t.toUpperCase();
  if (u === 'STRING' || u === 'BINARY') return { background: '#3b1e6e', color: '#d8b4fe' };
  if (u === 'DATE' || u === 'TIMESTAMP') return { background: '#78350f', color: '#fde68a' };
  if (u === 'BOOLEAN') return { background: '#831843', color: '#fbcfe8' };
  if (u.startsWith('STRUCT') || u.startsWith('ARRAY') || u.startsWith('MAP')) return { background: '#022c22', color: '#86efac' };
  return { background: '#1e3a8a', color: '#bfdbfe' };
}

function Row({ field, depth, path, expanded, toggle }: { field: SchemaField; depth: number; path: string; expanded: Set<string>; toggle: (key: string) => void }) {
  const expandable = isComplex(field.type);
  const isOpen = expanded.has(path);
  const tone = typeBadge(field.type);
  return (
    <li style={{ borderBottom: '1px solid var(--border-subtle)' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: 8, paddingLeft: 12 + depth * 16, fontSize: 12 }}>
        {expandable ? (
          <button type="button" onClick={() => toggle(path)} aria-label={isOpen ? 'Collapse' : 'Expand'} style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: 0 }}>
            {isOpen ? '▾' : '▸'}
          </button>
        ) : (
          <span style={{ display: 'inline-block', width: 12 }} />
        )}
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>{field.name}</span>
        <span style={{ ...tone, padding: '2px 8px', borderRadius: 999, fontSize: 10, fontWeight: 500 }}>{renderType(field)}</span>
        {field.nullable === false && (
          <span style={{ background: 'var(--bg-subtle)', padding: '1px 6px', borderRadius: 999, fontSize: 10, textTransform: 'uppercase', color: 'var(--text-muted)' }}>NOT NULL</span>
        )}
        {field.description && <span className="of-text-muted" style={{ marginLeft: 8, fontSize: 11, overflow: 'hidden', textOverflow: 'ellipsis' }}>{field.description}</span>}
      </div>
      {expandable && isOpen && (
        <ul style={{ borderTop: '1px solid var(--border-subtle)', background: 'rgba(15,23,42,0.4)', listStyle: 'none', margin: 0, padding: 0 }}>
          {field.subSchemas?.map((c, i) => <Row key={`${c.name}.${i}`} field={c} depth={depth + 1} path={`${path}.${i}`} expanded={expanded} toggle={toggle} />)}
          {field.arraySubType && <Row field={{ ...field.arraySubType, name: '[item]' }} depth={depth + 1} path={`${path}.item`} expanded={expanded} toggle={toggle} />}
          {field.mapKeyType && <Row field={{ ...field.mapKeyType, name: '[key]' }} depth={depth + 1} path={`${path}.key`} expanded={expanded} toggle={toggle} />}
          {field.mapValueType && <Row field={{ ...field.mapValueType, name: '[value]' }} depth={depth + 1} path={`${path}.value`} expanded={expanded} toggle={toggle} />}
        </ul>
      )}
    </li>
  );
}

export function SchemaPanel({ fields, options = {}, format = '' }: SchemaPanelProps) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  function toggle(key: string) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }
  const optionEntries = Object.entries(options);
  return (
    <section style={{ display: 'grid', gap: 16 }}>
      <header>
        <div className="of-text-muted" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.22em' }}>Schema</div>
        <h2 style={{ margin: '4px 0 0', fontSize: 18, fontWeight: 600 }}>Columns</h2>
        <p className="of-text-muted" style={{ margin: '4px 0 0', fontSize: 13 }}>
          {fields.length} top-level field{fields.length === 1 ? '' : 's'}. Click any STRUCT / ARRAY / MAP to drill into nested types.
        </p>
      </header>
      {fields.length === 0 ? (
        <div className="of-text-muted" style={{ padding: 32, textAlign: 'center', borderRadius: 12, border: '1px dashed var(--border-default)', fontSize: 13 }}>
          Schema is inferred from the next quality profile or upload.
        </div>
      ) : (
        <ul className="of-panel" style={{ padding: 0, margin: 0, listStyle: 'none', overflow: 'hidden' }}>
          {fields.map((f, i) => <Row key={`${f.name}.${i}`} field={f} depth={0} path={String(i)} expanded={expanded} toggle={toggle} />)}
        </ul>
      )}
      {optionEntries.length > 0 && (
        <div className="of-panel" style={{ padding: 16 }}>
          <div className="of-text-muted" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.22em' }}>
            Format options{format ? ` · ${format}` : ''}
          </div>
          <dl style={{ marginTop: 8, display: 'grid', gap: 4, gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', fontSize: 12 }}>
            {optionEntries.map(([key, value]) => (
              <div key={key} style={{ display: 'flex', justifyContent: 'space-between', padding: '4px 8px', background: 'var(--bg-subtle)', borderRadius: 4 }}>
                <dt style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>{key}</dt>
                <dd style={{ margin: 0, fontFamily: 'var(--font-mono)', fontSize: 11 }}>{String(value)}</dd>
              </div>
            ))}
          </dl>
        </div>
      )}
    </section>
  );
}

// apps/web/src/lib/components/dataset/details/SchemaPanel.svelte
<!--
  T5.1 — SchemaPanel

  Renders a Foundry-style schema browser. The wire format here is a
  superset of the simple `{ name, field_type, nullable }` rows
  exposed today by `quality.profile.columns`, plus the recursive
  Foundry types: STRUCT (subSchemas), ARRAY (arraySubType), MAP
  (mapKeyType / mapValueType), DECIMAL (precision/scale), and
  primitives BOOLEAN/BYTE/SHORT/INTEGER/LONG/FLOAT/DOUBLE/STRING/
  BINARY/DATE/TIMESTAMP. A bottom block surfaces format-level
  `options` (e.g. CSV `has_header`, `delimiter`).

  Recursive expansion is local to each row so users can drill into
  one nested column without collapsing siblings.
-->
<script lang="ts" module>
  export type SchemaField = {
    name: string;
    type: string;
    nullable?: boolean;
    description?: string;
    /** STRUCT */
    subSchemas?: SchemaField[];
    /** ARRAY */
    arraySubType?: SchemaField;
    /** MAP */
    mapKeyType?: SchemaField;
    mapValueType?: SchemaField;
    /** DECIMAL */
    precision?: number;
    scale?: number;
  };

  // Stable, deterministic key for a row given its position in the
  // recursion. Using the depth + path of indices avoids the "two
  // STRUCT siblings with the same field name share expansion state"
  // bug while remaining stable across rerenders.
  export function rowKey(path: string): string {
    return path;
  }
</script>

<script lang="ts">
  type Props = {
    fields: SchemaField[];
    /** Format-level options (e.g. CSV `has_header`, `delimiter`). */
    options?: Record<string, string | number | boolean>;
    /** Format string ("PARQUET", "CSV", …) — only used to label the options block. */
    format?: string;
  };

  const { fields, options = {}, format = '' }: Props = $props();

  let expandedKeys = $state<Set<string>>(new Set());

  function toggle(key: string) {
    const next = new Set(expandedKeys);
    if (next.has(key)) next.delete(key);
    else next.add(key);
    expandedKeys = next;
  }

  function isComplex(t: string): boolean {
    const u = t.toUpperCase();
    return u.startsWith('STRUCT') || u.startsWith('ARRAY') || u.startsWith('MAP');
  }

  function renderType(field: SchemaField): string {
    const t = field.type.toUpperCase();
    if (t === 'DECIMAL' && field.precision !== undefined) {
      return `DECIMAL(${field.precision},${field.scale ?? 0})`;
    }
    return t;
  }

  function typeBadge(t: string): string {
    const u = t.toUpperCase();
    if (u === 'STRING' || u === 'BINARY')
      return 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300';
    if (u === 'DATE' || u === 'TIMESTAMP')
      return 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300';
    if (u === 'BOOLEAN') return 'bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300';
    if (u.startsWith('STRUCT') || u.startsWith('ARRAY') || u.startsWith('MAP'))
      return 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300';
    return 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300';
  }
</script>

<!--
  Recursive snippet:
    {@render row(field, depth)} renders one row. We don't reach for a
    separate component because Svelte 5 snippets handle the recursion
    cleanly and we get to keep state-less rendering.
-->
{#snippet row(field: SchemaField, depth: number, path: string)}
  {@const expandable = isComplex(field.type)}
  {@const expanded = expandedKeys.has(path)}
  <li class="border-b last:border-0 dark:border-gray-800">
    <div
      class="flex items-center gap-2 px-3 py-2 text-sm"
      style:padding-left={`${12 + depth * 16}px`}
    >
      {#if expandable}
        <button
          type="button"
          class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200"
          aria-label={expanded ? 'Collapse' : 'Expand'}
          onclick={() => toggle(path)}
        >
          {expanded ? '▾' : '▸'}
        </button>
      {:else}
        <span class="inline-block w-3"></span>
      {/if}
      <span class="font-mono text-xs">{field.name}</span>
      <span class={`rounded-full px-2 py-0.5 text-[10px] font-medium ${typeBadge(field.type)}`}>
        {renderType(field)}
      </span>
      {#if field.nullable === false}
        <span class="rounded-full bg-slate-100 px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-slate-600 dark:bg-gray-800 dark:text-gray-300">
          NOT NULL
        </span>
      {/if}
      {#if field.description}
        <span class="ml-2 truncate text-xs text-gray-500">{field.description}</span>
      {/if}
    </div>

    {#if expandable && expanded}
      <ul class="border-t bg-slate-50/50 dark:border-gray-800 dark:bg-gray-900/40">
        {#if field.subSchemas}
          {#each field.subSchemas as child, idx (child.name + idx)}
            {@render row(child, depth + 1, `${path}.${idx}`)}
          {/each}
        {/if}
        {#if field.arraySubType}
          {@render row({ ...field.arraySubType, name: '[item]' }, depth + 1, `${path}.item`)}
        {/if}
        {#if field.mapKeyType}
          {@render row({ ...field.mapKeyType, name: '[key]' }, depth + 1, `${path}.key`)}
        {/if}
        {#if field.mapValueType}
          {@render row({ ...field.mapValueType, name: '[value]' }, depth + 1, `${path}.value`)}
        {/if}
      </ul>
    {/if}
  </li>
{/snippet}

<section class="space-y-4">
  <header>
    <div class="text-xs uppercase tracking-[0.22em] text-gray-400">Schema</div>
    <h2 class="mt-1 text-lg font-semibold">Columns</h2>
    <p class="mt-1 text-sm text-gray-500">
      {fields.length} top-level field{fields.length === 1 ? '' : 's'}. Click any STRUCT / ARRAY /
      MAP to drill into nested types.
    </p>
  </header>

  {#if fields.length === 0}
    <div class="rounded-xl border border-dashed border-slate-300 px-4 py-8 text-center text-sm text-gray-500 dark:border-gray-700">
      Schema is inferred from the next quality profile or upload.
    </div>
  {:else}
    <ul class="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-gray-700 dark:bg-gray-900">
      {#each fields as field, idx (field.name + idx)}
        {@render row(field, 0, String(idx))}
      {/each}
    </ul>
  {/if}

  {#if Object.keys(options).length > 0}
    <div class="rounded-xl border border-slate-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
      <div class="text-xs uppercase tracking-[0.22em] text-gray-400">
        Format options{format ? ` · ${format}` : ''}
      </div>
      <dl class="mt-2 grid grid-cols-1 gap-1 text-sm md:grid-cols-2">
        {#each Object.entries(options) as [key, value] (key)}
          <div class="flex items-center justify-between rounded bg-slate-50 px-2 py-1 dark:bg-gray-800">
            <dt class="font-mono text-xs">{key}</dt>
            <dd class="font-mono text-xs">{String(value)}</dd>
          </div>
        {/each}
      </dl>
    </div>
  {/if}
</section>
