// apps/web/src/lib/components/dataset/details/StorageDetailsTab.svelte
<!--
  P3 — Storage details tab (manage role only).

  Surfaces the running BackingFsConfig (driver + base_directory +
  bucket / region / fs_id) plus the live GB consumed by the dataset's
  active and soft-deleted files. The data comes from the manage-only
  `GET /v1/datasets/{rid}/storage-details` endpoint, which returns a
  403 to non-manage callers — the parent gates the tab visibility but
  we re-render the 403 here so the failure is observable when a role
  flips mid-session.
-->
<script lang="ts">
  import {
    getDatasetStorageDetails,
    type DatasetStorageDetails,
  } from '$lib/api/datasets';

  type Props = {
    datasetRid: string;
  };

  const { datasetRid }: Props = $props();

  let details = $state<DatasetStorageDetails | null>(null);
  let loading = $state(false);
  let errorMessage = $state<string | null>(null);
  let lastKey = $state('');

  $effect(() => {
    if (!datasetRid || datasetRid === lastKey) return;
    lastKey = datasetRid;
    void load();
  });

  async function load() {
    loading = true;
    errorMessage = null;
    try {
      details = await getDatasetStorageDetails(datasetRid);
    } catch (cause) {
      errorMessage = cause instanceof Error ? cause.message : 'Storage details failed.';
      details = null;
    } finally {
      loading = false;
    }
  }

  function fmtBytes(value: number): string {
    if (value < 1024) return `${value} B`;
    if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
    if (value < 1024 * 1024 * 1024) return `${(value / (1024 * 1024)).toFixed(1)} MB`;
    return `${(value / (1024 * 1024 * 1024)).toFixed(2)} GB`;
  }

  function bucketFromFsId(fsId: string): string {
    if (fsId.startsWith('s3:')) return fsId.slice('s3:'.length);
    if (fsId.startsWith('hdfs:')) return fsId.slice('hdfs:'.length);
    return '—';
  }
</script>

<section class="space-y-3" data-component="storage-details-tab">
  <header class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
    <div class="text-xs uppercase tracking-[0.18em] text-slate-400">Storage</div>
    <h2 class="mt-1 text-lg font-semibold">Backing filesystem details</h2>
    <p class="mt-1 text-sm text-slate-500">
      Foundry-style storage configuration for this dataset's underlying file system.
      Visible only to users with dataset-manage permission.
    </p>
  </header>

  {#if loading}
    <div class="rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-300" role="status">
      Loading storage details...
    </div>
  {:else if errorMessage}
    <div class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800 dark:border-rose-900/50 dark:bg-rose-950/40 dark:text-rose-100" role="alert" data-testid="storage-details-error">
      {errorMessage}
    </div>
  {:else if details}
    <div class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4" data-testid="storage-details-cards">
      {@render Card('Driver', details.driver.toUpperCase())}
      {@render Card('FS id', details.fs_id, true)}
      {@render Card('Base directory', details.base_directory, true)}
      {@render Card('Bucket / namenode', bucketFromFsId(details.fs_id), true)}
    </div>

    <div class="grid grid-cols-1 gap-3 md:grid-cols-3">
      {@render Card('Active storage', fmtBytes(details.total_active_bytes))}
      {@render Card('Active files', details.total_active_files.toLocaleString())}
      {@render Card('Soft-deleted storage', fmtBytes(details.total_deleted_bytes))}
    </div>

    <div class="rounded-lg border border-slate-200 bg-white p-4 text-xs text-slate-500 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-400">
      Presigned download URLs expire after
      <span class="font-mono">{details.presign_ttl_seconds}s</span>. Adjust via
      <span class="font-mono">OF_BACKING_FS_PRESIGN_TTL_SECONDS</span>.
    </div>
  {/if}
</section>

{#snippet Card(label: string, value: string, mono = false)}
  <div class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
    <div class="text-xs uppercase tracking-[0.18em] text-slate-400">{label}</div>
    <div class={`mt-2 ${mono ? 'font-mono break-all text-sm' : 'text-2xl font-semibold'}`}>{value}</div>
  </div>
{/snippet}

// apps/web/src/lib/components/dataset/details/StorageDetailsTab.tsx
import { useEffect, useState } from 'react';

import { getDatasetStorageDetails, type DatasetStorageDetails } from '@/lib/api/datasets';

interface StorageDetailsTabProps {
  datasetRid: string;
}

function fmtBytes(value: number) {
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  if (value < 1024 * 1024 * 1024) return `${(value / (1024 * 1024)).toFixed(1)} MB`;
  return `${(value / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

function bucketFromFsId(fsId: string) {
  if (fsId.startsWith('s3:')) return fsId.slice(3);
  if (fsId.startsWith('hdfs:')) return fsId.slice(5);
  return '—';
}

function Card({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="of-panel" style={{ padding: 16 }}>
      <div style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--text-muted)', letterSpacing: '0.18em' }}>{label}</div>
      <div
        style={{
          marginTop: 8,
          ...(mono
            ? { fontFamily: 'var(--font-mono)', fontSize: 13, wordBreak: 'break-all' }
            : { fontSize: 24, fontWeight: 600 }),
        }}
      >
        {value}
      </div>
    </div>
  );
}

export function StorageDetailsTab({ datasetRid }: StorageDetailsTabProps) {
  const [details, setDetails] = useState<DatasetStorageDetails | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!datasetRid) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    getDatasetStorageDetails(datasetRid)
      .then((d) => { if (!cancelled) setDetails(d); })
      .catch((cause: unknown) => {
        if (!cancelled) {
          setError(cause instanceof Error ? cause.message : 'Storage details failed.');
          setDetails(null);
        }
      })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [datasetRid]);

  return (
    <section style={{ display: 'grid', gap: 12 }}>
      <header className="of-panel" style={{ padding: 16 }}>
        <div style={{ fontSize: 11, textTransform: 'uppercase', color: 'var(--text-muted)', letterSpacing: '0.18em' }}>Storage</div>
        <h2 style={{ margin: '4px 0 0', fontSize: 18, fontWeight: 600 }}>Backing filesystem details</h2>
        <p className="of-text-muted" style={{ margin: '4px 0 0', fontSize: 13 }}>
          Foundry-style storage configuration. Visible only to users with dataset-manage permission.
        </p>
      </header>
      {loading && <div role="status" className="of-panel" style={{ padding: 16, fontSize: 13 }}>Loading storage details…</div>}
      {error && <div role="alert" className="of-status-danger" style={{ padding: 16, fontSize: 13 }}>{error}</div>}
      {details && (
        <>
          <div style={{ display: 'grid', gap: 12, gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))' }}>
            <Card label="Driver" value={details.driver.toUpperCase()} />
            <Card label="FS id" value={details.fs_id} mono />
            <Card label="Base directory" value={details.base_directory} mono />
            <Card label="Bucket / namenode" value={bucketFromFsId(details.fs_id)} mono />
          </div>
          <div style={{ display: 'grid', gap: 12, gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))' }}>
            <Card label="Active storage" value={fmtBytes(details.total_active_bytes)} />
            <Card label="Active files" value={details.total_active_files.toLocaleString()} />
            <Card label="Soft-deleted storage" value={fmtBytes(details.total_deleted_bytes)} />
          </div>
          <div className="of-panel" style={{ padding: 16, fontSize: 11, color: 'var(--text-muted)' }}>
            Presigned download URLs expire after <code>{details.presign_ttl_seconds}s</code>. Adjust via{' '}
            <code>OF_BACKING_FS_PRESIGN_TTL_SECONDS</code>.
          </div>
        </>
      )}
    </section>
  );
}
