// apps/web/src/lib/components/dataset/CreateBranchDialog.tsx
import { useEffect, useState } from 'react';

import { createBranchV2, type DatasetBranch } from '@/lib/api/datasets';

interface CreateBranchDialogProps {
  datasetRid: string;
  open: boolean;
  branches: DatasetBranch[];
  onClose: () => void;
  onCreated?: (branch: DatasetBranch) => void;
}

type Mode = 'from_branch' | 'from_transaction' | 'as_root';

export function CreateBranchDialog({ datasetRid, open, branches, onClose, onCreated }: CreateBranchDialogProps) {
  const [mode, setMode] = useState<Mode>('from_branch');
  const [name, setName] = useState('');
  const [fromBranch, setFromBranch] = useState('master');
  const [fromTxnRid, setFromTxnRid] = useState('');
  const [fallbackChainRaw, setFallbackChainRaw] = useState('');
  const [labelsRaw, setLabelsRaw] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (open) {
      setMode(branches.length === 0 ? 'as_root' : 'from_branch');
      setName('');
      setFromBranch(branches.find((b) => b.is_default)?.name ?? branches[0]?.name ?? 'master');
      setFromTxnRid('');
      setFallbackChainRaw('');
      setLabelsRaw('');
      setError('');
    }
  }, [open, branches]);

  function parseFallback() {
    return fallbackChainRaw.split(',').map((s) => s.trim()).filter(Boolean);
  }

  function parseLabels(): Record<string, string> | undefined {
    const out: Record<string, string> = {};
    for (const part of labelsRaw.split(',')) {
      const [k, v] = part.split('=').map((s) => s.trim());
      if (k && v) out[k] = v;
    }
    return Object.keys(out).length ? out : undefined;
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!name.trim()) {
      setError('Branch name is required');
      return;
    }
    let source;
    if (mode === 'from_branch') {
      if (!fromBranch.trim()) { setError('Source branch is required'); return; }
      source = { from_branch: fromBranch.trim() };
    } else if (mode === 'from_transaction') {
      if (!fromTxnRid.trim()) { setError('Source transaction RID is required'); return; }
      source = { from_transaction_rid: fromTxnRid.trim() };
    } else {
      source = { as_root: true as const };
    }
    setBusy(true);
    setError('');
    try {
      const branch = await createBranchV2(datasetRid, {
        name: name.trim(),
        source,
        fallback_chain: parseFallback(),
        labels: parseLabels(),
      });
      onCreated?.(branch);
      onClose();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Failed to create branch');
    } finally {
      setBusy(false);
    }
  }

  if (!open) return null;

  return (
    <div role="dialog" aria-modal="true" style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 }}>
      <form onSubmit={submit} style={{ width: '100%', maxWidth: 520, padding: 20, borderRadius: 16, background: '#0f172a', color: '#e2e8f0', boxShadow: '0 20px 50px rgba(0,0,0,0.5)', border: '1px solid #1e293b', display: 'grid', gap: 12 }}>
        <h2 style={{ margin: 0, fontSize: 18, fontWeight: 600 }}>Create branch</h2>

        <label style={{ fontSize: 13 }}>
          Branch name
          <input value={name} onChange={(e) => setName(e.target.value)} required placeholder="feature-x" className="of-input" style={{ marginTop: 4 }} />
        </label>

        <fieldset style={{ border: '1px solid #1e293b', borderRadius: 6, padding: 12 }}>
          <legend style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.04em', color: '#94a3b8', padding: '0 6px' }}>Source</legend>
          <label style={{ display: 'flex', gap: 8, alignItems: 'flex-start', fontSize: 13 }}>
            <input type="radio" name="mode" checked={mode === 'from_branch'} onChange={() => setMode('from_branch')} />
            <span style={{ flex: 1 }}>
              <strong>From another branch</strong>
              <select value={fromBranch} onChange={(e) => setFromBranch(e.target.value)} disabled={mode !== 'from_branch'} className="of-input" style={{ marginTop: 4, width: '100%' }}>
                {branches.map((b) => <option key={b.id} value={b.name}>{b.name}{b.is_default ? ' (default)' : ''}</option>)}
              </select>
            </span>
          </label>
          <label style={{ display: 'flex', gap: 8, alignItems: 'flex-start', fontSize: 13, marginTop: 8 }}>
            <input type="radio" name="mode" checked={mode === 'from_transaction'} onChange={() => setMode('from_transaction')} />
            <span style={{ flex: 1 }}>
              <strong>From a specific transaction</strong>
              <input value={fromTxnRid} onChange={(e) => setFromTxnRid(e.target.value)} placeholder="ri.foundry.main.transaction.…" disabled={mode !== 'from_transaction'} className="of-input" style={{ marginTop: 4, width: '100%', fontFamily: 'var(--font-mono)', fontSize: 11 }} />
            </span>
          </label>
          <label style={{ display: 'flex', gap: 8, alignItems: 'flex-start', fontSize: 13, marginTop: 8 }}>
            <input type="radio" name="mode" checked={mode === 'as_root'} onChange={() => setMode('as_root')} disabled={branches.length > 0} />
            <span style={{ flex: 1 }}>
              <strong>As root branch</strong>
              <span style={{ display: 'block', fontSize: 11, color: '#94a3b8' }}>
                Only valid when the dataset has no other branches yet.
              </span>
            </span>
          </label>
        </fieldset>

        <label style={{ fontSize: 13 }}>
          Fallback chain (comma-separated)
          <input value={fallbackChainRaw} onChange={(e) => setFallbackChainRaw(e.target.value)} placeholder="develop, master" className="of-input" style={{ marginTop: 4 }} />
        </label>

        <label style={{ fontSize: 13 }}>
          Labels (key=value, comma-separated)
          <input value={labelsRaw} onChange={(e) => setLabelsRaw(e.target.value)} placeholder="persona=data-eng, ticket=PR-123" className="of-input" style={{ marginTop: 4 }} />
        </label>

        {error && <p style={{ fontSize: 11, color: '#fca5a5' }}>{error}</p>}

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
          <button type="button" onClick={onClose} className="of-button">Cancel</button>
          <button type="submit" disabled={busy} className="of-button of-button--primary">Create</button>
        </div>
      </form>
    </div>
  );
}

// apps/web/src/lib/components/dataset/CreateBranchDialog.svelte
<!--
  P3 — CreateBranchDialog

  Modal that drives the P1 v2 source-aware create-branch flow:
    * source = `from_branch` → pick a parent branch (default "master")
    * source = `from_transaction` → paste a transaction RID
    * source = `as_root` → only allowed when the dataset has none yet

  Plus a fallback-chain editor (comma-separated branch names; trimmed).
-->
<script lang="ts">
  import {
    createBranchV2,
    type DatasetBranch,
  } from '$lib/api/datasets';
  import { ApiError } from '$lib/api/client';

  type Props = {
    datasetRid: string;
    open: boolean;
    branches: DatasetBranch[];
    onClose: () => void;
    onCreated?: (branch: DatasetBranch) => void;
  };

  const { datasetRid, open, branches, onClose, onCreated }: Props = $props();

  let mode = $state<'from_branch' | 'from_transaction' | 'as_root'>('from_branch');
  let name = $state('');
  let fromBranch = $state('master');
  let fromTxnRid = $state('');
  let fallbackChainRaw = $state('');
  let labelsRaw = $state('');
  let busy = $state(false);
  let error = $state('');

  $effect(() => {
    if (open) {
      mode = branches.length === 0 ? 'as_root' : 'from_branch';
      name = '';
      fromBranch = branches.find((b) => b.is_default)?.name ?? branches[0]?.name ?? 'master';
      fromTxnRid = '';
      fallbackChainRaw = '';
      labelsRaw = '';
      error = '';
    }
  });

  function parseFallback(): string[] {
    return fallbackChainRaw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
  }

  function parseLabels(): Record<string, string> | undefined {
    const out: Record<string, string> = {};
    for (const part of labelsRaw.split(',')) {
      const trimmed = part.trim();
      if (!trimmed) continue;
      const [k, v] = trimmed.split('=').map((s) => s.trim());
      if (k && v) out[k] = v;
    }
    return Object.keys(out).length ? out : undefined;
  }

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    if (!name.trim()) {
      error = 'Branch name is required';
      return;
    }
    let source;
    if (mode === 'from_branch') {
      if (!fromBranch.trim()) {
        error = 'Source branch is required';
        return;
      }
      source = { from_branch: fromBranch.trim() };
    } else if (mode === 'from_transaction') {
      if (!fromTxnRid.trim()) {
        error = 'Source transaction RID is required';
        return;
      }
      source = { from_transaction_rid: fromTxnRid.trim() };
    } else {
      source = { as_root: true as const };
    }
    busy = true;
    error = '';
    try {
      const branch = await createBranchV2(datasetRid, {
        name: name.trim(),
        source,
        fallback_chain: parseFallback(),
        labels: parseLabels(),
      });
      onCreated?.(branch);
      onClose();
    } catch (cause) {
      error = cause instanceof ApiError ? cause.message : 'Failed to create branch';
    } finally {
      busy = false;
    }
  }
</script>

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
    role="dialog"
    aria-modal="true"
    data-testid="create-branch-dialog"
  >
    <form
      class="w-full max-w-lg space-y-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-xl dark:border-gray-700 dark:bg-gray-900"
      onsubmit={submit}
    >
      <h2 class="text-lg font-semibold">Create branch</h2>

      <label class="block text-sm">
        <span class="text-gray-500">Branch name</span>
        <input
          type="text"
          bind:value={name}
          placeholder="feature-x"
          class="mt-1 block w-full rounded border border-slate-300 px-2 py-1 dark:border-gray-700 dark:bg-gray-800"
          data-testid="create-branch-name"
          required
        />
      </label>

      <fieldset class="rounded border border-slate-200 px-3 py-2 text-sm dark:border-gray-700">
        <legend class="px-1 text-xs uppercase tracking-wide text-gray-500">Source</legend>
        <label class="flex items-start gap-2">
          <input type="radio" bind:group={mode} value="from_branch" data-testid="create-branch-source-from-branch" />
          <span>
            <span class="font-medium">From another branch</span>
            <select
              bind:value={fromBranch}
              class="mt-1 block w-full rounded border border-slate-300 px-2 py-1 dark:border-gray-700 dark:bg-gray-800"
              disabled={mode !== 'from_branch'}
              data-testid="create-branch-from-branch-select"
            >
              {#each branches as b (b.id)}
                <option value={b.name}>{b.name}{b.is_default ? ' (default)' : ''}</option>
              {/each}
            </select>
          </span>
        </label>
        <label class="mt-2 flex items-start gap-2">
          <input type="radio" bind:group={mode} value="from_transaction" data-testid="create-branch-source-from-transaction" />
          <span>
            <span class="font-medium">From a specific transaction</span>
            <input
              type="text"
              bind:value={fromTxnRid}
              placeholder="ri.foundry.main.transaction.…"
              class="mt-1 block w-full rounded border border-slate-300 px-2 py-1 font-mono text-xs dark:border-gray-700 dark:bg-gray-800"
              disabled={mode !== 'from_transaction'}
              data-testid="create-branch-from-transaction-input"
            />
          </span>
        </label>
        <label class="mt-2 flex items-start gap-2">
          <input
            type="radio"
            bind:group={mode}
            value="as_root"
            disabled={branches.length > 0}
            data-testid="create-branch-source-as-root"
          />
          <span>
            <span class="font-medium">As root branch</span>
            <span class="block text-xs text-gray-500">
              Only valid when the dataset has no other branches yet.
            </span>
          </span>
        </label>
      </fieldset>

      <label class="block text-sm">
        <span class="text-gray-500">Fallback chain (comma-separated)</span>
        <input
          type="text"
          bind:value={fallbackChainRaw}
          placeholder="develop, master"
          class="mt-1 block w-full rounded border border-slate-300 px-2 py-1 dark:border-gray-700 dark:bg-gray-800"
          data-testid="create-branch-fallback-chain"
        />
      </label>

      <label class="block text-sm">
        <span class="text-gray-500">Labels (key=value, comma-separated)</span>
        <input
          type="text"
          bind:value={labelsRaw}
          placeholder="persona=data-eng, ticket=PR-123"
          class="mt-1 block w-full rounded border border-slate-300 px-2 py-1 dark:border-gray-700 dark:bg-gray-800"
          data-testid="create-branch-labels"
        />
      </label>

      {#if error}
        <p class="text-xs text-rose-600 dark:text-rose-300">{error}</p>
      {/if}

      <div class="flex justify-end gap-2 pt-2">
        <button
          type="button"
          class="rounded border border-slate-300 px-3 py-1 text-sm hover:bg-slate-50 dark:border-gray-700 dark:hover:bg-gray-800"
          onclick={onClose}
          data-testid="create-branch-cancel"
        >Cancel</button>
        <button
          type="submit"
          class="rounded bg-blue-600 px-3 py-1 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
          disabled={busy}
          data-testid="create-branch-submit"
        >Create</button>
      </div>
    </form>
  </div>
{/if}
