// apps/web/src/lib/components/dataset/HistoryTimeline.tsx
import type { DatasetTransaction } from '@/lib/api/datasets';

export type RetentionPurgeMarker = {
  policyName: string;
  daysUntilPurge: number;
};

interface HistoryTimelineProps {
  transactions: DatasetTransaction[];
  rollingBack?: string | null;
  onView?: (tx: DatasetTransaction) => void;
  onRollback?: (tx: DatasetTransaction) => void | Promise<void>;
  retentionPurges?: Record<string, RetentionPurgeMarker>;
  onOpenRetention?: () => void;
}

const TONE: Record<string, { border: string; bg: string }> = {
  SNAPSHOT: { border: '#1e40af', bg: '#172554' },
  APPEND: { border: '#047857', bg: '#022c22' },
  UPDATE: { border: '#b45309', bg: '#78350f' },
  DELETE: { border: '#b91c1c', bg: '#7f1d1d' },
};

function icon(op: string) {
  const u = op.toUpperCase();
  if (u === 'SNAPSHOT') return '📸';
  if (u === 'APPEND') return '➕';
  if (u === 'UPDATE') return '✏️';
  if (u === 'DELETE') return '🗑️';
  return '•';
}

function delta(tx: DatasetTransaction) {
  const added = Number(tx.metadata?.['files_added'] ?? 0);
  const removed = Number(tx.metadata?.['files_removed'] ?? 0);
  const parts: string[] = [];
  if (added) parts.push(`+${added}`);
  if (removed) parts.push(`−${removed}`);
  return parts.join(' / ') || '—';
}

function author(tx: DatasetTransaction) {
  const a = tx.metadata?.['author'];
  return typeof a === 'string' ? a : 'system';
}

export function HistoryTimeline({
  transactions,
  rollingBack = null,
  onView,
  onRollback,
  retentionPurges = {},
  onOpenRetention,
}: HistoryTimelineProps) {
  return (
    <section style={{ display: 'grid', gap: 12 }}>
      <header>
        <div className="of-text-muted" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.22em' }}>History</div>
        <h2 style={{ margin: '4px 0 0', fontSize: 18, fontWeight: 600 }}>Transaction timeline</h2>
        <p style={{ margin: '4px 0 0', fontSize: 13, color: 'var(--text-muted)' }}>
          {transactions.length} transaction{transactions.length === 1 ? '' : 's'} on the active branch.
        </p>
      </header>

      {transactions.length === 0 ? (
        <div className="of-text-muted" style={{ padding: 32, textAlign: 'center', borderRadius: 12, border: '1px dashed var(--border-default)', fontSize: 13 }}>
          No transactions yet.
        </div>
      ) : (
        <ol style={{ paddingLeft: 20, margin: 0, borderLeft: '1px solid var(--border-default)', display: 'grid', gap: 12, listStyle: 'none' }}>
          {transactions.map((tx) => {
            const tone = TONE[tx.operation.toUpperCase()] ?? { border: '#475569', bg: '#1e293b' };
            const marker = retentionPurges[tx.id];
            return (
              <li
                key={tx.id}
                style={{
                  padding: 12,
                  borderRadius: 12,
                  background: tone.bg,
                  boxShadow: `inset 0 0 0 1px ${tone.border}`,
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 }}>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <span style={{ fontSize: 18, lineHeight: 1 }} aria-hidden="true">{icon(tx.operation)}</span>
                    <div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, fontWeight: 500 }}>
                        <span style={{ textTransform: 'uppercase' }}>{tx.operation}</span>
                        <span style={{ background: 'rgba(255,255,255,0.1)', padding: '2px 8px', borderRadius: 999, fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                          {tx.status}
                        </span>
                      </div>
                      <div style={{ marginTop: 2, fontSize: 11, opacity: 0.8 }}>
                        {author(tx)} · {new Date(tx.created_at).toLocaleString()} · files {delta(tx)}
                      </div>
                      <div style={{ marginTop: 2, fontFamily: 'var(--font-mono)', fontSize: 10, opacity: 0.6 }}>{tx.id}</div>
                      {tx.summary && <p style={{ margin: '4px 0 0', fontSize: 13 }}>{tx.summary}</p>}
                      {marker && (
                        <button
                          type="button"
                          onClick={() => onOpenRetention?.()}
                          style={{
                            marginTop: 4,
                            padding: '2px 8px',
                            borderRadius: 999,
                            background: '#7f1d1d',
                            color: '#fecaca',
                            border: 'none',
                            cursor: 'pointer',
                            fontSize: 10,
                            fontWeight: 600,
                            textTransform: 'uppercase',
                          }}
                        >
                          Will be purged{' '}
                          {marker.daysUntilPurge <= 0 ? 'now' : `in ${marker.daysUntilPurge}d`} by {marker.policyName}
                        </button>
                      )}
                    </div>
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                    <button type="button" onClick={() => onView?.(tx)} className="of-button" style={{ fontSize: 11 }}>
                      View at this point in time
                    </button>
                    <button
                      type="button"
                      onClick={() => void onRollback?.(tx)}
                      disabled={rollingBack === tx.id}
                      className="of-button"
                      style={{ fontSize: 11 }}
                    >
                      {rollingBack === tx.id ? 'Rolling back…' : 'Roll back to this transaction'}
                    </button>
                  </div>
                </div>
              </li>
            );
          })}
        </ol>
      )}
    </section>
  );
}

// apps/web/src/lib/components/dataset/HistoryTimeline.svelte
<!--
  T5.3 — HistoryTimeline

  Vertical timeline of every transaction on the active branch. Each
  row carries an icon by transaction type (SNAPSHOT / APPEND / UPDATE
  / DELETE), the author, the +/- file count delta, and two actions:

    * "View at this point in time" — emits an `onView` callback with
      the transaction id so the parent can redirect to the Preview
      tab pinned to that transaction.
    * "Roll back to this transaction" — emits `onRollback` so the
      parent can call the dataset-versioning-service endpoint that
      creates a new SNAPSHOT with the chosen view's contents.
-->
<script lang="ts">
  import type { DatasetTransaction } from '$lib/api/datasets';

  /** P4 — retention preview marker keyed by transaction id. The
   *  parent fetches `getRetentionPreview` and forwards a map of the
   *  txns flagged `would_delete = true` so the timeline can surface a
   *  "purged in N days" badge cross-linking to the Retention tab. */
  export type RetentionPurgeMarker = {
    policyName: string;
    daysUntilPurge: number;
  };

  type Props = {
    transactions: DatasetTransaction[];
    /** True while a rollback is in flight so we can disable buttons. */
    rollingBack?: string | null;
    onView?: (tx: DatasetTransaction) => void;
    onRollback?: (tx: DatasetTransaction) => void | Promise<void>;
    /** Retention purge markers, keyed by transaction id. */
    retentionPurges?: Record<string, RetentionPurgeMarker>;
    /** Click handler for the purge badge — typically navigates the
     *  parent to the Retention tab. */
    onOpenRetention?: () => void;
  };

  const {
    transactions,
    rollingBack = null,
    onView = () => {},
    onRollback = () => {},
    retentionPurges = {},
    onOpenRetention,
  }: Props = $props();

  function icon(op: string): string {
    const u = op.toUpperCase();
    if (u === 'SNAPSHOT') return '📸';
    if (u === 'APPEND') return '➕';
    if (u === 'UPDATE') return '✏️';
    if (u === 'DELETE') return '🗑️';
    return '•';
  }

  function tone(op: string): string {
    const u = op.toUpperCase();
    if (u === 'SNAPSHOT')
      return 'border-blue-300 bg-blue-50 dark:border-blue-900/40 dark:bg-blue-950/30';
    if (u === 'APPEND')
      return 'border-emerald-300 bg-emerald-50 dark:border-emerald-900/40 dark:bg-emerald-950/30';
    if (u === 'UPDATE')
      return 'border-amber-300 bg-amber-50 dark:border-amber-900/40 dark:bg-amber-950/30';
    if (u === 'DELETE')
      return 'border-rose-300 bg-rose-50 dark:border-rose-900/40 dark:bg-rose-950/30';
    return 'border-slate-300 bg-slate-50 dark:border-slate-700 dark:bg-slate-900/40';
  }

  function delta(tx: DatasetTransaction): string {
    const added = Number(tx.metadata?.['files_added'] ?? 0);
    const removed = Number(tx.metadata?.['files_removed'] ?? 0);
    const parts: string[] = [];
    if (added) parts.push(`+${added}`);
    if (removed) parts.push(`−${removed}`);
    return parts.join(' / ') || '—';
  }

  function author(tx: DatasetTransaction): string {
    const a = tx.metadata?.['author'];
    if (typeof a === 'string') return a;
    return 'system';
  }
</script>

<section class="space-y-3">
  <header>
    <div class="text-xs uppercase tracking-[0.22em] text-gray-400">History</div>
    <h2 class="mt-1 text-lg font-semibold">Transaction timeline</h2>
    <p class="mt-1 text-sm text-gray-500">
      {transactions.length} transaction{transactions.length === 1 ? '' : 's'} on the active branch.
    </p>
  </header>

  {#if transactions.length === 0}
    <div class="rounded-xl border border-dashed border-slate-300 px-4 py-8 text-center text-sm text-gray-500 dark:border-gray-700">
      No transactions yet.
    </div>
  {:else}
    <ol class="relative space-y-3 border-l border-slate-200 pl-5 dark:border-gray-700">
      {#each transactions as tx (tx.id)}
        <li class={`rounded-xl border p-3 ${tone(tx.operation)}`}>
          <div class="flex items-start justify-between gap-3">
            <div class="flex items-start gap-2">
              <span class="text-lg leading-none" aria-hidden="true">{icon(tx.operation)}</span>
              <div>
                <div class="flex items-center gap-2 text-sm font-medium">
                  <span class="uppercase">{tx.operation}</span>
                  <span class="rounded-full bg-white/60 px-2 py-0.5 text-[10px] uppercase tracking-wide text-gray-700 dark:bg-gray-800/60 dark:text-gray-200">
                    {tx.status}
                  </span>
                </div>
                <div class="mt-0.5 text-xs text-gray-600 dark:text-gray-300">
                  {author(tx)} · {new Date(tx.created_at).toLocaleString()} · files {delta(tx)}
                </div>
                <div class="mt-0.5 font-mono text-[10px] text-gray-500">{tx.id}</div>
                {#if tx.summary}
                  <p class="mt-1 text-sm">{tx.summary}</p>
                {/if}
                {#if retentionPurges[tx.id]}
                  {@const marker = retentionPurges[tx.id]}
                  <button
                    type="button"
                    class="mt-1 inline-flex items-center gap-1 rounded-full bg-rose-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-rose-800 hover:bg-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:hover:bg-rose-900/60"
                    title="Open the Retention tab"
                    onclick={() => onOpenRetention?.()}
                    data-testid="history-retention-badge"
                  >
                    Will be purged
                    {#if marker.daysUntilPurge <= 0}now{:else}in {marker.daysUntilPurge}d{/if}
                    by {marker.policyName}
                  </button>
                {/if}
              </div>
            </div>
            <div class="flex shrink-0 flex-col gap-1">
              <button
                type="button"
                class="rounded-md border border-slate-300 px-2 py-1 text-xs hover:bg-white dark:border-gray-700 dark:hover:bg-gray-800"
                onclick={() => onView(tx)}
              >
                View at this point in time
              </button>
              <button
                type="button"
                class="rounded-md border border-slate-300 px-2 py-1 text-xs hover:bg-white disabled:opacity-50 dark:border-gray-700 dark:hover:bg-gray-800"
                disabled={rollingBack === tx.id}
                onclick={() => onRollback(tx)}
              >
                {rollingBack === tx.id ? 'Rolling back…' : 'Roll back to this transaction'}
              </button>
            </div>
          </div>
        </li>
      {/each}
    </ol>
  {/if}
</section>
