// apps/web/src/lib/components/dataset/OpenTransactionBanner.svelte
<!--
  P3 — OpenTransactionBanner

  Persistent ámbar banner shown on `/datasets/[id]` when the active
  branch carries `has_open_transaction = true`. Mirrors the Foundry
  guarantee: while a branch points at an OPEN transaction, no further
  transactions can be started until the OPEN one is committed or
  aborted.

  Wired actions:
    * "View transaction"  — deep links into `?tab=history&txn=<id>`,
      which scrolls HistoryTimeline to the highlighted row.
    * "Commit"  — `POST /branches/{branch}/transactions/{txn}:commit`
      (gated by `canManage`).
    * "Abort"   — `POST /branches/{branch}/transactions/{txn}:abort`.

  The component is dumb about the open-tx ID: the parent page resolves
  it (typically by listing transactions where `status = OPEN`) and
  passes the value down. When `openTransactionId` is null the banner
  is rendered in a degraded "No transaction id available" state for
  diagnostic visibility.
-->
<script lang="ts">
  import {
    abortTransaction,
    commitTransaction,
  } from '$lib/api/datasets';
  import { ApiError } from '$lib/api/client';

  type Props = {
    datasetId: string;
    branch: string;
    openTransactionId: string | null;
    canManage: boolean;
    onResolved?: () => void;
  };

  const { datasetId, branch, openTransactionId, canManage, onResolved }: Props = $props();

  let busy = $state(false);
  let error = $state('');

  async function commit() {
    if (!openTransactionId) return;
    busy = true;
    error = '';
    try {
      await commitTransaction(datasetId, branch, openTransactionId);
      onResolved?.();
    } catch (cause) {
      error = cause instanceof ApiError ? cause.message : 'Commit failed';
    } finally {
      busy = false;
    }
  }

  async function abort() {
    if (!openTransactionId) return;
    busy = true;
    error = '';
    try {
      await abortTransaction(datasetId, branch, openTransactionId);
      onResolved?.();
    } catch (cause) {
      error = cause instanceof ApiError ? cause.message : 'Abort failed';
    } finally {
      busy = false;
    }
  }
</script>

<div
  class="rounded-2xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900 shadow-sm dark:border-amber-700 dark:bg-amber-950/40 dark:text-amber-100"
  data-testid="open-transaction-banner"
  role="status"
>
  <div class="flex flex-wrap items-center justify-between gap-3">
    <div class="flex items-start gap-2">
      <span aria-hidden="true">🔓</span>
      <div>
        <p class="font-semibold">An open transaction is in progress on this branch.</p>
        <p class="mt-0.5 text-xs opacity-80">
          New transactions cannot be started until the current one is
          committed or aborted.
        </p>
      </div>
    </div>
    <div class="flex flex-wrap gap-2">
      {#if openTransactionId}
        <a
          href={`/datasets/${encodeURIComponent(datasetId)}?tab=history&txn=${encodeURIComponent(openTransactionId)}`}
          class="rounded border border-amber-400 px-2 py-1 text-xs hover:bg-amber-100 dark:border-amber-600 dark:hover:bg-amber-900/40"
          data-testid="open-transaction-view"
        >View transaction</a>
        {#if canManage}
          <button
            type="button"
            class="rounded bg-emerald-600 px-2 py-1 text-xs font-medium text-white hover:bg-emerald-700 disabled:opacity-50"
            onclick={commit}
            disabled={busy}
            data-testid="open-transaction-commit"
          >Commit</button>
          <button
            type="button"
            class="rounded bg-rose-600 px-2 py-1 text-xs font-medium text-white hover:bg-rose-700 disabled:opacity-50"
            onclick={abort}
            disabled={busy}
            data-testid="open-transaction-abort"
          >Abort</button>
        {/if}
      {:else}
        <span class="text-xs italic opacity-70">No transaction id available — refresh to load.</span>
      {/if}
    </div>
  </div>

  {#if error}
    <p class="mt-2 text-xs text-rose-700 dark:text-rose-300" data-testid="open-transaction-error">{error}</p>
  {/if}
</div>

// apps/web/src/lib/components/dataset/OpenTransactionBanner.tsx
import { useState } from 'react';

import { abortTransaction, commitTransaction } from '@/lib/api/datasets';

interface OpenTransactionBannerProps {
  datasetId: string;
  branch: string;
  openTransactionId: string | null;
  canManage: boolean;
  onResolved?: () => void;
}

export function OpenTransactionBanner({
  datasetId,
  branch,
  openTransactionId,
  canManage,
  onResolved,
}: OpenTransactionBannerProps) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  async function commit() {
    if (!openTransactionId) return;
    setBusy(true);
    setError('');
    try {
      await commitTransaction(datasetId, branch, openTransactionId);
      onResolved?.();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Commit failed');
    } finally {
      setBusy(false);
    }
  }

  async function abort() {
    if (!openTransactionId) return;
    setBusy(true);
    setError('');
    try {
      await abortTransaction(datasetId, branch, openTransactionId);
      onResolved?.();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Abort failed');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div
      role="status"
      style={{
        borderRadius: 16,
        padding: '12px 16px',
        background: '#78350f',
        color: '#fde68a',
        boxShadow: 'inset 0 0 0 1px #b45309',
      }}
    >
      <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start' }}>
        <div style={{ display: 'flex', gap: 8 }}>
          <span aria-hidden="true">🔓</span>
          <div>
            <p style={{ margin: 0, fontWeight: 600 }}>An open transaction is in progress on this branch.</p>
            <p style={{ margin: '2px 0 0', fontSize: 11, opacity: 0.8 }}>
              New transactions cannot be started until the current one is committed or aborted.
            </p>
          </div>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
          {openTransactionId ? (
            <>
              <a
                href={`/datasets/${encodeURIComponent(datasetId)}?tab=transactions&txn=${encodeURIComponent(openTransactionId)}`}
                style={{ padding: '4px 8px', border: '1px solid #b45309', borderRadius: 4, fontSize: 11, color: 'inherit', textDecoration: 'none' }}
              >
                View transaction
              </a>
              {canManage && (
                <>
                  <button
                    type="button"
                    onClick={() => void commit()}
                    disabled={busy}
                    style={{ padding: '4px 8px', borderRadius: 4, fontSize: 11, fontWeight: 500, background: '#059669', color: '#fff', border: 'none', cursor: 'pointer' }}
                  >
                    Commit
                  </button>
                  <button
                    type="button"
                    onClick={() => void abort()}
                    disabled={busy}
                    style={{ padding: '4px 8px', borderRadius: 4, fontSize: 11, fontWeight: 500, background: '#dc2626', color: '#fff', border: 'none', cursor: 'pointer' }}
                  >
                    Abort
                  </button>
                </>
              )}
            </>
          ) : (
            <span style={{ fontSize: 11, fontStyle: 'italic', opacity: 0.7 }}>No transaction id available — refresh to load.</span>
          )}
        </div>
      </div>
      {error && <p style={{ marginTop: 8, fontSize: 11, color: '#fca5a5' }}>{error}</p>}
    </div>
  );
}
