// apps/web/src/lib/components/dataset/RetentionPoliciesTab.tsx
import { useEffect, useState } from 'react';

import {
  createRetentionPolicy,
  deleteRetentionPolicy,
  getApplicablePolicies,
  getRetentionPreview,
  type ApplicablePoliciesResponse,
  type RetentionPolicy,
  type RetentionPreviewResponse,
} from '@/lib/api/datasets';

interface RetentionPoliciesTabProps {
  datasetRid: string;
  projectId?: string;
  spaceId?: string;
  orgId?: string;
  canManage?: boolean;
}

function PolicyRow({ policy, onDelete }: { policy: RetentionPolicy; onDelete?: () => void }) {
  return (
    <li
      style={{
        padding: 8,
        background: 'var(--bg-subtle)',
        borderRadius: 6,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
        fontSize: 12,
      }}
    >
      <div>
        <strong>{policy.name}</strong>
        <span className="of-text-muted" style={{ marginLeft: 8, fontSize: 11 }}>
          · {policy.target_kind} · {policy.retention_days}d · {policy.purge_mode}{policy.legal_hold ? ' · legal hold' : ''}
        </span>
      </div>
      {onDelete && (
        <button type="button" onClick={onDelete} className="of-button" style={{ fontSize: 10, color: '#b91c1c', borderColor: '#fecaca' }}>
          Delete
        </button>
      )}
    </li>
  );
}

export function RetentionPoliciesTab({ datasetRid, projectId, spaceId, orgId, canManage = false }: RetentionPoliciesTabProps) {
  const [applicable, setApplicable] = useState<ApplicablePoliciesResponse | null>(null);
  const [preview, setPreview] = useState<RetentionPreviewResponse | null>(null);
  const [asOfDays, setAsOfDays] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [creating, setCreating] = useState(false);
  const [policyName, setPolicyName] = useState('');
  const [retentionDays, setRetentionDays] = useState(90);

  async function loadApplicable() {
    setError(null);
    try {
      setApplicable(await getApplicablePolicies(datasetRid, { project_id: projectId, space_id: spaceId, org_id: orgId }));
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Applicable-policies failed.');
    }
  }
  async function loadPreview() {
    try {
      setPreview(await getRetentionPreview(datasetRid, asOfDays, { project_id: projectId, space_id: spaceId, org_id: orgId }));
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Preview failed.');
    }
  }

  useEffect(() => { void loadApplicable(); }, [datasetRid, projectId, spaceId, orgId]);
  useEffect(() => { void loadPreview(); }, [datasetRid, asOfDays]);

  async function createPolicy() {
    if (!policyName.trim()) return;
    setBusy(true);
    setError(null);
    try {
      await createRetentionPolicy({
        name: policyName.trim(),
        scope: `dataset:${datasetRid}`,
        target_kind: 'transaction',
        retention_days: retentionDays,
        legal_hold: false,
        purge_mode: 'soft',
        rules: [],
        selector: { dataset_rid: datasetRid } as Parameters<typeof createRetentionPolicy>[0]['selector'],
        criteria: { tx_types: [] } as Parameters<typeof createRetentionPolicy>[0]['criteria'],
        grace_period_minutes: 60,
        updated_by: 'ui',
      });
      setPolicyName('');
      setCreating(false);
      await loadApplicable();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Create policy failed.');
    } finally {
      setBusy(false);
    }
  }

  async function deletePolicy(id: string) {
    if (typeof window !== 'undefined' && !window.confirm('Delete policy?')) return;
    setBusy(true);
    try {
      await deleteRetentionPolicy(id);
      await loadApplicable();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Delete failed.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <section style={{ display: 'grid', gap: 16 }}>
      <div style={{ padding: '8px 12px', background: '#1e3a8a', color: '#bfdbfe', borderRadius: 6, fontSize: 11 }}>
        <strong>Beta:</strong> retention policies. Inherited bottom-up: org → space → project → explicit.
      </div>

      {error && <div className="of-status-danger" style={{ padding: '8px 12px', borderRadius: 8, fontSize: 12 }}>{error}</div>}

      {applicable && (
        <>
          {(['org', 'space', 'project'] as const).map((scope) => {
            const list = applicable.inherited[scope];
            return (
              <section key={scope} className="of-panel" style={{ padding: 12 }}>
                <p className="of-eyebrow" style={{ fontSize: 10 }}>{scope.toUpperCase()} ({list.length})</p>
                <ul style={{ marginTop: 8, paddingLeft: 0, listStyle: 'none', display: 'grid', gap: 4 }}>
                  {list.map((p) => <PolicyRow key={p.id} policy={p} />)}
                  {list.length === 0 && <li className="of-text-muted" style={{ fontSize: 11 }}>None.</li>}
                </ul>
              </section>
            );
          })}

          <section className="of-panel" style={{ padding: 12 }}>
            <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
              <p className="of-eyebrow" style={{ fontSize: 10 }}>Explicit on this dataset ({applicable.explicit.length})</p>
              {canManage && !creating && (
                <button type="button" onClick={() => setCreating(true)} className="of-button" style={{ fontSize: 11 }}>+ New policy</button>
              )}
            </header>
            <ul style={{ marginTop: 8, paddingLeft: 0, listStyle: 'none', display: 'grid', gap: 4 }}>
              {applicable.explicit.map((p) => (
                <PolicyRow key={p.id} policy={p} onDelete={canManage ? () => void deletePolicy(p.id) : undefined} />
              ))}
              {applicable.explicit.length === 0 && <li className="of-text-muted" style={{ fontSize: 11 }}>No explicit policies on this dataset.</li>}
            </ul>
            {creating && (
              <div style={{ marginTop: 12, display: 'grid', gap: 6 }}>
                <input value={policyName} onChange={(e) => setPolicyName(e.target.value)} placeholder="Policy name" className="of-input" />
                <label style={{ fontSize: 12 }}>
                  Retention days
                  <input type="number" min={1} value={retentionDays} onChange={(e) => setRetentionDays(Number(e.target.value) || 0)} className="of-input" style={{ marginTop: 4, width: 120 }} />
                </label>
                <div style={{ display: 'flex', gap: 6 }}>
                  <button type="button" onClick={() => void createPolicy()} disabled={busy} className="of-button of-button--primary" style={{ fontSize: 11 }}>Create</button>
                  <button type="button" onClick={() => setCreating(false)} className="of-button" style={{ fontSize: 11 }}>Cancel</button>
                </div>
              </div>
            )}
          </section>

          <section className="of-panel" style={{ padding: 12 }}>
            <p className="of-eyebrow" style={{ fontSize: 10 }}>Effective policy</p>
            {applicable.effective ? <PolicyRow policy={applicable.effective} /> : <p className="of-text-muted" style={{ fontSize: 11 }}>No policy applies — data retained indefinitely.</p>}
            {applicable.conflicts.length > 0 && (
              <ul style={{ marginTop: 8, paddingLeft: 18, fontSize: 11 }}>
                {applicable.conflicts.map((c, i) => (
                  <li key={i} style={{ color: '#fbbf24' }}>
                    Conflict: {c.winner_id} won over {c.loser_id} — {c.reason}
                  </li>
                ))}
              </ul>
            )}
          </section>
        </>
      )}

      <section className="of-panel" style={{ padding: 12, display: 'grid', gap: 8 }}>
        <p className="of-eyebrow" style={{ fontSize: 10 }}>Preview deletions</p>
        <label style={{ fontSize: 12 }}>
          As of (days from now): {asOfDays}
          <input
            type="range"
            min={0}
            max={365}
            value={asOfDays}
            onChange={(e) => setAsOfDays(Number(e.target.value))}
            style={{ width: '100%', marginTop: 4 }}
          />
        </label>
        {preview && (
          <ul className="of-text-muted" style={{ paddingLeft: 18, fontSize: 12, marginTop: 0 }}>
            <li>{preview.summary.transactions_would_delete} of {preview.summary.transactions_total} transactions would be purged</li>
            <li>{preview.summary.files_total} files · {preview.summary.bytes_total.toLocaleString()} bytes</li>
            {preview.warnings.length > 0 && preview.warnings.map((w, i) => <li key={i} style={{ color: '#fbbf24' }}>{w}</li>)}
          </ul>
        )}
      </section>
    </section>
  );
}

// apps/web/src/lib/components/dataset/RetentionPoliciesTab.svelte
<!--
  P4 — RetentionPoliciesTab.

  Foundry's "View retention policies for a dataset [Beta]" surface
  (Datasets.md § "Retention"). Five sections, top to bottom:

    1. Beta banner.
    2. Inherited policies (Org → Space → Project), grouped tables.
    3. Explicit policies on this dataset (manage role: inline CRUD).
    4. Effective policy (winner-take, with the "why" line).
    5. Preview deletions (slider, hits the retention-preview endpoint).

  Self-fetches via the new `getApplicablePolicies` /
  `getRetentionPreview` helpers in `$lib/api/datasets`.
-->
<script lang="ts" module>
  import type { RetentionPolicy } from '$lib/api/datasets';
  export type Mode = 'view' | 'manage';
  export type { RetentionPolicy };
</script>

<script lang="ts">
  import {
    createRetentionPolicy,
    deleteRetentionPolicy,
    getApplicablePolicies,
    getRetentionPreview,
    type ApplicablePoliciesResponse,
    type RetentionPreviewResponse,
  } from '$lib/api/datasets';

  type Props = {
    datasetRid: string;
    /** Pass dataset metadata so the resolver can match
     *  inherited policies. The page already has these. */
    projectId?: string;
    spaceId?: string;
    orgId?: string;
    /** True when the current user has manage permission. Drives
     *  CRUD visibility on the Explicit section. */
    canManage?: boolean;
  };

  const {
    datasetRid,
    projectId,
    spaceId,
    orgId,
    canManage = false,
  }: Props = $props();

  let applicable = $state<ApplicablePoliciesResponse | null>(null);
  let preview = $state<RetentionPreviewResponse | null>(null);
  let asOfDays = $state(0);
  let loadingApplicable = $state(false);
  let loadingPreview = $state(false);
  let error = $state<string | null>(null);
  let saving = $state(false);

  let lastApplicableKey = $state('');
  let lastPreviewKey = $state('');

  $effect(() => {
    const key = JSON.stringify({ datasetRid, projectId, spaceId, orgId });
    if (!datasetRid || key === lastApplicableKey) return;
    lastApplicableKey = key;
    void loadApplicable();
  });

  $effect(() => {
    const key = JSON.stringify({ datasetRid, asOfDays });
    if (!datasetRid || key === lastPreviewKey) return;
    lastPreviewKey = key;
    void loadPreview();
  });

  async function loadApplicable() {
    loadingApplicable = true;
    error = null;
    try {
      applicable = await getApplicablePolicies(datasetRid, {
        project_id: projectId,
        space_id: spaceId,
        org_id: orgId,
      });
    } catch (cause) {
      error = cause instanceof Error ? cause.message : 'Applicable-policies failed.';
    } finally {
      loadingApplicable = false;
    }
  }

  async function loadPreview() {
    loadingPreview = true;
    try {
      preview = await getRetentionPreview(datasetRid, asOfDays, {
        project_id: projectId,
        space_id: spaceId,
        org_id: orgId,
      });
    } catch (cause) {
      // Preview failures are non-fatal — the rest of the tab still works.
      preview = null;
      console.warn('retention-preview failed', cause);
    } finally {
      loadingPreview = false;
    }
  }

  // Inline create form (manage role only).
  let newName = $state('');
  let newDays = $state<number>(30);

  async function createExplicitPolicy() {
    if (!newName.trim()) return;
    saving = true;
    try {
      await createRetentionPolicy({
        name: newName.trim(),
        target_kind: 'transaction',
        retention_days: newDays,
        purge_mode: 'hard-delete-after-ttl',
        selector: { dataset_rid: datasetRid },
        updated_by: 'web-ui',
      });
      newName = '';
      newDays = 30;
      lastApplicableKey = '';
      await loadApplicable();
    } catch (cause) {
      error = cause instanceof Error ? cause.message : 'Could not create policy.';
    } finally {
      saving = false;
    }
  }

  async function removeExplicit(id: string) {
    if (!confirm('Delete this retention policy?')) return;
    try {
      await deleteRetentionPolicy(id);
      lastApplicableKey = '';
      await loadApplicable();
    } catch (cause) {
      error = cause instanceof Error ? cause.message : 'Could not delete policy.';
    }
  }

  function fmtBytes(value: number): string {
    if (value < 1024) return `${value} B`;
    if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
    if (value < 1024 * 1024 * 1024) return `${(value / (1024 * 1024)).toFixed(1)} MB`;
    return `${(value / (1024 * 1024 * 1024)).toFixed(2)} GB`;
  }

  function describePolicy(policy: RetentionPolicy): string {
    const parts: string[] = [];
    parts.push(`${policy.target_kind}, ${policy.retention_days}d`);
    if (policy.legal_hold) parts.push('legal hold');
    if (policy.criteria.transaction_state)
      parts.push(`state=${policy.criteria.transaction_state}`);
    parts.push(`grace ${policy.grace_period_minutes}m`);
    return parts.join(' · ');
  }

  function inheritedTotal(a: ApplicablePoliciesResponse | null): number {
    if (!a) return 0;
    return a.inherited.org.length + a.inherited.space.length + a.inherited.project.length;
  }

  function effectiveExplanation(a: ApplicablePoliciesResponse | null): string {
    if (!a || !a.effective) return '';
    if (a.conflicts.length === 0) {
      return `Sole applicable policy.`;
    }
    const reasons = new Set(a.conflicts.map((c) => c.reason));
    if (reasons.has('winner_has_legal_hold')) {
      return `Wins because legal_hold = true overrides every other policy.`;
    }
    if (reasons.has('winner_has_lower_retention_days')) {
      return `Wins as the most restrictive policy: lowest retention_days (${a.effective.retention_days}d).`;
    }
    return `Wins by specificity (explicit > project > space > org).`;
  }
</script>

<section class="space-y-4" data-component="retention-policies-tab">
  <!-- 1) Beta banner -->
  <div class="flex flex-wrap items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:border-amber-900/50 dark:bg-amber-950/40 dark:text-amber-100" data-testid="retention-beta-banner">
    <span class="rounded-full bg-amber-200 px-2 py-0.5 text-xs font-semibold uppercase tracking-wide text-amber-900 dark:bg-amber-900 dark:text-amber-100">Beta</span>
    <span title="Per Foundry docs, this view is in Beta phase">
      Per Foundry docs, this view is in Beta phase.
    </span>
  </div>

  {#if error}
    <div class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-2 text-sm text-rose-800 dark:border-rose-900/50 dark:bg-rose-950/40 dark:text-rose-100" role="alert" data-testid="retention-error">
      {error}
    </div>
  {/if}

  <!-- 4) Effective policy summary up top: it's what users want first. -->
  <section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950" data-testid="retention-effective">
    <div class="text-xs uppercase tracking-[0.18em] text-slate-400">Effective policy</div>
    {#if loadingApplicable}
      <div class="mt-2 text-sm text-slate-500">Resolving applicable policies…</div>
    {:else if applicable?.effective}
      <div class="mt-2 flex flex-col gap-1">
        <div class="flex flex-wrap items-center gap-2">
          <span class="text-base font-semibold" data-testid="effective-policy-name">{applicable.effective.name}</span>
          {#if applicable.effective.is_system}
            <span class="rounded-full bg-indigo-100 px-2 py-0.5 text-xs font-medium text-indigo-800 dark:bg-indigo-900/40 dark:text-indigo-200">System</span>
          {/if}
          {#if applicable.effective.legal_hold}
            <span class="rounded-full bg-rose-100 px-2 py-0.5 text-xs font-medium text-rose-800 dark:bg-rose-900/40 dark:text-rose-200">Legal hold</span>
          {/if}
        </div>
        <div class="text-xs text-slate-500">{describePolicy(applicable.effective)}</div>
        <div class="text-xs italic text-slate-500">{effectiveExplanation(applicable)}</div>
      </div>
    {:else}
      <div class="mt-2 text-sm text-slate-500" data-testid="retention-empty">
        No retention policies apply to this dataset yet.
      </div>
    {/if}
  </section>

  <!-- 2) Inherited policies, one section per level. -->
  <section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950" data-testid="retention-inherited">
    <div class="flex items-center justify-between">
      <div>
        <div class="text-xs uppercase tracking-[0.18em] text-slate-400">Inherited policies</div>
        <p class="mt-1 text-sm text-slate-500">
          Policies that apply via the org / space / project hierarchy.
          {inheritedTotal(applicable)} inherited policy{inheritedTotal(applicable) === 1 ? '' : 's'}.
        </p>
      </div>
    </div>

    {#if applicable && inheritedTotal(applicable) > 0}
      <div class="mt-3 space-y-3">
        {@render InheritedGroup('Org', applicable.inherited.org, 'org')}
        {@render InheritedGroup('Space', applicable.inherited.space, 'space')}
        {@render InheritedGroup('Project', applicable.inherited.project, 'project')}
      </div>
    {:else if !loadingApplicable}
      <div class="mt-3 text-sm text-slate-500">No inherited policies.</div>
    {/if}
  </section>

  <!-- 3) Explicit policies on this dataset. -->
  <section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950" data-testid="retention-explicit">
    <div class="flex items-center justify-between">
      <div>
        <div class="text-xs uppercase tracking-[0.18em] text-slate-400">Explicit policies on this dataset</div>
        <p class="mt-1 text-sm text-slate-500">
          {applicable?.explicit.length ?? 0} explicit polic{(applicable?.explicit.length ?? 0) === 1 ? 'y' : 'ies'}.
        </p>
      </div>
    </div>

    {#if applicable?.explicit && applicable.explicit.length > 0}
      <ul class="mt-3 divide-y divide-slate-100 dark:divide-gray-800">
        {#each applicable.explicit as policy (policy.id)}
          <li class="flex flex-col gap-1 py-2 text-sm md:flex-row md:items-center md:justify-between" data-testid="explicit-row">
            <div class="flex flex-col">
              <span class="font-medium">{policy.name}</span>
              <span class="text-xs text-slate-500">{describePolicy(policy)}</span>
            </div>
            {#if canManage}
              <button
                type="button"
                class="self-start rounded-md border border-rose-300 px-2 py-1 text-xs text-rose-700 hover:bg-rose-50 dark:border-rose-900/50 dark:text-rose-200 dark:hover:bg-rose-950/40"
                onclick={() => void removeExplicit(policy.id)}
              >
                Remove
              </button>
            {/if}
          </li>
        {/each}
      </ul>
    {:else}
      <div class="mt-3 text-sm text-slate-500">No explicit policies on this dataset.</div>
    {/if}

    {#if canManage}
      <form
        class="mt-4 flex flex-wrap items-end gap-2 rounded-md bg-slate-50 p-3 text-sm dark:bg-gray-900"
        onsubmit={(event) => {
          event.preventDefault();
          void createExplicitPolicy();
        }}
        data-testid="explicit-create-form"
      >
        <label class="flex flex-col">
          <span class="text-xs uppercase tracking-wide text-slate-400">Name</span>
          <input
            class="mt-1 rounded-md border border-slate-300 bg-white px-2 py-1 dark:border-gray-700 dark:bg-gray-900"
            placeholder="e.g. operational-30d"
            bind:value={newName}
          />
        </label>
        <label class="flex flex-col">
          <span class="text-xs uppercase tracking-wide text-slate-400">Retention days</span>
          <input
            type="number"
            min="0"
            class="mt-1 w-28 rounded-md border border-slate-300 bg-white px-2 py-1 dark:border-gray-700 dark:bg-gray-900"
            bind:value={newDays}
          />
        </label>
        <button
          type="submit"
          class="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
          disabled={saving || !newName.trim()}
        >
          {saving ? 'Saving…' : 'Add policy'}
        </button>
      </form>
    {/if}
  </section>

  <!-- 5) Preview deletions. -->
  <section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950" data-testid="retention-preview">
    <div class="flex flex-wrap items-end justify-between gap-3">
      <div>
        <div class="text-xs uppercase tracking-[0.18em] text-slate-400">Preview deletions</div>
        <p class="mt-1 text-sm text-slate-500">
          Simulate which transactions and files would be purged
          {#if asOfDays === 0}today{:else}{asOfDays} day{asOfDays === 1 ? '' : 's'} from now{/if}.
        </p>
      </div>
      <label class="flex w-full max-w-sm items-center gap-2 text-sm">
        <span class="text-xs uppercase tracking-wide text-slate-400">As of</span>
        <input
          type="range"
          min="0"
          max="365"
          step="1"
          bind:value={asOfDays}
          class="flex-1"
          data-testid="retention-preview-slider"
        />
        <span class="w-16 text-right font-mono text-xs">{asOfDays}d</span>
      </label>
    </div>

    {#if loadingPreview}
      <div class="mt-3 text-sm text-slate-500">Computing preview…</div>
    {:else if preview}
      <div class="mt-3 grid grid-cols-1 gap-3 md:grid-cols-3">
        <div class="rounded-md bg-slate-50 px-3 py-2 dark:bg-gray-900">
          <div class="text-xs uppercase tracking-wide text-slate-400">Transactions</div>
          <div class="mt-1 text-lg font-semibold" data-testid="preview-tx-count">
            {preview.summary.transactions_would_delete} / {preview.summary.transactions_total}
          </div>
        </div>
        <div class="rounded-md bg-slate-50 px-3 py-2 dark:bg-gray-900">
          <div class="text-xs uppercase tracking-wide text-slate-400">Files</div>
          <div class="mt-1 text-lg font-semibold">{preview.summary.files_total}</div>
        </div>
        <div class="rounded-md bg-slate-50 px-3 py-2 dark:bg-gray-900">
          <div class="text-xs uppercase tracking-wide text-slate-400">Total size</div>
          <div class="mt-1 text-lg font-semibold">{fmtBytes(preview.summary.bytes_total)}</div>
        </div>
      </div>

      {#if preview.warnings.length > 0}
        <div class="mt-3 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:border-amber-900/50 dark:bg-amber-950/40 dark:text-amber-100">
          {preview.warnings.join('; ')}
        </div>
      {/if}

      {#if preview.transactions.some((t) => t.would_delete)}
        <div class="mt-3 max-h-72 overflow-y-auto rounded-md border border-slate-200 dark:border-gray-800">
          <table class="min-w-full text-xs">
            <thead class="text-left uppercase tracking-wide text-slate-500">
              <tr>
                <th class="px-2 py-1">Transaction</th>
                <th class="px-2 py-1">Status</th>
                <th class="px-2 py-1">Policy</th>
                <th class="px-2 py-1">Reason</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-100 font-mono dark:divide-gray-800">
              {#each preview.transactions.filter((t) => t.would_delete) as txn (txn.id)}
                <tr data-testid="preview-row">
                  <td class="px-2 py-1" title={txn.id}>{txn.id.slice(0, 8)}</td>
                  <td class="px-2 py-1">{txn.status}</td>
                  <td class="px-2 py-1">{txn.policy_name ?? '—'}</td>
                  <td class="px-2 py-1 text-slate-500">{txn.reason ?? '—'}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    {/if}
  </section>
</section>

{#snippet InheritedGroup(label: string, items: RetentionPolicy[], slug: string)}
  {#if items.length > 0}
    <div data-testid={`inherited-${slug}`}>
      <div class="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div>
      <ul class="mt-1 divide-y divide-slate-100 dark:divide-gray-800">
        {#each items as policy (policy.id)}
          <li class="flex flex-col gap-1 py-1 text-sm md:flex-row md:items-center md:justify-between">
            <span class="flex items-center gap-2">
              <span>{policy.name}</span>
              <span class="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] uppercase tracking-wide text-slate-700 dark:bg-gray-800 dark:text-gray-200" title={`Inherited from ${label}`}>
                inherited from {label.toLowerCase()}
              </span>
            </span>
            <span class="text-xs text-slate-500">{describePolicy(policy)}</span>
          </li>
        {/each}
      </ul>
    </div>
  {/if}
{/snippet}
