// apps/web/src/lib/components/ontology/ActionsButtonGroup.svelte
<!--
  TASK N — ActionsButtonGroup

  Configurable button-group widget that surfaces ontology actions in
  Object Explorer / Object Views / Workshop apps. Each button declares the
  action it triggers, optional default values to seed inputs, parameters to
  hide from the user, and whether the action is invoked immediately
  (skipping the modal form) when no required inputs remain.

  See `Use actions in the platform.md`.

  Usage:
    <ActionsButtonGroup
      typeId={objectType.id}
      objectId={selection.objectId}
      buttons={[
        { action_id: '…', label: 'Approve', color: 'emerald', immediate: true },
        { action_id: '…', label: 'Edit', color: 'sky', hidden_params: ['actor_id'] }
      ]}
      onExecuted={refresh}
    />
-->
<script lang="ts">
  import { executeAction, getActionType, type ActionType } from '$lib/api/ontology';
  import ActionExecutor from './ActionExecutor.svelte';

  export type ActionButtonConfig = {
    action_id: string;
    label?: string;
    /** Tailwind colour keyword: emerald | sky | rose | amber | slate */
    color?: 'emerald' | 'sky' | 'rose' | 'amber' | 'slate';
    /** Pre-filled parameter values when opening the executor. */
    default_values?: Record<string, unknown>;
    /** Names of parameters that should not be shown to the user. */
    hidden_params?: string[];
    /** Skip the modal entirely when the action has no remaining required input. */
    immediate?: boolean;
  };

  let {
    typeId,
    objectId,
    buttons,
    onExecuted
  }: {
    typeId: string;
    objectId?: string;
    buttons: ActionButtonConfig[];
    onExecuted?: () => void;
  } = $props();

  let openButton = $state<ActionButtonConfig | null>(null);
  let openAction = $state<ActionType | null>(null);
  let busy = $state('');
  let error = $state('');

  const colorClasses: Record<NonNullable<ActionButtonConfig['color']>, string> = {
    emerald: 'bg-emerald-600 hover:bg-emerald-500 text-white',
    sky: 'bg-sky-600 hover:bg-sky-500 text-white',
    rose: 'bg-rose-600 hover:bg-rose-500 text-white',
    amber: 'bg-amber-500 hover:bg-amber-400 text-slate-900',
    slate: 'bg-slate-200 hover:bg-slate-300 text-slate-900 dark:bg-slate-700 dark:text-slate-100'
  };

  function classFor(button: ActionButtonConfig): string {
    return colorClasses[button.color ?? 'sky'];
  }

  async function activate(button: ActionButtonConfig) {
    error = '';
    busy = button.action_id;
    try {
      const action = await getActionType(button.action_id);
      const visibleRequired = action.input_schema.filter(
        (field) =>
          field.required &&
          !(button.hidden_params ?? []).includes(field.name) &&
          (button.default_values?.[field.name] ?? field.default_value) === undefined
      );

      if (button.immediate && visibleRequired.length === 0) {
        await executeAction(button.action_id, {
          target_object_id: objectId,
          parameters: button.default_values ?? {}
        });
        onExecuted?.();
        return;
      }
      openAction = action;
      openButton = button;
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      busy = '';
    }
  }

  function close() {
    openAction = null;
    openButton = null;
  }

  function executed() {
    close();
    onExecuted?.();
  }
</script>

<div class="flex flex-wrap items-center gap-2">
  {#each buttons as button (button.action_id + (button.label ?? ''))}
    <button
      type="button"
      onclick={() => activate(button)}
      disabled={busy === button.action_id}
      class={`inline-flex items-center gap-2 rounded-xl px-3 py-1.5 text-sm font-semibold shadow-sm transition disabled:opacity-50 ${classFor(button)}`}
    >
      {button.label ?? 'Run action'}
    </button>
  {/each}
</div>

{#if error}
  <p class="mt-2 text-xs text-rose-600 dark:text-rose-300">{error}</p>
{/if}

{#if openAction && openButton}
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4">
    <div class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl dark:bg-slate-900">
      <div class="mb-4 flex items-center justify-between">
        <h2 class="text-lg font-semibold text-slate-900 dark:text-slate-100">
          {openButton.label ?? openAction.display_name ?? openAction.name}
        </h2>
        <button
          type="button"
          onclick={close}
          class="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-700 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-200"
        >
          Close
        </button>
      </div>
      <ActionExecutor
        action={openAction}
        parameters={{ ...(openButton.default_values ?? {}) }}
        on:executed={executed}
      />
      {#if (openButton.hidden_params ?? []).length > 0}
        <p class="mt-3 text-[11px] text-slate-500 dark:text-slate-400">
          Hidden parameters: {(openButton.hidden_params ?? []).join(', ')} are pre-filled by this
          button and not displayed in the form.
        </p>
      {/if}
    </div>
  </div>
{/if}

// apps/web/src/lib/components/ontology/ActionsButtonGroup.tsx
import { useState } from 'react';

import { executeAction, getActionType, type ActionType } from '@/lib/api/ontology';
import { ActionExecutor } from './ActionExecutor';

export interface ActionButtonConfig {
  action_id: string;
  label?: string;
  color?: 'emerald' | 'sky' | 'rose' | 'amber' | 'slate';
  default_values?: Record<string, unknown>;
  hidden_params?: string[];
  immediate?: boolean;
}

interface ActionsButtonGroupProps {
  typeId: string;
  objectId?: string;
  buttons: ActionButtonConfig[];
  onExecuted?: () => void;
}

const COLOR: Record<NonNullable<ActionButtonConfig['color']>, { background: string; color: string }> = {
  emerald: { background: '#059669', color: '#fff' },
  sky: { background: '#0284c7', color: '#fff' },
  rose: { background: '#e11d48', color: '#fff' },
  amber: { background: '#f59e0b', color: '#0f172a' },
  slate: { background: '#1e293b', color: '#cbd5e1' },
};

export function ActionsButtonGroup({ typeId, objectId, buttons, onExecuted }: ActionsButtonGroupProps) {
  const [openButton, setOpenButton] = useState<ActionButtonConfig | null>(null);
  const [openAction, setOpenAction] = useState<ActionType | null>(null);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');

  async function activate(button: ActionButtonConfig) {
    setError('');
    setBusy(button.action_id);
    try {
      const action = await getActionType(button.action_id);
      const visibleRequired = action.input_schema.filter(
        (field) =>
          field.required &&
          !(button.hidden_params ?? []).includes(field.name) &&
          (button.default_values?.[field.name] ?? field.default_value) === undefined,
      );
      if (button.immediate && visibleRequired.length === 0) {
        await executeAction(button.action_id, {
          target_object_id: objectId,
          parameters: button.default_values ?? {},
        });
        onExecuted?.();
        return;
      }
      setOpenAction(action);
      setOpenButton(button);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setBusy('');
    }
  }

  function close() {
    setOpenAction(null);
    setOpenButton(null);
  }

  function executed() {
    close();
    onExecuted?.();
  }

  return (
    <>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, alignItems: 'center' }}>
        {buttons.map((b) => {
          const tone = COLOR[b.color ?? 'sky'];
          return (
            <button
              key={b.action_id + (b.label ?? '')}
              type="button"
              onClick={() => void activate(b)}
              disabled={busy === b.action_id}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                padding: '6px 12px',
                borderRadius: 12,
                border: 'none',
                fontWeight: 600,
                fontSize: 13,
                cursor: busy === b.action_id ? 'not-allowed' : 'pointer',
                ...tone,
              }}
            >
              {b.label ?? 'Run action'}
            </button>
          );
        })}
      </div>
      {error && <p style={{ marginTop: 8, fontSize: 11, color: '#fca5a5' }}>{error}</p>}
      {openAction && openButton && typeId && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(15,23,42,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16, zIndex: 100 }}>
          <div style={{ maxHeight: '90vh', width: '100%', maxWidth: 720, overflow: 'auto', background: '#0f172a', color: '#e2e8f0', borderRadius: 16, padding: 24, border: '1px solid #1e293b' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
              <h2 style={{ margin: 0, fontSize: 16, fontWeight: 600 }}>{openButton.label ?? openAction.display_name ?? openAction.name}</h2>
              <button type="button" onClick={close} className="of-button" style={{ fontSize: 12 }}>Close</button>
            </div>
            <ActionExecutor action={openAction} initialParameters={{ ...(openButton.default_values ?? {}) }} hiddenParams={openButton.hidden_params ?? []} targetObjectId={objectId ?? null} onExecuted={executed} />
            {(openButton.hidden_params ?? []).length > 0 && (
              <p style={{ marginTop: 12, fontSize: 11, color: '#94a3b8' }}>
                Hidden parameters: {(openButton.hidden_params ?? []).join(', ')} are pre-filled by this button and not displayed in the form.
              </p>
            )}
          </div>
        </div>
      )}
    </>
  );
}
