// apps/web/src/lib/components/ontology/LinkEditor.svelte
<script lang="ts">
  /**
   * `LinkEditor` — Form CRUD para un `LinkType` con cardinalidades y
   * selectores `source` / `target` (poblados desde `listObjectTypes`).
   *
   * Contrato Svelte 5:
   * - `linkId?: string | null` — edita si está presente; crea si no.
   * - `defaultSourceTypeId?: string`
   * - `defaultTargetTypeId?: string`
   * - `oncreated?: (link: LinkType) => void`
   * - `onupdated?: (link: LinkType) => void`
   * - `ondeleted?: (id: string) => void`
   */
  import {
    createLinkType,
    deleteLinkType,
    listLinkTypes,
    listObjectTypes,
    updateLinkType,
    type LinkType,
    type ObjectType,
  } from '$lib/api/ontology';

  type Cardinality = 'one_to_one' | 'one_to_many' | 'many_to_one' | 'many_to_many';

  type Props = {
    linkId?: string | null;
    defaultSourceTypeId?: string;
    defaultTargetTypeId?: string;
    oncreated?: (link: LinkType) => void;
    onupdated?: (link: LinkType) => void;
    ondeleted?: (id: string) => void;
  };

  const {
    linkId = null,
    defaultSourceTypeId = '',
    defaultTargetTypeId = '',
    oncreated,
    onupdated,
    ondeleted,
  }: Props = $props();

  let saving = $state(false);
  let loading = $state(false);
  let error = $state('');

  let objectTypes = $state<ObjectType[]>([]);
  let editing = $state<LinkType | null>(null);
  let draft = $state({
    name: '',
    display_name: '',
    description: '',
    source_type_id: '',
    target_type_id: '',
    cardinality: 'many_to_many' as Cardinality,
  });

  const isEdit = $derived(Boolean(linkId));

  $effect(() => {
    void loadTypes();
  });

  $effect(() => {
    if (!linkId) {
      editing = null;
      draft = {
        name: '',
        display_name: '',
        description: '',
        source_type_id: defaultSourceTypeId,
        target_type_id: defaultTargetTypeId,
        cardinality: 'many_to_many',
      };
      return;
    }
    void loadLink(linkId);
  });

  async function loadTypes() {
    try {
      const response = await listObjectTypes({ per_page: 200 });
      objectTypes = response.data ?? [];
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    }
  }

  async function loadLink(id: string) {
    loading = true;
    error = '';
    try {
      // No `getLinkType` endpoint exposed individually; reuse list.
      const response = await listLinkTypes({ per_page: 500 });
      const found = response.data?.find((link) => link.id === id) ?? null;
      if (!found) throw new Error('link type not found');
      editing = found;
      draft = {
        name: found.name,
        display_name: found.display_name,
        description: found.description,
        source_type_id: found.source_type_id,
        target_type_id: found.target_type_id,
        cardinality: (found.cardinality as Cardinality) ?? 'many_to_many',
      };
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  }

  async function save() {
    saving = true;
    error = '';
    try {
      if (isEdit && linkId) {
        const updated = await updateLinkType(linkId, {
          display_name: draft.display_name,
          description: draft.description,
          cardinality: draft.cardinality,
        });
        editing = updated;
        onupdated?.(updated);
      } else {
        if (!draft.name.trim()) throw new Error('name is required');
        if (!draft.source_type_id) throw new Error('source type is required');
        if (!draft.target_type_id) throw new Error('target type is required');
        const created = await createLinkType({
          name: draft.name,
          display_name: draft.display_name || undefined,
          description: draft.description || undefined,
          source_type_id: draft.source_type_id,
          target_type_id: draft.target_type_id,
          cardinality: draft.cardinality,
        });
        editing = created;
        oncreated?.(created);
      }
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      saving = false;
    }
  }

  async function remove() {
    if (!linkId) return;
    if (!confirm('Delete this link type?')) return;
    saving = true;
    try {
      await deleteLinkType(linkId);
      ondeleted?.(linkId);
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      saving = false;
    }
  }
</script>

<section class="link-editor" aria-busy={loading || saving}>
  <header>
    <h2>{isEdit ? `Edit link type: ${editing?.display_name ?? ''}` : 'Create link type'}</h2>
    {#if error}<p class="error" role="alert">{error}</p>{/if}
  </header>

  <form
    class="grid"
    onsubmit={(event) => {
      event.preventDefault();
      void save();
    }}
  >
    <label>
      <span>Name (slug)</span>
      <input bind:value={draft.name} required disabled={isEdit} />
    </label>
    <label>
      <span>Display name</span>
      <input bind:value={draft.display_name} />
    </label>
    <label class="full">
      <span>Description</span>
      <textarea bind:value={draft.description} rows="2"></textarea>
    </label>
    <label>
      <span>Source object type</span>
      <select bind:value={draft.source_type_id} required disabled={isEdit}>
        <option value="">— select —</option>
        {#each objectTypes as ot (ot.id)}
          <option value={ot.id}>{ot.display_name || ot.name}</option>
        {/each}
      </select>
    </label>
    <label>
      <span>Target object type</span>
      <select bind:value={draft.target_type_id} required disabled={isEdit}>
        <option value="">— select —</option>
        {#each objectTypes as ot (ot.id)}
          <option value={ot.id}>{ot.display_name || ot.name}</option>
        {/each}
      </select>
    </label>
    <label class="full">
      <span>Cardinality</span>
      <select bind:value={draft.cardinality}>
        <option value="one_to_one">one_to_one</option>
        <option value="one_to_many">one_to_many</option>
        <option value="many_to_one">many_to_one</option>
        <option value="many_to_many">many_to_many</option>
      </select>
    </label>

    <div class="actions">
      <button type="submit" disabled={saving}>{isEdit ? 'Save changes' : 'Create link'}</button>
      {#if isEdit}
        <button type="button" class="danger" disabled={saving} onclick={() => void remove()}>
          Delete
        </button>
      {/if}
    </div>
  </form>
</section>

<style>
  .link-editor { display: flex; flex-direction: column; gap: 1rem; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem 1rem; }
  .grid .full { grid-column: 1 / -1; }
  label { display: flex; flex-direction: column; gap: 0.25rem; font-size: 0.85rem; }
  .actions { grid-column: 1 / -1; display: flex; gap: 0.5rem; }
  .danger { background: #b91c1c; color: white; }
  .error { color: #b91c1c; }
</style>

// apps/web/src/lib/components/ontology/LinkEditor.tsx
import { useEffect, useState } from 'react';

import {
  createLinkType,
  deleteLinkType,
  listLinkTypes,
  listObjectTypes,
  updateLinkType,
  type LinkType,
  type ObjectType,
} from '@/lib/api/ontology';

type Cardinality = 'one_to_one' | 'one_to_many' | 'many_to_one' | 'many_to_many';

interface LinkEditorProps {
  linkId?: string | null;
  defaultSourceTypeId?: string;
  defaultTargetTypeId?: string;
  onCreated?: (link: LinkType) => void;
  onUpdated?: (link: LinkType) => void;
  onDeleted?: (id: string) => void;
}

export function LinkEditor({ linkId = null, defaultSourceTypeId = '', defaultTargetTypeId = '', onCreated, onUpdated, onDeleted }: LinkEditorProps) {
  const [objectTypes, setObjectTypes] = useState<ObjectType[]>([]);
  const [editing, setEditing] = useState<LinkType | null>(null);
  const [draft, setDraft] = useState({
    name: '',
    display_name: '',
    description: '',
    source_type_id: defaultSourceTypeId,
    target_type_id: defaultTargetTypeId,
    cardinality: 'many_to_many' as Cardinality,
  });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    listObjectTypes({ per_page: 200 }).then((r) => setObjectTypes(r.data)).catch(() => {});
  }, []);

  useEffect(() => {
    if (!linkId) {
      setEditing(null);
      setDraft({
        name: '',
        display_name: '',
        description: '',
        source_type_id: defaultSourceTypeId,
        target_type_id: defaultTargetTypeId,
        cardinality: 'many_to_many',
      });
      return;
    }
    listLinkTypes({ per_page: 200 }).then((r) => {
      const found = r.data.find((l) => l.id === linkId) ?? null;
      setEditing(found);
      if (found) {
        setDraft({
          name: found.name,
          display_name: found.display_name,
          description: found.description,
          source_type_id: found.source_type_id,
          target_type_id: found.target_type_id,
          cardinality: found.cardinality as Cardinality,
        });
      }
    }).catch(() => {});
  }, [linkId, defaultSourceTypeId, defaultTargetTypeId]);

  async function save() {
    setSaving(true);
    setError('');
    try {
      if (editing) {
        const updated = await updateLinkType(editing.id, {
          display_name: draft.display_name,
          description: draft.description,
          cardinality: draft.cardinality,
        });
        onUpdated?.(updated);
      } else {
        const created = await createLinkType({
          name: draft.name,
          display_name: draft.display_name,
          description: draft.description,
          source_type_id: draft.source_type_id,
          target_type_id: draft.target_type_id,
          cardinality: draft.cardinality,
        });
        onCreated?.(created);
      }
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setSaving(false);
    }
  }

  async function remove() {
    if (!editing) return;
    if (typeof window !== 'undefined' && !window.confirm(`Delete link "${editing.name}"?`)) return;
    setSaving(true);
    try {
      await deleteLinkType(editing.id);
      onDeleted?.(editing.id);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setSaving(false);
    }
  }

  return (
    <article style={{ display: 'flex', flexDirection: 'column', gap: 8, padding: 12, background: '#0f172a', border: '1px solid #1e293b', borderRadius: 6, color: '#e2e8f0' }}>
      <h3 style={{ margin: 0, fontSize: 14 }}>{editing ? 'Edit link type' : 'New link type'}</h3>
      <label style={{ fontSize: 12 }}>
        Name (identifier)
        <input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} disabled={!!editing} className="of-input" style={{ marginTop: 4, fontFamily: 'var(--font-mono)' }} />
      </label>
      <label style={{ fontSize: 12 }}>
        Display name
        <input value={draft.display_name} onChange={(e) => setDraft({ ...draft, display_name: e.target.value })} className="of-input" style={{ marginTop: 4 }} />
      </label>
      <label style={{ fontSize: 12 }}>
        Description
        <textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} rows={2} className="of-input" style={{ marginTop: 4 }} />
      </label>
      <div style={{ display: 'flex', gap: 8 }}>
        <label style={{ fontSize: 12, flex: 1 }}>
          Source type
          <select value={draft.source_type_id} onChange={(e) => setDraft({ ...draft, source_type_id: e.target.value })} disabled={!!editing} className="of-input" style={{ marginTop: 4 }}>
            <option value="">— pick —</option>
            {objectTypes.map((t) => <option key={t.id} value={t.id}>{t.display_name} ({t.name})</option>)}
          </select>
        </label>
        <label style={{ fontSize: 12, flex: 1 }}>
          Target type
          <select value={draft.target_type_id} onChange={(e) => setDraft({ ...draft, target_type_id: e.target.value })} disabled={!!editing} className="of-input" style={{ marginTop: 4 }}>
            <option value="">— pick —</option>
            {objectTypes.map((t) => <option key={t.id} value={t.id}>{t.display_name} ({t.name})</option>)}
          </select>
        </label>
      </div>
      <label style={{ fontSize: 12 }}>
        Cardinality
        <select value={draft.cardinality} onChange={(e) => setDraft({ ...draft, cardinality: e.target.value as Cardinality })} className="of-input" style={{ marginTop: 4 }}>
          <option value="one_to_one">one_to_one</option>
          <option value="one_to_many">one_to_many</option>
          <option value="many_to_one">many_to_one</option>
          <option value="many_to_many">many_to_many</option>
        </select>
      </label>
      {error && <p style={{ color: '#fca5a5', fontSize: 11, margin: 0 }}>{error}</p>}
      <div style={{ display: 'flex', gap: 6 }}>
        <button type="button" onClick={() => void save()} disabled={saving} className="of-button of-button--primary" style={{ fontSize: 11 }}>
          {saving ? 'Saving…' : editing ? 'Update' : 'Create'}
        </button>
        {editing && (
          <button type="button" onClick={() => void remove()} disabled={saving} className="of-button" style={{ fontSize: 11, color: '#fca5a5', borderColor: '#7f1d1d' }}>Delete</button>
        )}
      </div>
    </article>
  );
}
