// apps/web/src/lib/components/ontology/ObjectExplorer.tsx
import { useEffect, useState } from 'react';

import { listObjects, listProperties, queryObjects, type ObjectInstance, type Property } from '@/lib/api/ontology';
import { ObjectCard } from './ObjectCard';

interface ObjectExplorerProps {
  typeId: string;
  properties?: Property[];
  pageSize?: number;
  onSelect?: (object: ObjectInstance) => void;
}

export function ObjectExplorer({ typeId, properties: propertiesProp, pageSize = 50, onSelect }: ObjectExplorerProps) {
  const [properties, setProperties] = useState<Property[]>(propertiesProp ?? []);
  const [objects, setObjects] = useState<ObjectInstance[]>([]);
  const [filters, setFilters] = useState<Array<{ name: string; value: string }>>([]);
  const [marking, setMarking] = useState('');
  const [layout, setLayout] = useState<'table' | 'cards'>('table');
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (propertiesProp) {
      setProperties(propertiesProp);
      return;
    }
    listProperties(typeId).then(setProperties).catch((e) => setError(e instanceof Error ? e.message : String(e)));
  }, [typeId, propertiesProp]);

  function applyFacet(list: ObjectInstance[]) {
    if (!marking) return list;
    return list.filter((o) => o.marking === marking);
  }

  async function load() {
    setLoading(true);
    setError('');
    try {
      const active = filters.filter((f) => f.name && f.value !== '');
      if (active.length === 0) {
        const r = await listObjects(typeId, { page, per_page: pageSize });
        setObjects(applyFacet(r.data ?? []));
        setTotal(r.total ?? r.data?.length ?? 0);
      } else {
        const equals: Record<string, unknown> = {};
        for (const f of active) equals[f.name] = f.value;
        const r = await queryObjects(typeId, { equals, limit: pageSize });
        setObjects(applyFacet(r.data ?? []));
        setTotal(r.total ?? r.data?.length ?? 0);
      }
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { void load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [typeId, page, marking]);

  function addFilter() {
    setFilters((prev) => [...prev, { name: properties[0]?.name ?? '', value: '' }]);
  }

  return (
    <section style={{ display: 'flex', flexDirection: 'column', gap: 8, padding: 12, background: '#0f172a', border: '1px solid #1e293b', borderRadius: 6, color: '#e2e8f0' }}>
      <header style={{ display: 'flex', flexWrap: 'wrap', gap: 8, alignItems: 'center', justifyContent: 'space-between' }}>
        <h3 style={{ margin: 0, fontSize: 14 }}>Objects ({total})</h3>
        <div style={{ display: 'flex', gap: 6 }}>
          <select value={layout} onChange={(e) => setLayout(e.target.value as typeof layout)} className="of-input" style={{ fontSize: 11 }}>
            <option value="table">Table</option>
            <option value="cards">Cards</option>
          </select>
          <select value={marking} onChange={(e) => setMarking(e.target.value)} className="of-input" style={{ fontSize: 11 }}>
            <option value="">All markings</option>
            <option value="public">public</option>
            <option value="confidential">confidential</option>
            <option value="pii">pii</option>
          </select>
          <button type="button" onClick={() => void load()} disabled={loading} className="of-button" style={{ fontSize: 11 }}>Refresh</button>
        </div>
      </header>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        {filters.map((f, i) => (
          <div key={i} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr auto', gap: 4 }}>
            <select
              value={f.name}
              onChange={(e) => setFilters((prev) => prev.map((p, j) => (j === i ? { ...p, name: e.target.value } : p)))}
              className="of-input"
              style={{ fontSize: 11 }}
            >
              {properties.map((p) => <option key={p.id} value={p.name}>{p.name}</option>)}
            </select>
            <input value={f.value} onChange={(e) => setFilters((prev) => prev.map((p, j) => (j === i ? { ...p, value: e.target.value } : p)))} className="of-input" style={{ fontSize: 11 }} />
            <button type="button" onClick={() => setFilters((prev) => prev.filter((_, j) => j !== i))} className="of-button" style={{ fontSize: 11, color: '#fca5a5', borderColor: '#7f1d1d' }}>×</button>
          </div>
        ))}
        <div style={{ display: 'flex', gap: 6 }}>
          <button type="button" onClick={addFilter} className="of-button" style={{ fontSize: 11 }}>+ Filter</button>
          <button type="button" onClick={() => { setPage(1); void load(); }} className="of-button of-button--primary" style={{ fontSize: 11 }}>Apply</button>
        </div>
      </div>

      {error && <p style={{ color: '#fca5a5', fontSize: 11, margin: 0 }}>{error}</p>}

      {layout === 'table' ? (
        <div style={{ overflow: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
            <thead>
              <tr>
                <th style={{ textAlign: 'left', padding: 6, borderBottom: '1px solid #1f2937' }}>Object id</th>
                {properties.slice(0, 5).map((p) => (
                  <th key={p.id} style={{ textAlign: 'left', padding: 6, borderBottom: '1px solid #1f2937' }}>{p.display_name || p.name}</th>
                ))}
                <th style={{ textAlign: 'left', padding: 6, borderBottom: '1px solid #1f2937' }}>Marking</th>
              </tr>
            </thead>
            <tbody>
              {objects.map((o) => (
                <tr
                  key={o.id}
                  onClick={() => onSelect?.(o)}
                  style={{ cursor: onSelect ? 'pointer' : 'default', borderBottom: '1px solid #1f2937' }}
                >
                  <td style={{ padding: 6, fontFamily: 'var(--font-mono)' }}>{o.id.slice(0, 12)}…</td>
                  {properties.slice(0, 5).map((p) => (
                    <td key={p.id} style={{ padding: 6 }}>{String(o.properties?.[p.name] ?? '')}</td>
                  ))}
                  <td style={{ padding: 6 }}>{o.marking ?? '—'}</td>
                </tr>
              ))}
              {objects.length === 0 && !loading && (
                <tr><td colSpan={properties.length + 2} style={{ padding: 16, textAlign: 'center', color: '#94a3b8', fontStyle: 'italic' }}>No objects.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      ) : (
        <div style={{ display: 'grid', gap: 8, gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))' }}>
          {objects.map((o) => (
            <ObjectCard key={o.id} object={o} properties={properties} onClick={onSelect ? () => onSelect(o) : undefined} />
          ))}
        </div>
      )}

      <footer style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 12 }}>
        <span style={{ color: '#94a3b8' }}>Page {page} · {total} total</span>
        <span style={{ display: 'flex', gap: 6 }}>
          <button type="button" onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page <= 1} className="of-button" style={{ fontSize: 11 }}>← Prev</button>
          <button type="button" onClick={() => setPage((p) => p + 1)} disabled={page * pageSize >= total} className="of-button" style={{ fontSize: 11 }}>Next →</button>
        </span>
      </footer>
    </section>
  );
}

// apps/web/src/lib/components/ontology/ObjectExplorer.svelte
<script lang="ts">
  /**
   * `ObjectExplorer` — tabla de instancias de un `ObjectType` con filtros por
   * propiedad, facets de marking y paginación.
   *
   * Llama a `listObjects` para listados completos y a `queryObjects` cuando
   * hay filtros igualdad activos. La virtualización se hace por slicing de
   * página (per_page); para cargar más, paginación clásica. Una virtualización
   * row-level con `@tanstack/svelte-virtual` queda como TODO si el dataset
   * supera ~5k filas.
   *
   * Contrato Svelte 5:
   * - `typeId: string`
   * - `properties?: Property[]`            — para columnas y selector de filtros.
   * - `pageSize?: number = 50`
   * - `onselect?: (object: ObjectInstance) => void`
   */
  import {
    listObjects,
    listProperties,
    queryObjects,
    type ObjectInstance,
    type Property,
  } from '$lib/api/ontology';
  import ObjectCard from './ObjectCard.svelte';

  type Props = {
    typeId: string;
    properties?: Property[];
    pageSize?: number;
    onselect?: (object: ObjectInstance) => void;
  };

  const { typeId, properties: propertiesProp, pageSize = 50, onselect }: Props = $props();

  let loading = $state(false);
  let error = $state('');
  let page = $state(1);
  let total = $state(0);
  let objects = $state<ObjectInstance[]>([]);
  let properties = $state<Property[]>([]);
  let filters = $state<Array<{ name: string; value: string }>>([]);
  let markingFacet = $state<string>(''); // empty = all
  let layout = $state<'table' | 'cards'>('table');

  $effect(() => {
    if (propertiesProp) {
      properties = propertiesProp;
      return;
    }
    void loadProperties();
  });

  $effect(() => {
    void load();
  });

  // Re-load when typeId/page change.
  // (Filters use explicit "Apply" button to avoid request storm.)

  async function loadProperties() {
    try {
      properties = await listProperties(typeId);
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    }
  }

  async function load() {
    loading = true;
    error = '';
    try {
      const activeFilters = filters.filter((f) => f.name && f.value !== '');
      if (activeFilters.length === 0) {
        const response = await listObjects(typeId, { page, per_page: pageSize });
        objects = applyFacet(response.data ?? []);
        total = response.total ?? objects.length;
      } else {
        const equals: Record<string, unknown> = {};
        for (const filter of activeFilters) equals[filter.name] = filter.value;
        const response = await queryObjects(typeId, { equals, limit: pageSize });
        objects = applyFacet(response.data ?? []);
        total = response.total ?? objects.length;
      }
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  }

  function applyFacet(rows: ObjectInstance[]): ObjectInstance[] {
    if (!markingFacet) return rows;
    return rows.filter((row) => (row.marking ?? 'public') === markingFacet);
  }

  const markingFacets = $derived(
    Array.from(
      objects.reduce((acc, obj) => {
        const key = obj.marking ?? 'public';
        acc.set(key, (acc.get(key) ?? 0) + 1);
        return acc;
      }, new Map<string, number>()),
    ).sort((a, b) => b[1] - a[1]),
  );

  const visibleColumns = $derived(properties.slice(0, 6));
  const totalPages = $derived(Math.max(1, Math.ceil(total / pageSize)));

  function addFilter() {
    filters = [...filters, { name: properties[0]?.name ?? '', value: '' }];
  }
  function removeFilter(index: number) {
    filters = filters.filter((_, i) => i !== index);
  }
</script>

<section class="explorer" aria-busy={loading}>
  <header>
    <h2>Objects ({total})</h2>
    <div class="layout-toggle">
      <button type="button" class:active={layout === 'table'} onclick={() => (layout = 'table')}>Table</button>
      <button type="button" class:active={layout === 'cards'} onclick={() => (layout = 'cards')}>Cards</button>
    </div>
  </header>

  {#if error}<p class="error" role="alert">{error}</p>{/if}

  <section class="filters">
    <div class="filter-row">
      <strong>Filters</strong>
      <button type="button" onclick={addFilter}>+ filter</button>
      <button type="button" onclick={() => void load()}>Apply</button>
    </div>
    {#each filters as filter, index}
      <div class="filter">
        <select bind:value={filter.name}>
          {#each properties as property (property.id)}
            <option value={property.name}>{property.display_name || property.name}</option>
          {/each}
        </select>
        <input bind:value={filter.value} placeholder="value (= equality)" />
        <button type="button" onclick={() => removeFilter(index)}>×</button>
      </div>
    {/each}
  </section>

  {#if markingFacets.length > 1}
    <section class="facets">
      <strong>Marking</strong>
      <button type="button" class:active={!markingFacet} onclick={() => { markingFacet = ''; void load(); }}>
        all ({total})
      </button>
      {#each markingFacets as [marking, count]}
        <button
          type="button"
          class:active={markingFacet === marking}
          onclick={() => { markingFacet = marking; void load(); }}
        >
          {marking} ({count})
        </button>
      {/each}
    </section>
  {/if}

  {#if layout === 'table'}
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>id</th>
            {#each visibleColumns as col (col.id)}
              <th>{col.display_name || col.name}</th>
            {/each}
            <th>marking</th>
          </tr>
        </thead>
        <tbody>
          {#each objects as object (object.id)}
            <tr onclick={() => onselect?.(object)}>
              <td class="mono">{object.id.slice(0, 8)}…</td>
              {#each visibleColumns as col (col.id)}
                <td>{formatCell(object.properties?.[col.name])}</td>
              {/each}
              <td><span class="marking" data-marking={object.marking ?? 'public'}>{object.marking ?? 'public'}</span></td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {:else}
    <div class="cards">
      {#each objects as object (object.id)}
        <ObjectCard
          {object}
          {properties}
          onclick={() => onselect?.(object)}
        />
      {/each}
    </div>
  {/if}

  <footer class="pager">
    <button type="button" disabled={page <= 1 || loading} onclick={() => { page -= 1; void load(); }}>
      ‹ prev
    </button>
    <span>Page {page} / {totalPages}</span>
    <button
      type="button"
      disabled={page >= totalPages || loading}
      onclick={() => { page += 1; void load(); }}
    >
      next ›
    </button>
  </footer>
</section>

<script lang="ts" module>
  function formatCell(value: unknown): string {
    if (value === null || value === undefined) return '—';
    if (typeof value === 'string') return value;
    if (typeof value === 'number' || typeof value === 'boolean') return String(value);
    return JSON.stringify(value);
  }
</script>

<style>
  .explorer { display: flex; flex-direction: column; gap: 0.75rem; }
  header { display: flex; justify-content: space-between; align-items: center; }
  .layout-toggle button { background: #1e293b; }
  .layout-toggle button.active { background: #2563eb; }
  .error { color: #fca5a5; }
  .filters, .facets { display: flex; flex-wrap: wrap; gap: 0.5rem; align-items: center; }
  .filter { display: flex; gap: 0.25rem; align-items: center; }
  .facets button.active { background: #2563eb; color: white; }
  .table-wrap { overflow: auto; max-height: 60vh; border: 1px solid #1e293b; border-radius: 6px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { padding: 0.4rem 0.6rem; text-align: left; border-bottom: 1px solid #1e293b; font-size: 0.85rem; }
  tbody tr { cursor: pointer; }
  tbody tr:hover { background: #1e293b; }
  .mono { font-family: monospace; color: #94a3b8; }
  .marking { padding: 0.1rem 0.35rem; border-radius: 3px; font-size: 0.7rem; }
  .marking[data-marking='public'] { background: #064e3b; color: #6ee7b7; }
  .marking[data-marking='confidential'] { background: #7c2d12; color: #fdba74; }
  .marking[data-marking='pii'] { background: #831843; color: #f9a8d4; }
  .cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 0.75rem; }
  .pager { display: flex; gap: 0.75rem; align-items: center; justify-content: center; }
</style>
