// apps/web/src/lib/components/ontology/TypeEditor.svelte
<script lang="ts">
  /**
   * `TypeEditor` — Form CRUD para un `ObjectType` y sus `Property[]`.
   *
   * Contrato Svelte 5 (runes):
   * - `typeId?: string` — si se pasa, edita; si es `null`/`undefined`, crea.
   * - `oncreated?: (type: ObjectType) => void`
   * - `onupdated?: (type: ObjectType) => void`
   * - `ondeleted?: (id: string) => void`
   *
   * Llama directamente a `createObjectType`, `updateObjectType`,
   * `deleteObjectType`, `listProperties`, `createProperty`, `updateProperty`,
   * `deleteProperty`. El editor in-line de cada propiedad delega en
   * `PropertyPanel.svelte`.
   */
  import {
    createObjectType,
    createProperty,
    deleteObjectType,
    deleteProperty,
    getObjectType,
    listProperties,
    updateObjectType,
    type ObjectType,
    type Property,
  } from '$lib/api/ontology';
  import PropertyPanel from './PropertyPanel.svelte';

  type Props = {
    typeId?: string | null;
    oncreated?: (type: ObjectType) => void;
    onupdated?: (type: ObjectType) => void;
    ondeleted?: (id: string) => void;
  };

  const { typeId = null, oncreated, onupdated, ondeleted }: Props = $props();

  let loading = $state(false);
  let saving = $state(false);
  let error = $state('');

  let draft = $state({
    name: '',
    display_name: '',
    description: '',
    primary_key_property: '',
    icon: '',
    color: '',
  });
  let properties = $state<Property[]>([]);
  let editingType = $state<ObjectType | null>(null);

  const isEdit = $derived(Boolean(typeId));

  $effect(() => {
    if (!typeId) {
      editingType = null;
      properties = [];
      draft = { name: '', display_name: '', description: '', primary_key_property: '', icon: '', color: '' };
      return;
    }
    void loadType(typeId);
  });

  async function loadType(id: string) {
    loading = true;
    error = '';
    try {
      const [type, props] = await Promise.all([getObjectType(id), listProperties(id)]);
      editingType = type;
      properties = props;
      draft = {
        name: type.name,
        display_name: type.display_name,
        description: type.description,
        primary_key_property: type.primary_key_property ?? '',
        icon: type.icon ?? '',
        color: type.color ?? '',
      };
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  }

  async function save() {
    saving = true;
    error = '';
    try {
      if (isEdit && typeId) {
        const updated = await updateObjectType(typeId, {
          display_name: draft.display_name,
          description: draft.description,
          primary_key_property: draft.primary_key_property || undefined,
          icon: draft.icon || undefined,
          color: draft.color || undefined,
        });
        editingType = updated;
        onupdated?.(updated);
      } else {
        if (!draft.name.trim()) throw new Error('name is required');
        const created = await createObjectType({
          name: draft.name,
          display_name: draft.display_name || undefined,
          description: draft.description || undefined,
          primary_key_property: draft.primary_key_property || undefined,
          icon: draft.icon || undefined,
          color: draft.color || undefined,
        });
        editingType = created;
        oncreated?.(created);
      }
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      saving = false;
    }
  }

  async function remove() {
    if (!typeId) return;
    if (!confirm('Delete this object type and all its properties?')) return;
    saving = true;
    try {
      await deleteObjectType(typeId);
      ondeleted?.(typeId);
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      saving = false;
    }
  }

  let newPropertyOpen = $state(false);
  let newPropertyDraft = $state({ name: '', display_name: '', property_type: 'string', required: false });

  async function addProperty() {
    if (!editingType) return;
    try {
      const created = await createProperty(editingType.id, {
        name: newPropertyDraft.name,
        display_name: newPropertyDraft.display_name || undefined,
        property_type: newPropertyDraft.property_type,
        required: newPropertyDraft.required,
      });
      properties = [...properties, created];
      newPropertyDraft = { name: '', display_name: '', property_type: 'string', required: false };
      newPropertyOpen = false;
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    }
  }

  async function removeProperty(prop: Property) {
    if (!editingType) return;
    if (!confirm(`Delete property "${prop.name}"?`)) return;
    try {
      await deleteProperty(editingType.id, prop.id);
      properties = properties.filter((p) => p.id !== prop.id);
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    }
  }

  function onPropertyUpdated(updated: Property) {
    properties = properties.map((p) => (p.id === updated.id ? updated : p));
  }
</script>

<section class="type-editor" aria-busy={loading || saving}>
  <header>
    <h2>{isEdit ? `Edit object type: ${editingType?.display_name ?? ''}` : 'Create object type'}</h2>
    {#if error}<p class="error" role="alert">{error}</p>{/if}
  </header>

  <form
    class="grid"
    onsubmit={(event) => {
      event.preventDefault();
      void save();
    }}
  >
    <label>
      <span>Name (slug)</span>
      <input bind:value={draft.name} required disabled={isEdit} />
    </label>
    <label>
      <span>Display name</span>
      <input bind:value={draft.display_name} />
    </label>
    <label class="full">
      <span>Description</span>
      <textarea bind:value={draft.description} rows="2"></textarea>
    </label>
    <label>
      <span>Primary key property</span>
      <input bind:value={draft.primary_key_property} placeholder="e.g. tail_number" />
    </label>
    <label>
      <span>Icon</span>
      <input bind:value={draft.icon} />
    </label>
    <label>
      <span>Color</span>
      <input bind:value={draft.color} type="color" />
    </label>

    <div class="actions">
      <button type="submit" disabled={saving}>{isEdit ? 'Save changes' : 'Create type'}</button>
      {#if isEdit}
        <button type="button" class="danger" disabled={saving} onclick={() => void remove()}>
          Delete
        </button>
      {/if}
    </div>
  </form>

  {#if isEdit && editingType}
    <section class="properties">
      <header>
        <h3>Properties ({properties.length})</h3>
        <button type="button" onclick={() => (newPropertyOpen = !newPropertyOpen)}>
          {newPropertyOpen ? 'Cancel' : '+ Add property'}
        </button>
      </header>

      {#if newPropertyOpen}
        <form
          class="new-prop"
          onsubmit={(event) => {
            event.preventDefault();
            void addProperty();
          }}
        >
          <input bind:value={newPropertyDraft.name} placeholder="name (slug)" required />
          <input bind:value={newPropertyDraft.display_name} placeholder="display name" />
          <select bind:value={newPropertyDraft.property_type}>
            <option value="string">string</option>
            <option value="number">number</option>
            <option value="boolean">boolean</option>
            <option value="datetime">datetime</option>
            <option value="json">json</option>
            <option value="vector">vector</option>
          </select>
          <label class="inline">
            <input type="checkbox" bind:checked={newPropertyDraft.required} /> required
          </label>
          <button type="submit">Add</button>
        </form>
      {/if}

      <ul class="prop-list">
        {#each properties as property (property.id)}
          <li>
            <PropertyPanel
              {property}
              typeId={editingType.id}
              isPrimaryKey={property.name === draft.primary_key_property}
              onupdated={onPropertyUpdated}
              ondeleted={() => void removeProperty(property)}
            />
          </li>
        {/each}
      </ul>
    </section>
  {/if}
</section>

<style>
  .type-editor { display: flex; flex-direction: column; gap: 1.25rem; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem 1rem; }
  .grid .full { grid-column: 1 / -1; }
  label { display: flex; flex-direction: column; gap: 0.25rem; font-size: 0.85rem; }
  label.inline { flex-direction: row; align-items: center; gap: 0.25rem; }
  .actions { grid-column: 1 / -1; display: flex; gap: 0.5rem; }
  .danger { background: #b91c1c; color: white; }
  .error { color: #b91c1c; }
  .properties header { display: flex; justify-content: space-between; align-items: center; }
  .new-prop { display: grid; grid-template-columns: repeat(5, 1fr); gap: 0.5rem; margin-bottom: 0.75rem; }
  .prop-list { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 0.5rem; }
</style>

// apps/web/src/lib/components/ontology/TypeEditor.tsx
import { useEffect, useState } from 'react';

import {
  createObjectType,
  createProperty,
  deleteObjectType,
  deleteProperty,
  getObjectType,
  listProperties,
  updateObjectType,
  type ObjectType,
  type Property,
} from '@/lib/api/ontology';
import { PropertyPanel } from './PropertyPanel';
import { PropertyTypeEditor, type PropertyType } from './PropertyTypeEditor';

interface TypeEditorProps {
  typeId?: string | null;
  onCreated?: (type: ObjectType) => void;
  onUpdated?: (type: ObjectType) => void;
  onDeleted?: (id: string) => void;
}

export function TypeEditor({ typeId = null, onCreated, onUpdated, onDeleted }: TypeEditorProps) {
  const [draft, setDraft] = useState({
    name: '',
    display_name: '',
    description: '',
    primary_key_property: '',
    icon: '',
    color: '#1d4ed8',
  });
  const [properties, setProperties] = useState<Property[]>([]);
  const [editing, setEditing] = useState<ObjectType | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  // new property form
  const [newName, setNewName] = useState('');
  const [newDisplay, setNewDisplay] = useState('');
  const [newType, setNewType] = useState<PropertyType>('string');
  const [newRequired, setNewRequired] = useState(false);

  useEffect(() => {
    if (!typeId) {
      setEditing(null);
      setProperties([]);
      setDraft({ name: '', display_name: '', description: '', primary_key_property: '', icon: '', color: '#1d4ed8' });
      return;
    }
    Promise.all([getObjectType(typeId), listProperties(typeId)])
      .then(([type, props]) => {
        setEditing(type);
        setProperties(props);
        setDraft({
          name: type.name,
          display_name: type.display_name,
          description: type.description,
          primary_key_property: type.primary_key_property ?? '',
          icon: type.icon ?? '',
          color: type.color ?? '#1d4ed8',
        });
      })
      .catch((cause: unknown) => setError(cause instanceof Error ? cause.message : String(cause)));
  }, [typeId]);

  async function save() {
    setSaving(true);
    setError('');
    try {
      if (editing) {
        const updated = await updateObjectType(editing.id, {
          display_name: draft.display_name,
          description: draft.description,
          primary_key_property: draft.primary_key_property || undefined,
          icon: draft.icon || undefined,
          color: draft.color || undefined,
        });
        setEditing(updated);
        onUpdated?.(updated);
      } else {
        const created = await createObjectType({
          name: draft.name,
          display_name: draft.display_name,
          description: draft.description,
          icon: draft.icon || undefined,
          color: draft.color || undefined,
        });
        setEditing(created);
        onCreated?.(created);
      }
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setSaving(false);
    }
  }

  async function remove() {
    if (!editing) return;
    if (typeof window !== 'undefined' && !window.confirm(`Delete object type "${editing.name}"?`)) return;
    setSaving(true);
    try {
      await deleteObjectType(editing.id);
      onDeleted?.(editing.id);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setSaving(false);
    }
  }

  async function addProperty() {
    if (!editing || !newName.trim()) return;
    try {
      const created = await createProperty(editing.id, {
        name: newName.trim(),
        display_name: newDisplay.trim() || newName.trim(),
        property_type: newType,
        required: newRequired,
      });
      setProperties((prev) => [...prev, created]);
      setNewName('');
      setNewDisplay('');
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    }
  }

  async function removeProperty(p: Property) {
    if (!editing) return;
    if (typeof window !== 'undefined' && !window.confirm(`Delete property "${p.name}"?`)) return;
    try {
      await deleteProperty(editing.id, p.id);
      setProperties((prev) => prev.filter((q) => q.id !== p.id));
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    }
  }

  return (
    <article style={{ display: 'flex', flexDirection: 'column', gap: 12, padding: 12, background: '#0f172a', border: '1px solid #1e293b', borderRadius: 6, color: '#e2e8f0' }}>
      <h3 style={{ margin: 0, fontSize: 14 }}>{editing ? 'Edit object type' : 'New object type'}</h3>
      <label style={{ fontSize: 12 }}>
        Name (identifier)
        <input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} disabled={!!editing} className="of-input" style={{ marginTop: 4, fontFamily: 'var(--font-mono)' }} />
      </label>
      <label style={{ fontSize: 12 }}>
        Display name
        <input value={draft.display_name} onChange={(e) => setDraft({ ...draft, display_name: e.target.value })} className="of-input" style={{ marginTop: 4 }} />
      </label>
      <label style={{ fontSize: 12 }}>
        Description
        <textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} rows={2} className="of-input" style={{ marginTop: 4 }} />
      </label>
      <div style={{ display: 'flex', gap: 8 }}>
        <label style={{ fontSize: 12, flex: 1 }}>
          Icon
          <input value={draft.icon} onChange={(e) => setDraft({ ...draft, icon: e.target.value })} placeholder="📄" className="of-input" style={{ marginTop: 4 }} />
        </label>
        <label style={{ fontSize: 12, flex: 1 }}>
          Color
          <input type="color" value={draft.color} onChange={(e) => setDraft({ ...draft, color: e.target.value })} className="of-input" style={{ marginTop: 4, padding: 2, height: 36 }} />
        </label>
      </div>
      {editing && (
        <label style={{ fontSize: 12 }}>
          Primary key property
          <select value={draft.primary_key_property} onChange={(e) => setDraft({ ...draft, primary_key_property: e.target.value })} className="of-input" style={{ marginTop: 4 }}>
            <option value="">—</option>
            {properties.map((p) => <option key={p.id} value={p.name}>{p.name}</option>)}
          </select>
        </label>
      )}
      {error && <p style={{ color: '#fca5a5', fontSize: 11, margin: 0 }}>{error}</p>}
      <div style={{ display: 'flex', gap: 6 }}>
        <button type="button" onClick={() => void save()} disabled={saving} className="of-button of-button--primary" style={{ fontSize: 11 }}>{saving ? 'Saving…' : editing ? 'Update' : 'Create'}</button>
        {editing && <button type="button" onClick={() => void remove()} disabled={saving} className="of-button" style={{ fontSize: 11, color: '#fca5a5', borderColor: '#7f1d1d' }}>Delete</button>}
      </div>

      {editing && (
        <section style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 12 }}>
          <h4 style={{ margin: 0, fontSize: 13 }}>Properties ({properties.length})</h4>
          <div style={{ padding: 8, background: '#0b1220', borderRadius: 6, display: 'grid', gap: 6 }}>
            <input value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="property name" className="of-input" style={{ fontSize: 11, fontFamily: 'var(--font-mono)' }} />
            <input value={newDisplay} onChange={(e) => setNewDisplay(e.target.value)} placeholder="display name" className="of-input" style={{ fontSize: 11 }} />
            <PropertyTypeEditor propertyType={newType} onChange={setNewType} />
            <label style={{ fontSize: 11, display: 'flex', gap: 4, alignItems: 'center' }}>
              <input type="checkbox" checked={newRequired} onChange={(e) => setNewRequired(e.target.checked)} />
              required
            </label>
            <button type="button" onClick={() => void addProperty()} disabled={!newName.trim()} className="of-button of-button--primary" style={{ fontSize: 11, alignSelf: 'flex-start' }}>+ Add property</button>
          </div>
          {properties.map((p) => (
            <div key={p.id} style={{ display: 'flex', alignItems: 'flex-start', gap: 6 }}>
              <div style={{ flex: 1 }}>
                <PropertyPanel property={p} typeId={editing.id} isPrimaryKey={draft.primary_key_property === p.name} onUpdated={(next) => setProperties((prev) => prev.map((x) => (x.id === next.id ? next : x)))} />
              </div>
              <button type="button" onClick={() => void removeProperty(p)} className="of-button" style={{ fontSize: 11, color: '#fca5a5', borderColor: '#7f1d1d' }}>×</button>
            </div>
          ))}
        </section>
      )}
    </article>
  );
}
