// apps/web/src/lib/components/audit/AuditLogViewer.svelte
<script lang="ts">
	import type { AuditEvent, AuditEventStatus, AuditSeverity, ClassificationCatalogEntry, ClassificationLevel } from '$lib/api/audit';

	type EventFilterDraft = {
		source_service: string;
		subject_id: string;
		classification: string;
	};

	type EventDraft = {
		source_service: string;
		channel: string;
		actor: string;
		action: string;
		resource_type: string;
		resource_id: string;
		status: AuditEventStatus;
		severity: AuditSeverity;
		classification: ClassificationLevel;
		subject_id: string;
		ip_address: string;
		location: string;
		labels_text: string;
		metadata_text: string;
		retention_days: string;
	};

	export let events: AuditEvent[] = [];
	export let classifications: ClassificationCatalogEntry[] = [];
	export let filters: EventFilterDraft;
	export let draft: EventDraft;
	export let busy = false;
	export let onFilterChange: (patch: Partial<EventFilterDraft>) => void;
	export let onApplyFilters: () => void;
	export let onDraftChange: (patch: Partial<EventDraft>) => void;
	export let onAppendEvent: () => void;
	/**
	 * Show the "Manual event probe" appender. The global Audit page
	 * uses it to seed test events; per-resource Activity panels embed
	 * the viewer in read-only mode and pass `false` to keep the
	 * surface focused on history. Defaults to `true` so existing
	 * call-sites are unaffected.
	 */
	export let showProbeForm = true;

	const statuses: AuditEventStatus[] = ['success', 'failure', 'denied'];
	const severities: AuditSeverity[] = ['low', 'medium', 'high', 'critical'];

	function inputValue(event: Event) {
		return (event.currentTarget as HTMLInputElement).value;
	}

	function textValue(event: Event) {
		return (event.currentTarget as HTMLTextAreaElement).value;
	}
</script>

<section class="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm shadow-stone-200/60">
	<div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
		<div>
			<p class="text-xs font-semibold uppercase tracking-[0.24em] text-sky-700">Audit Log Viewer</p>
			<h3 class="mt-2 text-xl font-semibold text-stone-900">Append-only events with filters and manual probes</h3>
			<p class="mt-1 text-sm text-stone-500">Filter by service, subject, or classification, and append probe events to validate the chain end to end.</p>
		</div>
		{#if showProbeForm}
			<button class="rounded-full bg-sky-500 px-4 py-2 text-sm font-semibold text-stone-950 transition hover:bg-sky-400 disabled:cursor-not-allowed disabled:bg-sky-200" onclick={onAppendEvent} disabled={busy}>Append event</button>
		{/if}
	</div>

	<div class={`mt-5 grid gap-4 ${showProbeForm ? 'xl:grid-cols-[1.02fr_0.98fr]' : ''}`}>
		<div class="space-y-4 rounded-2xl border border-stone-200 bg-stone-50/80 p-4">
			<div class="grid gap-4 md:grid-cols-3">
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-700">Source service</span>
					<input class="w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 outline-none transition focus:border-sky-500" value={filters.source_service} oninput={(event) => onFilterChange({ source_service: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-700">Subject ID</span>
					<input class="w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 outline-none transition focus:border-sky-500" value={filters.subject_id} oninput={(event) => onFilterChange({ subject_id: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-700">Classification</span>
					<select class="w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 outline-none transition focus:border-sky-500" value={filters.classification} onchange={(event) => onFilterChange({ classification: (event.currentTarget as HTMLSelectElement).value })}>
						<option value="">All</option>
						{#each classifications as option}
							<option value={option.classification}>{option.classification}</option>
						{/each}
					</select>
				</label>
			</div>
			<button class="rounded-full border border-sky-300 px-4 py-2 text-sm font-medium text-sky-700 transition hover:border-sky-400 hover:bg-sky-50" onclick={onApplyFilters} disabled={busy}>Apply filters</button>

			<div class="space-y-3">
				{#each events as event}
					<div class="rounded-2xl border border-stone-200 bg-white px-4 py-4">
						<div class="flex items-start justify-between gap-3">
							<div>
								<p class="font-semibold text-stone-900">#{event.sequence} • {event.action}</p>
								<p class="text-sm text-stone-500">{event.source_service} • {event.actor} • {event.resource_type}:{event.resource_id}</p>
							</div>
							<span class={`rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] ${event.severity === 'critical' ? 'bg-rose-100 text-rose-700' : 'bg-stone-100 text-stone-700'}`}>{event.severity}</span>
						</div>
						<div class="mt-3 flex flex-wrap gap-2 text-xs text-stone-600">
							<span class="rounded-full bg-stone-100 px-2 py-1">{event.status}</span>
							<span class="rounded-full bg-stone-100 px-2 py-1">{event.classification}</span>
							{#each event.labels as label}
								<span class="rounded-full bg-sky-50 px-2 py-1 text-sky-700">{label}</span>
							{/each}
						</div>
					</div>
				{/each}
			</div>
		</div>

		{#if showProbeForm}
		<div class="rounded-2xl border border-stone-200 bg-stone-950 p-4 text-stone-100">
			<p class="text-xs font-semibold uppercase tracking-[0.2em] text-sky-300">Manual event probe</p>
			<div class="mt-4 grid gap-4 md:grid-cols-2">
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Service</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.source_service} oninput={(event) => onDraftChange({ source_service: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Channel</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.channel} oninput={(event) => onDraftChange({ channel: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Actor</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.actor} oninput={(event) => onDraftChange({ actor: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Action</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.action} oninput={(event) => onDraftChange({ action: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Resource type</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.resource_type} oninput={(event) => onDraftChange({ resource_type: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Resource ID</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.resource_id} oninput={(event) => onDraftChange({ resource_id: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Status</span>
					<select class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.status} onchange={(event) => onDraftChange({ status: (event.currentTarget as HTMLSelectElement).value as AuditEventStatus })}>
						{#each statuses as status}
							<option value={status}>{status}</option>
						{/each}
					</select>
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Severity</span>
					<select class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.severity} onchange={(event) => onDraftChange({ severity: (event.currentTarget as HTMLSelectElement).value as AuditSeverity })}>
						{#each severities as severity}
							<option value={severity}>{severity}</option>
						{/each}
					</select>
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Classification</span>
					<select class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.classification} onchange={(event) => onDraftChange({ classification: (event.currentTarget as HTMLSelectElement).value as ClassificationLevel })}>
						{#each classifications as option}
							<option value={option.classification}>{option.classification}</option>
						{/each}
					</select>
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Subject ID</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.subject_id} oninput={(event) => onDraftChange({ subject_id: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">IP address</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.ip_address} oninput={(event) => onDraftChange({ ip_address: inputValue(event) })} />
				</label>
				<label class="block text-sm">
					<span class="mb-2 block font-medium text-stone-100">Location</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.location} oninput={(event) => onDraftChange({ location: inputValue(event) })} />
				</label>
				<label class="block text-sm md:col-span-2">
					<span class="mb-2 block font-medium text-stone-100">Labels</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.labels_text} oninput={(event) => onDraftChange({ labels_text: inputValue(event) })} />
				</label>
				<label class="block text-sm md:col-span-2">
					<span class="mb-2 block font-medium text-stone-100">Metadata JSON</span>
					<textarea class="min-h-24 w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 font-mono text-xs text-sky-100 outline-none transition focus:border-sky-400" oninput={(event) => onDraftChange({ metadata_text: textValue(event) })}>{draft.metadata_text}</textarea>
				</label>
				<label class="block text-sm md:col-span-2">
					<span class="mb-2 block font-medium text-stone-100">Retention days</span>
					<input class="w-full rounded-2xl border border-stone-700 bg-stone-900 px-4 py-3 outline-none transition focus:border-sky-400" value={draft.retention_days} oninput={(event) => onDraftChange({ retention_days: inputValue(event) })} />
				</label>
			</div>
		</div>
		{/if}
	</div>
</section>

// apps/web/src/lib/components/audit/AuditLogViewer.tsx
import type {
  AuditEvent,
  AuditEventStatus,
  AuditSeverity,
  ClassificationCatalogEntry,
  ClassificationLevel,
} from '@/lib/api/audit';

export interface EventFilterDraft {
  source_service: string;
  subject_id: string;
  classification: string;
}

export interface EventDraft {
  source_service: string;
  channel: string;
  actor: string;
  action: string;
  resource_type: string;
  resource_id: string;
  status: AuditEventStatus;
  severity: AuditSeverity;
  classification: ClassificationLevel;
  subject_id: string;
  ip_address: string;
  location: string;
  labels_text: string;
  metadata_text: string;
  retention_days: string;
}

interface Props {
  events: AuditEvent[];
  classifications: ClassificationCatalogEntry[];
  filters: EventFilterDraft;
  draft: EventDraft;
  busy?: boolean;
  onFilterChange: (patch: Partial<EventFilterDraft>) => void;
  onApplyFilters: () => void;
  onDraftChange: (patch: Partial<EventDraft>) => void;
  onAppendEvent: () => void;
  showProbeForm?: boolean;
}

const STATUSES: AuditEventStatus[] = ['success', 'failure', 'denied'];
const SEVERITIES: AuditSeverity[] = ['low', 'medium', 'high', 'critical'];

const darkInput: React.CSSProperties = {
  width: '100%',
  borderRadius: 16,
  border: '1px solid #44403c',
  background: '#1c1917',
  padding: '10px 14px',
  color: '#f5f5f4',
  fontSize: 13,
  outline: 'none',
};

export function AuditLogViewer({
  events,
  classifications,
  filters,
  draft,
  busy = false,
  onFilterChange,
  onApplyFilters,
  onDraftChange,
  onAppendEvent,
  showProbeForm = true,
}: Props) {
  return (
    <section className="of-panel" style={{ padding: 20 }}>
      <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
        <div>
          <p className="of-eyebrow" style={{ color: '#0369a1' }}>
            Audit Log Viewer
          </p>
          <h3 className="of-heading-md" style={{ marginTop: 6 }}>
            Append-only events with filters and manual probes
          </h3>
          <p className="of-text-muted" style={{ marginTop: 4, fontSize: 13 }}>
            Filter by service, subject, or classification, and append probe events to validate the chain end to end.
          </p>
        </div>
        {showProbeForm && (
          <button type="button" onClick={onAppendEvent} disabled={busy} className="of-button of-button--primary" style={{ background: '#0ea5e9' }}>
            Append event
          </button>
        )}
      </div>

      <div style={{ display: 'grid', gap: 16, gridTemplateColumns: showProbeForm ? 'minmax(0, 1.02fr) minmax(0, 0.98fr)' : '1fr', marginTop: 18 }}>
        <div className="of-panel-muted" style={{ padding: 14, display: 'grid', gap: 12 }}>
          <div style={{ display: 'grid', gap: 12, gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))' }}>
            <label style={{ fontSize: 13 }}>
              <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Source service</span>
              <input
                value={filters.source_service}
                onChange={(e) => onFilterChange({ source_service: e.target.value })}
                className="of-input"
              />
            </label>
            <label style={{ fontSize: 13 }}>
              <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Subject ID</span>
              <input
                value={filters.subject_id}
                onChange={(e) => onFilterChange({ subject_id: e.target.value })}
                className="of-input"
              />
            </label>
            <label style={{ fontSize: 13 }}>
              <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Classification</span>
              <select
                value={filters.classification}
                onChange={(e) => onFilterChange({ classification: e.target.value })}
                className="of-input"
              >
                <option value="">All</option>
                {classifications.map((option) => (
                  <option key={option.classification} value={option.classification}>
                    {option.classification}
                  </option>
                ))}
              </select>
            </label>
          </div>
          <button type="button" onClick={onApplyFilters} disabled={busy} className="of-button" style={{ width: 'fit-content' }}>
            Apply filters
          </button>

          <div style={{ display: 'grid', gap: 8 }}>
            {events.map((event) => (
              <div key={event.id} className="of-panel" style={{ padding: 12 }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }}>
                  <div>
                    <p style={{ fontWeight: 600, color: 'var(--text-strong)' }}>
                      #{event.sequence} · {event.action}
                    </p>
                    <p className="of-text-muted" style={{ fontSize: 13 }}>
                      {event.source_service} · {event.actor} · {event.resource_type}:{event.resource_id}
                    </p>
                  </div>
                  <span
                    className="of-chip"
                    style={
                      event.severity === 'critical'
                        ? { background: '#fef2f2', color: '#b91c1c' }
                        : { background: 'var(--bg-subtle)', color: 'var(--text-muted)' }
                    }
                  >
                    {event.severity}
                  </span>
                </div>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 8 }}>
                  <span className="of-chip">{event.status}</span>
                  <span className="of-chip">{event.classification}</span>
                  {event.labels.map((label) => (
                    <span key={label} className="of-chip" style={{ background: '#dbeafe', color: '#0369a1' }}>
                      {label}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {showProbeForm && (
          <div style={{ borderRadius: 16, padding: 14, background: '#0c0a09' }}>
            <p style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.18em', color: '#7dd3fc' }}>
              Manual event probe
            </p>
            <div style={{ display: 'grid', gap: 12, gridTemplateColumns: '1fr 1fr', marginTop: 14 }}>
              {(['source_service', 'channel', 'actor', 'action', 'resource_type', 'resource_id'] as const).map((field) => (
                <label key={field} style={{ fontSize: 13, color: '#f5f5f4' }}>
                  <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>{field.replace(/_/g, ' ')}</span>
                  <input
                    value={draft[field]}
                    onChange={(e) => onDraftChange({ [field]: e.target.value } as Partial<EventDraft>)}
                    style={darkInput}
                  />
                </label>
              ))}
              <label style={{ fontSize: 13, color: '#f5f5f4' }}>
                <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Status</span>
                <select
                  value={draft.status}
                  onChange={(e) => onDraftChange({ status: e.target.value as AuditEventStatus })}
                  style={darkInput}
                >
                  {STATUSES.map((status) => (
                    <option key={status} value={status}>
                      {status}
                    </option>
                  ))}
                </select>
              </label>
              <label style={{ fontSize: 13, color: '#f5f5f4' }}>
                <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Severity</span>
                <select
                  value={draft.severity}
                  onChange={(e) => onDraftChange({ severity: e.target.value as AuditSeverity })}
                  style={darkInput}
                >
                  {SEVERITIES.map((severity) => (
                    <option key={severity} value={severity}>
                      {severity}
                    </option>
                  ))}
                </select>
              </label>
              <label style={{ fontSize: 13, color: '#f5f5f4' }}>
                <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Classification</span>
                <select
                  value={draft.classification}
                  onChange={(e) => onDraftChange({ classification: e.target.value as ClassificationLevel })}
                  style={darkInput}
                >
                  {classifications.map((option) => (
                    <option key={option.classification} value={option.classification}>
                      {option.classification}
                    </option>
                  ))}
                </select>
              </label>
              {(['subject_id', 'ip_address', 'location'] as const).map((field) => (
                <label key={field} style={{ fontSize: 13, color: '#f5f5f4' }}>
                  <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>{field.replace(/_/g, ' ')}</span>
                  <input
                    value={draft[field]}
                    onChange={(e) => onDraftChange({ [field]: e.target.value } as Partial<EventDraft>)}
                    style={darkInput}
                  />
                </label>
              ))}
              <label style={{ fontSize: 13, color: '#f5f5f4', gridColumn: 'span 2' }}>
                <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Labels</span>
                <input
                  value={draft.labels_text}
                  onChange={(e) => onDraftChange({ labels_text: e.target.value })}
                  style={darkInput}
                />
              </label>
              <label style={{ fontSize: 13, color: '#f5f5f4', gridColumn: 'span 2' }}>
                <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Metadata JSON</span>
                <textarea
                  value={draft.metadata_text}
                  onChange={(e) => onDraftChange({ metadata_text: e.target.value })}
                  style={{ ...darkInput, minHeight: 90, fontFamily: 'var(--font-mono)', fontSize: 11, color: '#7dd3fc', resize: 'vertical' }}
                />
              </label>
              <label style={{ fontSize: 13, color: '#f5f5f4', gridColumn: 'span 2' }}>
                <span style={{ display: 'block', marginBottom: 6, fontWeight: 500 }}>Retention days</span>
                <input
                  value={draft.retention_days}
                  onChange={(e) => onDraftChange({ retention_days: e.target.value })}
                  style={darkInput}
                />
              </label>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
