// apps/web/src/lib/components/data-connection/CreateAutoRegistrationModal.tsx
import { useMemo, useState } from 'react';

import {
  virtualTables,
  type EnableAutoRegistrationRequest,
  type FolderMirrorKind,
  type VirtualTableProvider,
  type VirtualTableSourceLink,
} from '@/lib/api/virtual-tables';

interface Props {
  open: boolean;
  sourceRid: string;
  provider: VirtualTableProvider;
  onClose: () => void;
  onEnabled?: (link: VirtualTableSourceLink) => void;
}

type StepId = 'project' | 'layout' | 'tags' | 'interval' | 'review';

const POLL_OPTIONS = [
  { label: '15 minutes', value: 900 },
  { label: '1 hour', value: 3600 },
  { label: '6 hours', value: 21600 },
  { label: '24 hours', value: 86400 },
];

export function CreateAutoRegistrationModal({ open, sourceRid, provider, onClose, onEnabled }: Props) {
  const [stepIndex, setStepIndex] = useState(0);
  const [projectName, setProjectName] = useState('');
  const [layout, setLayout] = useState<FolderMirrorKind>('NESTED');
  const [tagFilters, setTagFilters] = useState<string[]>([]);
  const [tagDraft, setTagDraft] = useState('');
  const [pollIntervalSeconds, setPollIntervalSeconds] = useState(3600);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  const steps: StepId[] = useMemo(
    () => provider === 'DATABRICKS' ? ['project', 'layout', 'tags', 'interval', 'review'] : ['project', 'layout', 'interval', 'review'],
    [provider],
  );

  if (!open) return null;

  const current: StepId = steps[Math.min(stepIndex, steps.length - 1)] ?? 'review';

  function isValid(): boolean {
    switch (current) {
      case 'project': return projectName.trim().length > 0;
      case 'layout': return layout === 'FLAT' || layout === 'NESTED';
      case 'tags': return true;
      case 'interval': return pollIntervalSeconds >= 60;
      case 'review': return true;
    }
  }

  function addTag() {
    const t = tagDraft.trim();
    if (!t) return;
    setTagFilters((prev) => prev.includes(t) ? prev : [...prev, t]);
    setTagDraft('');
  }

  async function submit() {
    setBusy(true);
    setError('');
    const body: EnableAutoRegistrationRequest = {
      project_name: projectName.trim(),
      folder_mirror_kind: layout,
      table_tag_filters: provider === 'DATABRICKS' ? tagFilters : [],
      poll_interval_seconds: pollIntervalSeconds,
    };
    try {
      const link = await virtualTables.enableAutoRegistration(sourceRid, body);
      onEnabled?.(link);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to enable auto-registration');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div role="dialog" aria-modal="true" style={backdropStyle}>
      <div style={modalStyle}>
        <header>
          <h3 style={{ margin: '0 0 4px' }}>Enable auto-registration</h3>
          <p style={{ ...mutedStyle, fontSize: 12, margin: 0 }}>
            Step {stepIndex + 1} of {steps.length} · <span style={{ textTransform: 'capitalize' }}>{current.replace('-', ' ')}</span>
          </p>
          <ol style={stepperStyle}>
            {steps.map((id, i) => (
              <li key={id} style={i === stepIndex ? stepActiveStyle : i < stepIndex ? stepDoneStyle : stepIdleStyle}>{id}</li>
            ))}
          </ol>
        </header>

        {current === 'project' && (
          <section>
            <label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <span>Foundry-managed project name</span>
              <input type="text" value={projectName} onChange={(e) => setProjectName(e.target.value)} placeholder="warehouse mirror" style={inputStyle} />
            </label>
            <p style={hintStyle}>A new project will be created and managed by <code>virtual-table-service</code>. Users cannot create or modify resources in it directly.</p>
          </section>
        )}

        {current === 'layout' && (
          <section style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <label style={radioCardStyle}>
              <input type="radio" name="layout" checked={layout === 'NESTED'} onChange={() => setLayout('NESTED')} style={{ marginTop: 4 }} />
              <div>
                <strong>Nested</strong>
                <p style={hintStyle}><code>{'<project>/<database>/<schema>/<table>'}</code></p>
                <pre style={previewStyle}>{`main\n└── public\n    └── orders`}</pre>
              </div>
            </label>
            <label style={radioCardStyle}>
              <input type="radio" name="layout" checked={layout === 'FLAT'} onChange={() => setLayout('FLAT')} style={{ marginTop: 4 }} />
              <div>
                <strong>Flat</strong>
                <p style={hintStyle}><code>{'<project>/<database>__<schema>__<table>'}</code></p>
                <pre style={previewStyle}>main__public__orders</pre>
              </div>
            </label>
          </section>
        )}

        {current === 'tags' && (
          <section>
            <p style={hintStyle}>Only Databricks tables tagged with at least one of these tags will be auto-registered. Reads <code>INFORMATION_SCHEMA.TABLE_TAGS</code> on the workspace metastore.</p>
            <div style={{ display: 'flex', gap: 8 }}>
              <input type="text" placeholder="gold, pii, certified…" value={tagDraft} onChange={(e) => setTagDraft(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addTag(); } }} style={{ ...inputStyle, flex: 1 }} />
              <button type="button" onClick={addTag} style={btnStyle}>Add</button>
            </div>
            <ul style={{ display: 'flex', flexWrap: 'wrap', gap: 4, listStyle: 'none', padding: 0, margin: '8px 0 0' }}>
              {tagFilters.map((tag) => (
                <li key={tag} style={chipStyle}>
                  {tag}
                  <button type="button" onClick={() => setTagFilters((prev) => prev.filter((t) => t !== tag))} aria-label={`Remove ${tag}`} style={{ border: 'none', background: 'transparent', cursor: 'pointer', color: '#b91c1c', fontSize: 12 }}>✕</button>
                </li>
              ))}
            </ul>
          </section>
        )}

        {current === 'interval' && (
          <section>
            <p style={hintStyle}>How often the scanner re-runs against the source. Per Foundry doc the recommendation is 1 hour — too short costs compute, too long delays new-table discovery.</p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {POLL_OPTIONS.map((opt) => (
                <label key={opt.value} style={radioCardStyle}>
                  <input type="radio" name="poll" checked={pollIntervalSeconds === opt.value} onChange={() => setPollIntervalSeconds(opt.value)} />
                  {opt.label}
                </label>
              ))}
              <label style={{ ...radioCardStyle, flexDirection: 'row', alignItems: 'center' }}>
                <input type="number" min={60} value={pollIntervalSeconds} onChange={(e) => setPollIntervalSeconds(Number(e.target.value))} style={{ width: 128, padding: '4px 8px', border: '1px solid #d1d5db', borderRadius: 4 }} />
                <span>seconds</span>
              </label>
            </div>
          </section>
        )}

        {current === 'review' && (
          <section>
            <dl style={{ display: 'grid', gridTemplateColumns: 'max-content 1fr', gap: '4px 12px', margin: 0, fontSize: 14 }}>
              <dt style={dtStyle}>Project</dt><dd style={{ margin: 0 }}>{projectName}</dd>
              <dt style={dtStyle}>Layout</dt><dd style={{ margin: 0 }}>{layout}</dd>
              {provider === 'DATABRICKS' && (
                <>
                  <dt style={dtStyle}>Tag filters</dt>
                  <dd style={{ margin: 0 }}>{tagFilters.length === 0 ? <span style={mutedStyle}>none — every accessible table is mirrored</span> : tagFilters.join(', ')}</dd>
                </>
              )}
              <dt style={dtStyle}>Poll interval</dt><dd style={{ margin: 0 }}>{pollIntervalSeconds} seconds</dd>
            </dl>
          </section>
        )}

        {error && <div role="alert" style={errorStyle}>{error}</div>}

        <footer style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
          <button type="button" onClick={onClose} disabled={busy} style={btnStyle}>Cancel</button>
          {stepIndex > 0 && <button type="button" onClick={() => setStepIndex((i) => i - 1)} disabled={busy} style={btnStyle}>Back</button>}
          {stepIndex < steps.length - 1 ? (
            <button type="button" onClick={() => setStepIndex((i) => i + 1)} disabled={!isValid() || busy} style={primaryBtnStyle}>Next</button>
          ) : (
            <button type="button" onClick={() => void submit()} disabled={busy} style={primaryBtnStyle}>{busy ? 'Enabling…' : 'Enable'}</button>
          )}
        </footer>
      </div>
    </div>
  );
}

const backdropStyle: React.CSSProperties = { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 };
const modalStyle: React.CSSProperties = { background: '#fff', borderRadius: 8, padding: 20, width: 'min(620px, 92vw)', maxHeight: '92vh', overflow: 'auto', display: 'flex', flexDirection: 'column', gap: 12 };
const stepperStyle: React.CSSProperties = { display: 'flex', gap: 8, listStyle: 'none', padding: 0, margin: '8px 0 0', fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.05em' };
const stepIdleStyle: React.CSSProperties = { padding: '2px 8px', borderRadius: 4, background: '#f3f4f6', color: '#6b7280' };
const stepActiveStyle: React.CSSProperties = { padding: '2px 8px', borderRadius: 4, background: '#1d4ed8', color: '#fff' };
const stepDoneStyle: React.CSSProperties = { padding: '2px 8px', borderRadius: 4, background: '#d1fae5', color: '#065f46' };
const hintStyle: React.CSSProperties = { margin: '4px 0 0', color: '#4b5563', fontSize: 12 };
const radioCardStyle: React.CSSProperties = { display: 'flex', gap: 8, alignItems: 'flex-start', padding: 8, border: '1px solid #e5e7eb', borderRadius: 8, cursor: 'pointer', fontSize: 14, flex: '0 0 auto' };
const previewStyle: React.CSSProperties = { margin: '4px 0 0', padding: 8, background: '#f9fafb', borderRadius: 4, fontFamily: 'ui-monospace, SFMono-Regular, monospace', fontSize: 12, whiteSpace: 'pre-wrap' };
const inputStyle: React.CSSProperties = { padding: '6px 8px', border: '1px solid #d1d5db', borderRadius: 4, fontSize: 14 };
const btnStyle: React.CSSProperties = { padding: '6px 12px', border: '1px solid #d1d5db', borderRadius: 4, background: '#fff', cursor: 'pointer', fontSize: 14 };
const primaryBtnStyle: React.CSSProperties = { ...btnStyle, background: '#1d4ed8', color: '#fff', borderColor: '#1d4ed8' };
const chipStyle: React.CSSProperties = { display: 'inline-flex', alignItems: 'center', gap: 4, padding: '1px 6px', background: '#f3f4f6', border: '1px solid #e5e7eb', borderRadius: 4, fontSize: 12 };
const errorStyle: React.CSSProperties = { background: '#fef2f2', color: '#b91c1c', border: '1px solid #fecaca', borderRadius: 4, padding: '8px 12px', fontSize: 14 };
const mutedStyle: React.CSSProperties = { color: '#6b7280' };
const dtStyle: React.CSSProperties = { color: '#6b7280', fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.05em', alignSelf: 'center' };

// apps/web/src/lib/components/data-connection/CreateAutoRegistrationModal.svelte
<script lang="ts">
  /**
   * 5-step wizard for `POST /v1/sources/{rid}/auto-registration`.
   *
   * Foundry doc § "Auto-registration" (img_005, img_006). The
   * Databricks tag-filter step is gated on provider so non-Databricks
   * sources skip it (the doc only blesses tag filtering for
   * Databricks).
   */
  import {
    virtualTables,
    type EnableAutoRegistrationRequest,
    type FolderMirrorKind,
    type VirtualTableProvider,
    type VirtualTableSourceLink,
  } from '$lib/api/virtual-tables';

  type Props = {
    open: boolean;
    sourceRid: string;
    provider: VirtualTableProvider;
    onClose: () => void;
    onEnabled?: (link: VirtualTableSourceLink) => void;
  };

  let { open, sourceRid, provider, onClose, onEnabled }: Props = $props();

  type StepId = 'project' | 'layout' | 'tags' | 'interval' | 'review';

  const steps: StepId[] = $derived(
    provider === 'DATABRICKS'
      ? (['project', 'layout', 'tags', 'interval', 'review'] as const).slice()
      : (['project', 'layout', 'interval', 'review'] as const).slice(),
  );

  let stepIndex = $state(0);
  let projectName = $state('');
  let layout = $state<FolderMirrorKind>('NESTED');
  let tagFilters = $state<string[]>([]);
  let tagDraft = $state('');
  let pollIntervalSeconds = $state(3600);
  let busy = $state(false);
  let error = $state('');

  const POLL_OPTIONS = [
    { label: '15 minutes', value: 900 },
    { label: '1 hour', value: 3600 },
    { label: '6 hours', value: 21600 },
    { label: '24 hours', value: 86400 },
  ];

  function currentStep(): StepId {
    return steps[Math.min(stepIndex, steps.length - 1)] ?? 'review';
  }

  function next() {
    if (stepIndex < steps.length - 1) stepIndex += 1;
  }

  function back() {
    if (stepIndex > 0) stepIndex -= 1;
  }

  function addTag() {
    const t = tagDraft.trim();
    if (!t) return;
    if (!tagFilters.includes(t)) tagFilters = [...tagFilters, t];
    tagDraft = '';
  }

  function removeTag(tag: string) {
    tagFilters = tagFilters.filter((t) => t !== tag);
  }

  function isStepValid(): boolean {
    switch (currentStep()) {
      case 'project':
        return projectName.trim().length > 0;
      case 'layout':
        return layout === 'FLAT' || layout === 'NESTED';
      case 'tags':
        return true; // tags optional
      case 'interval':
        return pollIntervalSeconds >= 60;
      case 'review':
        return true;
    }
  }

  async function submit() {
    busy = true;
    error = '';
    const body: EnableAutoRegistrationRequest = {
      project_name: projectName.trim(),
      folder_mirror_kind: layout,
      table_tag_filters: provider === 'DATABRICKS' ? tagFilters : [],
      poll_interval_seconds: pollIntervalSeconds,
    };
    try {
      const link = await virtualTables.enableAutoRegistration(sourceRid, body);
      onEnabled?.(link);
      onClose();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to enable auto-registration';
    } finally {
      busy = false;
    }
  }
</script>

{#if open}
  <div class="backdrop" role="dialog" aria-modal="true" data-testid="vt-auto-reg-wizard">
    <div class="modal">
      <header>
        <h3>Enable auto-registration</h3>
        <p class="muted">
          Step {stepIndex + 1} of {steps.length} ·
          <span class="step-name">{currentStep().replace('-', ' ')}</span>
        </p>
        <ol class="stepper">
          {#each steps as id, i (id)}
            <li class={i === stepIndex ? 'active' : i < stepIndex ? 'done' : ''}>
              {id}
            </li>
          {/each}
        </ol>
      </header>

      {#if currentStep() === 'project'}
        <section>
          <label>
            <span>Foundry-managed project name</span>
            <input
              type="text"
              bind:value={projectName}
              placeholder="warehouse mirror"
              data-testid="vt-auto-reg-project-name"
            />
          </label>
          <p class="hint">
            A new project will be created and managed by
            <code>virtual-table-service</code>. Users cannot create or
            modify resources in it directly.
          </p>
        </section>
      {:else if currentStep() === 'layout'}
        <section class="layout-pick">
          <label class="radio" data-testid="vt-auto-reg-layout-nested">
            <input type="radio" bind:group={layout} value={'NESTED'} />
            <div>
              <strong>Nested</strong>
              <p class="hint">
                <code>{'<project>/<database>/<schema>/<table>'}</code>
              </p>
              <pre class="preview">main
└── public
    └── orders</pre>
            </div>
          </label>
          <label class="radio" data-testid="vt-auto-reg-layout-flat">
            <input type="radio" bind:group={layout} value={'FLAT'} />
            <div>
              <strong>Flat</strong>
              <p class="hint">
                <code>{'<project>/<database>__<schema>__<table>'}</code>
              </p>
              <pre class="preview">main__public__orders</pre>
            </div>
          </label>
        </section>
      {:else if currentStep() === 'tags'}
        <section>
          <p class="hint">
            Only Databricks tables tagged with at least one of these
            tags will be auto-registered. Reads
            <code>INFORMATION_SCHEMA.TABLE_TAGS</code> on the
            workspace metastore.
          </p>
          <div class="tag-input">
            <input
              type="text"
              placeholder="gold, pii, certified…"
              bind:value={tagDraft}
              onkeydown={(e) => e.key === 'Enter' && (e.preventDefault(), addTag())}
              data-testid="vt-auto-reg-tag-input"
            />
            <button type="button" onclick={addTag}>Add</button>
          </div>
          <ul class="chips" data-testid="vt-auto-reg-tag-chips">
            {#each tagFilters as tag (tag)}
              <li class="chip">
                {tag}
                <button type="button" onclick={() => removeTag(tag)} aria-label={`Remove ${tag}`}>
                  ✕
                </button>
              </li>
            {/each}
          </ul>
        </section>
      {:else if currentStep() === 'interval'}
        <section>
          <p class="hint">
            How often the scanner re-runs against the source. Per
            Foundry doc the recommendation is 1 hour — too short
            costs compute, too long delays new-table discovery.
          </p>
          <div class="interval-row">
            {#each POLL_OPTIONS as opt (opt.value)}
              <label class="radio">
                <input
                  type="radio"
                  bind:group={pollIntervalSeconds}
                  value={opt.value}
                />
                {opt.label}
              </label>
            {/each}
            <label class="radio custom">
              <input
                type="number"
                min="60"
                bind:value={pollIntervalSeconds}
                data-testid="vt-auto-reg-interval-custom"
              />
              <span>seconds</span>
            </label>
          </div>
        </section>
      {:else if currentStep() === 'review'}
        <section class="review">
          <dl>
            <dt>Project</dt>
            <dd>{projectName}</dd>
            <dt>Layout</dt>
            <dd>{layout}</dd>
            {#if provider === 'DATABRICKS'}
              <dt>Tag filters</dt>
              <dd>
                {#if tagFilters.length === 0}
                  <span class="muted">none — every accessible table is mirrored</span>
                {:else}
                  {tagFilters.join(', ')}
                {/if}
              </dd>
            {/if}
            <dt>Poll interval</dt>
            <dd>{pollIntervalSeconds} seconds</dd>
          </dl>
        </section>
      {/if}

      {#if error}
        <div class="error" role="alert">{error}</div>
      {/if}

      <footer>
        <button type="button" onclick={onClose} disabled={busy}>Cancel</button>
        {#if stepIndex > 0}
          <button type="button" onclick={back} disabled={busy}>Back</button>
        {/if}
        {#if stepIndex < steps.length - 1}
          <button
            type="button"
            class="primary"
            onclick={next}
            disabled={!isStepValid() || busy}
            data-testid="vt-auto-reg-next"
          >
            Next
          </button>
        {:else}
          <button
            type="button"
            class="primary"
            onclick={submit}
            disabled={busy}
            data-testid="vt-auto-reg-submit"
          >
            {busy ? 'Enabling…' : 'Enable'}
          </button>
        {/if}
      </footer>
    </div>
  </div>
{/if}

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.4);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;
  }
  .modal {
    background: var(--color-bg-elevated, #fff);
    border-radius: 0.5rem;
    padding: 1.25rem;
    width: min(620px, 92vw);
    max-height: 92vh;
    overflow: auto;
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }
  header h3 {
    margin: 0 0 0.25rem;
  }
  .stepper {
    display: flex;
    gap: 0.5rem;
    list-style: none;
    padding: 0;
    margin: 0.5rem 0 0;
    font-size: 0.625rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }
  .stepper li {
    padding: 0.125rem 0.5rem;
    border-radius: 0.25rem;
    background: var(--color-bg-subtle, #f3f4f6);
    color: var(--color-fg-muted, #6b7280);
  }
  .stepper li.active {
    background: #1d4ed8;
    color: #fff;
  }
  .stepper li.done {
    background: #d1fae5;
    color: #065f46;
  }
  .step-name {
    text-transform: capitalize;
  }
  .hint {
    margin: 0.25rem 0 0;
    color: var(--color-fg-muted, #4b5563);
    font-size: 0.75rem;
  }
  .layout-pick {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 0.75rem;
  }
  .radio {
    display: flex;
    gap: 0.5rem;
    align-items: flex-start;
    padding: 0.5rem;
    border: 1px solid var(--color-border, #e5e7eb);
    border-radius: 0.5rem;
    cursor: pointer;
    font-size: 0.875rem;
  }
  .radio input[type='radio'] {
    margin-top: 0.25rem;
  }
  .radio.custom {
    flex-direction: row;
    align-items: center;
  }
  .radio.custom input[type='number'] {
    width: 8rem;
    padding: 0.25rem 0.5rem;
    border: 1px solid var(--color-border, #d1d5db);
    border-radius: 0.25rem;
  }
  .preview {
    margin: 0.25rem 0 0;
    padding: 0.5rem;
    background: var(--color-bg-subtle, #f9fafb);
    border-radius: 0.25rem;
    font-family: ui-monospace, SFMono-Regular, monospace;
    font-size: 0.75rem;
  }
  .tag-input {
    display: flex;
    gap: 0.5rem;
  }
  .tag-input input {
    flex: 1;
    padding: 0.375rem 0.5rem;
    border: 1px solid var(--color-border, #d1d5db);
    border-radius: 0.25rem;
    font-size: 0.875rem;
  }
  .tag-input button {
    padding: 0.375rem 0.75rem;
    border-radius: 0.25rem;
    border: 1px solid var(--color-border, #d1d5db);
    background: var(--color-bg-elevated, #fff);
    font-size: 0.875rem;
    cursor: pointer;
  }
  .chips {
    display: flex;
    flex-wrap: wrap;
    gap: 0.25rem;
    list-style: none;
    padding: 0;
    margin: 0.5rem 0 0;
  }
  .chip {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
    padding: 0.0625rem 0.375rem;
    background: var(--color-bg-subtle, #f3f4f6);
    border: 1px solid var(--color-border, #e5e7eb);
    border-radius: 0.25rem;
    font-size: 0.75rem;
  }
  .chip button {
    border: none;
    background: transparent;
    cursor: pointer;
    color: #b91c1c;
    font-size: 0.75rem;
  }
  .interval-row {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
  }
  .interval-row .radio {
    flex: 0 0 auto;
  }
  .review dl {
    display: grid;
    grid-template-columns: max-content 1fr;
    gap: 0.25rem 0.75rem;
    margin: 0;
    font-size: 0.875rem;
  }
  .review dt {
    color: var(--color-fg-muted, #6b7280);
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    align-self: center;
  }
  .review dd {
    margin: 0;
  }
  .muted {
    color: var(--color-fg-muted, #6b7280);
  }
  .error {
    background: #fef2f2;
    color: #b91c1c;
    border: 1px solid #fecaca;
    border-radius: 0.25rem;
    padding: 0.5rem 0.75rem;
    font-size: 0.875rem;
  }
  footer {
    display: flex;
    gap: 0.5rem;
    justify-content: flex-end;
  }
  footer button {
    padding: 0.375rem 0.75rem;
    border: 1px solid var(--color-border, #d1d5db);
    border-radius: 0.25rem;
    background: var(--color-bg-elevated, #fff);
    cursor: pointer;
    font-size: 0.875rem;
  }
  footer button.primary {
    background: #1d4ed8;
    color: #fff;
    border-color: #1d4ed8;
  }
  footer button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>
