// apps/web/src/lib/components/streaming/StreamLiveDataView.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import { previewStream, type PreviewRow } from '$lib/api/streaming';

	export let streamId: string;

	type Mode = 'live' | 'recent' | 'historical';
	let mode: Mode = 'live';
	let limit = 50;
	let rows: PreviewRow[] = [];
	let aggregateSource: 'hot' | 'cold' | 'hybrid' = 'hot';
	let error = '';
	let loading = false;

	let pollTimer: ReturnType<typeof setInterval> | null = null;
	let socket: WebSocket | null = null;

	function modeToServerMode(m: Mode): 'oldest' | 'hot_only' | 'cold_only' {
		switch (m) {
			case 'live':
				return 'hot_only';
			case 'recent':
				return 'oldest';
			case 'historical':
				return 'cold_only';
		}
	}

	async function refresh() {
		loading = true;
		error = '';
		try {
			const res = await previewStream(streamId, {
				mode: modeToServerMode(mode),
				limit
			});
			rows = res.data;
			aggregateSource = res.source;
		} catch (err) {
			error = err instanceof Error ? err.message : String(err);
		} finally {
			loading = false;
		}
	}

	function openWebSocket() {
		closeWebSocket();
		try {
			const proto = typeof window !== 'undefined' && window.location.protocol === 'https:' ? 'wss' : 'ws';
			const host = typeof window !== 'undefined' ? window.location.host : '';
			socket = new WebSocket(
				`${proto}://${host}/api/v1/streaming/streams/${streamId}/live`
			);
			socket.onmessage = (ev) => {
				try {
					const incoming = JSON.parse(ev.data) as PreviewRow;
					const tagged: PreviewRow = { ...incoming, source: 'hot' };
					rows = [tagged, ...rows].slice(0, limit);
					aggregateSource = 'hot';
				} catch (err) {
					console.warn('live frame parse failed', err);
				}
			};
			socket.onerror = (ev) => {
				console.warn('live socket error', ev);
			};
		} catch (err) {
			console.warn('live socket open failed', err);
		}
	}

	function closeWebSocket() {
		if (socket) {
			try {
				socket.close();
			} catch {
				/* swallow */
			}
			socket = null;
		}
	}

	function startPolling() {
		stopPolling();
		// Polling fallback for the Recent tab and as a complement to
		// the Live socket (the proxy may not be deployed in dev).
		pollTimer = setInterval(refresh, mode === 'live' ? 5_000 : 15_000);
	}

	function stopPolling() {
		if (pollTimer) {
			clearInterval(pollTimer);
			pollTimer = null;
		}
	}

	function setMode(next: Mode) {
		mode = next;
		closeWebSocket();
		stopPolling();
		refresh();
		if (mode === 'live') {
			openWebSocket();
			startPolling();
		} else if (mode === 'recent') {
			startPolling();
		}
	}

	onMount(() => {
		setMode('live');
	});

	onDestroy(() => {
		closeWebSocket();
		stopPolling();
	});

	function badgeClass(source: 'hot' | 'cold'): string {
		return source === 'hot' ? 'live' : 'archived';
	}

	function badgeLabel(source: 'hot' | 'cold'): string {
		return source === 'hot' ? 'live' : 'archived';
	}
</script>

<section class="stream-live-data" data-testid="stream-live-data">
	<div class="toggle-row" role="tablist" aria-label="View mode">
		<button
			type="button"
			role="tab"
			class:active={mode === 'live'}
			on:click={() => setMode('live')}
			data-testid="view-live"
		>Live</button>
		<button
			type="button"
			role="tab"
			class:active={mode === 'recent'}
			on:click={() => setMode('recent')}
			data-testid="view-recent"
		>Recent</button>
		<button
			type="button"
			role="tab"
			class:active={mode === 'historical'}
			on:click={() => setMode('historical')}
			data-testid="view-historical"
		>Historical</button>
		<span class="aggregate-source" data-testid="aggregate-source">
			source: <strong>{aggregateSource}</strong>
		</span>
	</div>

	{#if error}<p class="error">{error}</p>{/if}
	{#if loading && rows.length === 0}
		<p class="hint">Loading…</p>
	{/if}

	<table data-testid="preview-table">
		<thead>
			<tr><th>Time</th><th>Sequence</th><th>Source</th><th>Payload</th></tr>
		</thead>
		<tbody>
			{#each rows as row, idx (idx)}
				<tr>
					<td>{new Date(row.event_time).toLocaleString()}</td>
					<td>{row.sequence_no ?? '—'}</td>
					<td>
						<span
							class="badge {badgeClass(row.source)}"
							data-testid={`row-badge-${row.source}`}
						>
							{badgeLabel(row.source)}
						</span>
					</td>
					<td>
						<pre>{JSON.stringify(row.payload, null, 2)}</pre>
					</td>
				</tr>
			{:else}
				<tr><td colspan="4" class="hint">No records.</td></tr>
			{/each}
		</tbody>
	</table>
</section>

<style>
	.stream-live-data { display: grid; gap: 0.75rem; }
	.toggle-row { display: flex; gap: 0.4rem; align-items: center; }
	.toggle-row button {
		background: #f3f4f6; border: 1px solid #ddd; border-radius: 4px;
		padding: 0.25rem 0.65rem; cursor: pointer; font-size: 0.85rem;
	}
	.toggle-row button.active { background: #246; color: #fff; border-color: #246; }
	.aggregate-source { margin-left: auto; font-size: 0.8rem; color: #555; }
	table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
	th, td { text-align: left; padding: 0.35rem 0.6rem; border-bottom: 1px solid #eee; vertical-align: top; }
	pre { margin: 0; white-space: pre-wrap; font-family: ui-monospace, monospace; }
	.badge { padding: 0.05rem 0.45rem; border-radius: 3px; font-size: 0.7rem; font-weight: 600; }
	.badge.live { background: #d4f4dd; color: #1f5631; }
	.badge.archived { background: #e5e7eb; color: #4b5563; }
	.error { color: #b00; }
	.hint { color: #666; }
</style>

// apps/web/src/lib/components/streaming/StreamLiveDataView.tsx
import { useEffect, useRef, useState } from 'react';

import { previewStream, type PreviewRow } from '@/lib/api/streaming';

interface Props {
  streamId: string;
}

type Mode = 'live' | 'recent' | 'historical';

function modeToServerMode(m: Mode): 'oldest' | 'hot_only' | 'cold_only' {
  if (m === 'live') return 'hot_only';
  if (m === 'recent') return 'oldest';
  return 'cold_only';
}

const BADGE_LIVE: React.CSSProperties = { background: '#d4f4dd', color: '#1f5631' };
const BADGE_ARCHIVED: React.CSSProperties = { background: '#e5e7eb', color: '#4b5563' };

export function StreamLiveDataView({ streamId }: Props) {
  const [mode, setMode] = useState<Mode>('live');
  const [limit] = useState(50);
  const [rows, setRows] = useState<PreviewRow[]>([]);
  const [aggregateSource, setAggregateSource] = useState<'hot' | 'cold' | 'hybrid'>('hot');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const socketRef = useRef<WebSocket | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  async function refresh(currentMode: Mode) {
    setLoading(true);
    setError('');
    try {
      const res = await previewStream(streamId, { mode: modeToServerMode(currentMode), limit });
      setRows(res.data);
      setAggregateSource(res.source);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setLoading(false);
    }
  }

  function closeSocket() {
    if (socketRef.current) {
      try { socketRef.current.close(); } catch { /* swallow */ }
      socketRef.current = null;
    }
  }

  function stopPolling() {
    if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
  }

  function openSocket() {
    closeSocket();
    try {
      const proto = window.location.protocol === 'https:' ? 'wss' : 'ws';
      const host = window.location.host;
      const sock = new WebSocket(`${proto}://${host}/api/v1/streaming/streams/${streamId}/live`);
      sock.onmessage = (ev) => {
        try {
          const incoming = JSON.parse(ev.data) as PreviewRow;
          const tagged: PreviewRow = { ...incoming, source: 'hot' };
          setRows((prev) => [tagged, ...prev].slice(0, limit));
          setAggregateSource('hot');
        } catch (err) {
          console.warn('live frame parse failed', err);
        }
      };
      sock.onerror = (ev) => { console.warn('live socket error', ev); };
      socketRef.current = sock;
    } catch (err) {
      console.warn('live socket open failed', err);
    }
  }

  useEffect(() => {
    closeSocket();
    stopPolling();
    void refresh(mode);
    if (mode === 'live') {
      openSocket();
      pollRef.current = setInterval(() => void refresh(mode), 5_000);
    } else if (mode === 'recent') {
      pollRef.current = setInterval(() => void refresh(mode), 15_000);
    }
    return () => { closeSocket(); stopPolling(); };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode, streamId]);

  return (
    <section style={{ display: 'grid', gap: 12 }}>
      <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
        {(['live', 'recent', 'historical'] as Mode[]).map((m) => (
          <button
            key={m}
            type="button"
            onClick={() => setMode(m)}
            style={{ background: mode === m ? '#246' : '#f3f4f6', color: mode === m ? '#fff' : 'inherit', border: '1px solid #ddd', borderRadius: 4, padding: '4px 10px', cursor: 'pointer', fontSize: 13, textTransform: 'capitalize' }}
          >
            {m}
          </button>
        ))}
        <span style={{ marginLeft: 'auto', fontSize: 12, color: '#555' }}>
          source: <strong>{aggregateSource}</strong>
        </span>
      </div>

      {error && <p style={{ color: '#b00' }}>{error}</p>}
      {loading && rows.length === 0 && <p style={{ color: '#666' }}>Loading…</p>}

      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
        <thead>
          <tr><th style={{ textAlign: 'left', padding: '6px 10px', borderBottom: '1px solid #eee' }}>Time</th><th style={{ textAlign: 'left', padding: '6px 10px', borderBottom: '1px solid #eee' }}>Sequence</th><th style={{ textAlign: 'left', padding: '6px 10px', borderBottom: '1px solid #eee' }}>Source</th><th style={{ textAlign: 'left', padding: '6px 10px', borderBottom: '1px solid #eee' }}>Payload</th></tr>
        </thead>
        <tbody>
          {rows.length === 0 ? (
            <tr><td colSpan={4} style={{ color: '#666', padding: '6px 10px' }}>No records.</td></tr>
          ) : (
            rows.map((row, idx) => (
              <tr key={idx}>
                <td style={{ padding: '6px 10px', borderBottom: '1px solid #eee', verticalAlign: 'top' }}>{new Date(row.event_time).toLocaleString()}</td>
                <td style={{ padding: '6px 10px', borderBottom: '1px solid #eee', verticalAlign: 'top' }}>{row.sequence_no ?? '—'}</td>
                <td style={{ padding: '6px 10px', borderBottom: '1px solid #eee', verticalAlign: 'top' }}>
                  <span style={{ padding: '1px 8px', borderRadius: 3, fontSize: 11, fontWeight: 600, ...(row.source === 'hot' ? BADGE_LIVE : BADGE_ARCHIVED) }}>
                    {row.source === 'hot' ? 'live' : 'archived'}
                  </span>
                </td>
                <td style={{ padding: '6px 10px', borderBottom: '1px solid #eee', verticalAlign: 'top' }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontFamily: 'ui-monospace, monospace' }}>{JSON.stringify(row.payload, null, 2)}</pre>
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>
    </section>
  );
}
