// apps/web/src/lib/components/Sidebar.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';

import { useTranslator } from '@/lib/i18n/store';
import { Glyph, type GlyphName } from './ui/Glyph';

interface NavItem {
  to: string;
  label: string;
  icon: GlyphName;
  shortcut?: string;
  dot?: boolean;
  end?: boolean;
  iconTone?: string;
}

interface PinnedApp extends NavItem {
  iconTone: string;
}

interface CategoryDef {
  id: string;
  label: string;
  isHeading?: boolean;
}

interface LauncherApp {
  id: string;
  href: string;
  name: string;
  description: string;
  icon: GlyphName;
  iconTone: string;
  category: string;
  promoted?: boolean;
}

const COLLAPSED_KEY = 'of_sidebar_collapsed';

const PRIMARY_NAV: NavItem[] = [
  { to: '/', label: 'Home', icon: 'home', end: true },
  { to: '/search', label: 'Search', icon: 'search', shortcut: 'ctrl + J' },
  { to: '/notifications', label: 'Notifications', icon: 'bell', dot: true },
  { to: '/whats-new', label: "What's New", icon: 'sparkles', dot: true },
];

const SECONDARY_NAV: NavItem[] = [
  { to: '/recent', label: 'Recent', icon: 'history' },
  { to: '/projects', label: 'Files', icon: 'folder' },
];

const PINNED_APPS: PinnedApp[] = [
  { to: '/apps', label: 'Workshop', icon: 'app', iconTone: '#a78bfa' },
];

const FOOTER_NAV: NavItem[] = [
  { to: '/ai', label: 'AIP Assist', icon: 'asterisk', shortcut: 'ctrl + shift + U', iconTone: '#67e8f9' },
  { to: '/developers', label: 'Support', icon: 'help' },
  { to: '/settings', label: 'Account', icon: 'users' },
];

const CATEGORIES: CategoryDef[] = [
  { id: 'all', label: 'All apps' },
  { id: '__platform', label: 'PLATFORM APPS', isHeading: true },
  { id: 'administration', label: 'Administration' },
  { id: 'analytics-operations', label: 'Analytics & Operations' },
  { id: 'application-development', label: 'Application development' },
  { id: 'data-integration', label: 'Data integration' },
  { id: 'developer-toolchain', label: 'Developer toolchain' },
  { id: 'models', label: 'Models' },
  { id: 'ontology', label: 'Ontology' },
  { id: 'security-governance', label: 'Security & governance' },
  { id: 'support', label: 'Support' },
];

const LAUNCHER_APPS: LauncherApp[] = [
  // Administration
  { id: 'control-panel', href: '/control-panel', icon: 'settings', iconTone: '#60a5fa', category: 'administration',
    name: 'Control Panel',
    description: 'Manage critical platform operations for an enrollment or organization.' },
  { id: 'resource-management', href: '/control-panel/data-health', icon: 'pie-chart', iconTone: '#34d399', category: 'administration',
    name: 'Resource Management',
    description: 'Track and manage costs, budgets, resource queues and usage limits across Foundry.' },
  { id: 'upgrade-assistant', href: '/control-panel/streaming-profiles', icon: 'badge-check', iconTone: '#fbbf24', category: 'administration',
    name: 'Upgrade Assistant',
    description: 'Track important platform updates and changes affecting the platform.' },

  // Analytics & Operations
  { id: 'contour', href: '/contour', icon: 'graph', iconTone: '#fb923c', category: 'analytics-operations',
    name: 'Contour',
    description: 'Analyze large datasets with filters, joins, and visualizations. Export the result to contribute back to the Foundry pipeline.' },
  { id: 'fusion', href: '/fusion', icon: 'spreadsheet', iconTone: '#22c55e', category: 'analytics-operations',
    name: 'Fusion',
    description: 'Interact with live Foundry data in a familiar spreadsheet interface.' },
  { id: 'map', href: '/geospatial', icon: 'view-grid', iconTone: '#4ade80', category: 'analytics-operations',
    name: 'Map',
    description: 'Analyze geospatial and geotemporal data.' },
  { id: 'notepad', href: '/notepad', icon: 'document', iconTone: '#f472b6', category: 'analytics-operations',
    name: 'Notepad',
    description: 'Create, share and export object-aware documents and reports.' },
  { id: 'quiver', href: '/quiver', icon: 'graph', iconTone: '#a78bfa', category: 'analytics-operations',
    name: 'Quiver',
    description: 'Visualize, analyze, and build interactive dashboards from object and time series data using a point-and-click environment.' },
  { id: 'vertex', href: '/vertex', icon: 'project', iconTone: '#22d3ee', category: 'analytics-operations',
    name: 'Vertex',
    description: 'Explore object graphs and system diagrams.' },

  // Application development
  { id: 'workshop', href: '/apps', icon: 'app', iconTone: '#a78bfa', category: 'application-development', promoted: true,
    name: 'Workshop',
    description: 'Build operational apps with widgets, templates, runtime previews, and publishing.' },
  { id: 'apps-marketplace', href: '/marketplace', icon: 'cube', iconTone: '#60a5fa', category: 'application-development',
    name: 'Marketplace',
    description: 'Discover internal packages, release channels, and one-click rollout bundles.' },
  { id: 'object-views', href: '/object-views', icon: 'object', iconTone: '#fb923c', category: 'application-development',
    name: 'Object Views',
    description: 'Configure operational record views, related lists, and quick actions.' },
  { id: 'workflows', href: '/workflows', icon: 'graph', iconTone: '#4ade80', category: 'application-development',
    name: 'Workflows',
    description: 'Author multi-step automations and orchestration logic.' },
  { id: 'reports', href: '/reports', icon: 'document', iconTone: '#f472b6', category: 'application-development',
    name: 'Reports',
    description: 'Compose narrative reports rendered from live ontology data.' },
  { id: 'dashboards', href: '/dashboards', icon: 'view-grid', iconTone: '#22d3ee', category: 'application-development',
    name: 'Dashboards',
    description: 'Operational KPIs, cohorts, and drill-down dashboards.' },
  { id: 'global-branching', href: '/global-branching', icon: 'asterisk', iconTone: '#facc15', category: 'application-development',
    name: 'Global Branching',
    description: 'Promote, review, and merge cross-app branches with policy.' },

  // Data integration
  { id: 'datasets', href: '/datasets', icon: 'database', iconTone: '#60a5fa', category: 'data-integration',
    name: 'Data Catalog',
    description: 'Search datasets by owner, tags, and quality status from one registry.' },
  { id: 'data-connection', href: '/data-connection', icon: 'link', iconTone: '#34d399', category: 'data-integration',
    name: 'Data Connection',
    description: 'Sync data from external systems via sources, egress policies, and batch syncs.' },
  { id: 'pipelines', href: '/pipelines', icon: 'graph', iconTone: '#a78bfa', category: 'data-integration',
    name: 'Pipeline Builder',
    description: 'Design and monitor operational pipelines, runs, and automation jobs.' },
  { id: 'builds', href: '/builds', icon: 'cube', iconTone: '#fb923c', category: 'data-integration',
    name: 'Builds',
    description: 'Inspect every build, drill into the job graph, follow live logs.' },
  { id: 'streaming', href: '/streaming', icon: 'graph', iconTone: '#22d3ee', category: 'data-integration',
    name: 'Streaming',
    description: 'Operate real-time topologies, windows, joins, and live event tails.' },
  { id: 'lineage', href: '/lineage', icon: 'graph', iconTone: '#f472b6', category: 'data-integration',
    name: 'Data Lineage',
    description: 'Inspect upstream and downstream dependencies across the data estate.' },
  { id: 'media-sets', href: '/media-sets', icon: 'image', iconTone: '#facc15', category: 'data-integration',
    name: 'Media Sets',
    description: 'Manage image, audio, and video collections with metadata.' },
  { id: 'iceberg-tables', href: '/iceberg-tables', icon: 'database', iconTone: '#4ade80', category: 'data-integration',
    name: 'Iceberg Tables',
    description: 'Provision and govern Iceberg-managed table assets.' },
  { id: 'virtual-tables', href: '/virtual-tables', icon: 'database', iconTone: '#60a5fa', category: 'data-integration',
    name: 'Virtual Tables',
    description: 'Federate external sources without copying data.' },
  { id: 'schedules', href: '/build-schedules', icon: 'history', iconTone: '#fbbf24', category: 'data-integration',
    name: 'Schedules',
    description: 'Cron and event-based schedules for builds and pipelines.' },
  { id: 'machinery', href: '/machinery', icon: 'cube', iconTone: '#a78bfa', category: 'data-integration',
    name: 'Machinery',
    description: 'Manage long-running infrastructure jobs and workers.' },
  { id: 'object-databases', href: '/object-databases', icon: 'database', iconTone: '#f472b6', category: 'data-integration',
    name: 'Object Databases',
    description: 'Configure object-store-backed databases.' },
  { id: 'ontology-indexing', href: '/ontology-indexing', icon: 'database', iconTone: '#22c55e', category: 'data-integration',
    name: 'Ontology Indexing',
    description: 'Index ontology objects for fast retrieval.' },
  { id: 'foundry-rules', href: '/foundry-rules', icon: 'shield', iconTone: '#fb923c', category: 'data-integration',
    name: 'Foundry Rules',
    description: 'Author rule-based automations and triggers.' },

  // Developer toolchain
  { id: 'code-repos', href: '/code-repos', icon: 'code', iconTone: '#22d3ee', category: 'developer-toolchain',
    name: 'Code Repositories',
    description: 'Browse repositories, reviews, CI gates, commits, and protected merge flows.' },
  { id: 'notebooks', href: '/notebooks', icon: 'code', iconTone: '#a78bfa', category: 'developer-toolchain',
    name: 'Workshop Notebooks',
    description: 'Develop notebook-based workflows, analyses, and collaborative experiments.' },
  { id: 'functions', href: '/functions', icon: 'code', iconTone: '#facc15', category: 'developer-toolchain',
    name: 'Functions',
    description: 'Author serverless functions invoked by workflows and apps.' },

  // Models
  { id: 'ai', href: '/ai', icon: 'sparkles', iconTone: '#a78bfa', category: 'models',
    name: 'AI Platform',
    description: 'Manage providers, prompts, guardrails, agents, and copilots from one control plane.' },
  { id: 'ml', href: '/ml', icon: 'sparkles', iconTone: '#60a5fa', category: 'models',
    name: 'ML Studio',
    description: 'Track experiments, training jobs, model versions, and online feature flows.' },
  { id: 'nexus', href: '/nexus', icon: 'sparkles', iconTone: '#22d3ee', category: 'models',
    name: 'Nexus',
    description: 'Connect knowledge sources to grounded LLM agents.' },
  { id: 'agents', href: '/ai', icon: 'sparkles', iconTone: '#34d399', category: 'models',
    name: 'Agents',
    description: 'Build, evaluate, and deploy autonomous reasoning agents.' },

  // Ontology
  { id: 'ontology-manager', href: '/ontology-manager', icon: 'ontology', iconTone: '#a78bfa', category: 'ontology',
    name: 'Ontology Manager',
    description: 'Shape core object models, semantics, and linked operational concepts.' },
  { id: 'object-explorer', href: '/object-explorer', icon: 'object', iconTone: '#fb923c', category: 'ontology',
    name: 'Object Explorer',
    description: 'Explore linked operational entities, activity, and related records.' },
  { id: 'action-types', href: '/action-types', icon: 'run', iconTone: '#22d3ee', category: 'ontology',
    name: 'Action Types',
    description: 'Author actions that mutate ontology objects with policy and audit.' },
  { id: 'object-link-types', href: '/object-link-types', icon: 'link', iconTone: '#34d399', category: 'ontology',
    name: 'Object Link Types',
    description: 'Define typed relationships between ontology objects.' },
  { id: 'interfaces', href: '/interfaces', icon: 'object', iconTone: '#facc15', category: 'ontology',
    name: 'Interfaces',
    description: 'Polymorphic interfaces over ontology object types.' },

  // Security & governance
  { id: 'audit', href: '/audit', icon: 'shield', iconTone: '#f472b6', category: 'security-governance',
    name: 'Governance Center',
    description: 'Review policies, approvals, applications, and governance templates.' },
  { id: 'object-monitors', href: '/object-monitors', icon: 'eye', iconTone: '#22d3ee', category: 'security-governance',
    name: 'Object Monitors',
    description: 'Watch for ontology drift and rule violations.' },
  { id: 'object-views-gov', href: '/object-views', icon: 'lock', iconTone: '#fb923c', category: 'security-governance',
    name: 'Access Reviews',
    description: 'Review user access and entitlement assignments.' },
  { id: 'shield-plus', href: '/audit', icon: 'shield-plus', iconTone: '#facc15', category: 'security-governance',
    name: 'Policy Engine',
    description: 'Author access policies enforced across the platform.' },
  { id: 'settings-gov', href: '/settings', icon: 'settings', iconTone: '#a78bfa', category: 'security-governance',
    name: 'Settings',
    description: 'Configure identity, language, security posture, and account defaults.' },

  // Support
  { id: 'help', href: '/developers', icon: 'help', iconTone: '#60a5fa', category: 'support',
    name: 'Help Center',
    description: 'Browse docs, guides, and platform tutorials.' },
  { id: 'tour', href: '/developers', icon: 'tour', iconTone: '#fbbf24', category: 'support',
    name: 'Product Tours',
    description: 'Guided walkthroughs for the most common workflows.' },
  { id: 'developers', href: '/developers', icon: 'code', iconTone: '#22d3ee', category: 'support',
    name: 'Developers',
    description: 'API references, SDK downloads and webhooks.' },
  { id: 'contact', href: '/developers', icon: 'email', iconTone: '#f472b6', category: 'support',
    name: 'Contact Support',
    description: 'Open a support ticket with the platform team.' },
];

function isActive(href: string, pathname: string, end?: boolean) {
  if (end) return pathname === href;
  return href === '/' ? pathname === '/' : pathname === href || pathname.startsWith(`${href}/`);
}

function readCollapsedPref(): boolean {
  if (typeof localStorage === 'undefined') return false;
  return localStorage.getItem(COLLAPSED_KEY) === '1';
}

interface SidebarLinkProps {
  item: NavItem;
  pathname: string;
  collapsed: boolean;
}

function SidebarLink({ item, pathname, collapsed }: SidebarLinkProps) {
  const active = isActive(item.to, pathname, item.end);
  return (
    <NavLink
      to={item.to}
      className={`of-sidebar__link${active ? ' of-sidebar__link--active' : ''}`}
      title={collapsed ? item.label : undefined}
      aria-label={item.label}
    >
      <span className="of-sidebar__icon" style={item.iconTone ? { color: item.iconTone } : undefined}>
        <Glyph name={item.icon} size={17} tone={item.iconTone ?? null} />
        {item.dot && <span className="of-sidebar__dot" aria-hidden="true" />}
      </span>
      <span className="of-sidebar__label">{item.label}</span>
      {item.shortcut && <span className="of-sidebar__hint">{item.shortcut}</span>}
    </NavLink>
  );
}

export function Sidebar() {
  const t = useTranslator();
  const { pathname } = useLocation();
  const [collapsed, setCollapsed] = useState<boolean>(() => readCollapsedPref());
  const [launcherOpen, setLauncherOpen] = useState(false);
  const [category, setCategory] = useState<string>('all');
  const [search, setSearch] = useState('');
  const [hoveredAppId, setHoveredAppId] = useState<string | null>(null);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const searchRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (typeof localStorage === 'undefined') return;
    localStorage.setItem(COLLAPSED_KEY, collapsed ? '1' : '0');
  }, [collapsed]);

  useEffect(() => {
    if (launcherOpen) searchRef.current?.focus();
  }, [launcherOpen]);

  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape' && launcherOpen) setLauncherOpen(false);
    }
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [launcherOpen]);

  const categoryCounts = useMemo(() => {
    const counts: Record<string, number> = { all: LAUNCHER_APPS.length };
    for (const c of CATEGORIES) {
      if (c.isHeading || c.id === 'all') continue;
      counts[c.id] = LAUNCHER_APPS.filter((a) => a.category === c.id).length;
    }
    return counts;
  }, []);

  const visibleApps = useMemo(() => {
    const term = search.trim().toLowerCase();
    return LAUNCHER_APPS.filter((app) => {
      if (category !== 'all' && app.category !== category) return false;
      if (!term) return true;
      return app.name.toLowerCase().includes(term) || app.description.toLowerCase().includes(term);
    });
  }, [search, category]);

  const groupedApps = useMemo(() => {
    const groups = new Map<string, LauncherApp[]>();
    for (const app of visibleApps) {
      if (!groups.has(app.category)) groups.set(app.category, []);
      groups.get(app.category)!.push(app);
    }
    const order = CATEGORIES.filter((c) => !c.isHeading && c.id !== 'all').map((c) => c.id);
    return order
      .filter((id) => groups.has(id))
      .map((id) => ({
        id,
        label: CATEGORIES.find((c) => c.id === id)?.label ?? id,
        apps: groups.get(id)!,
      }));
  }, [visibleApps]);

  const hoveredApp = useMemo(
    () => LAUNCHER_APPS.find((a) => a.id === hoveredAppId) ?? null,
    [hoveredAppId],
  );

  const promotedApps = useMemo(() => LAUNCHER_APPS.filter((a) => a.promoted), []);

  function openLauncher() {
    setSearch('');
    setCategory('all');
    setHoveredAppId(null);
    setFiltersOpen(false);
    setLauncherOpen(true);
  }

  return (
    <>
      <aside className="of-sidebar of-scrollbar" data-collapsed={collapsed || undefined}>
        <div className="of-sidebar__brand">
          <Link to="/" className="of-sidebar__logo" aria-label="OpenFoundry home" title="OpenFoundry">
            <img src="/empty-logo.png" alt="" width={20} height={20} style={{ display: 'block', objectFit: 'contain' }} />
          </Link>
          <button
            type="button"
            className="of-sidebar__collapse"
            aria-label={collapsed ? t('nav.expand') : t('nav.collapse')}
            aria-pressed={collapsed}
            onClick={() => setCollapsed((c) => !c)}
            title={collapsed ? t('nav.expand') : t('nav.collapse')}
          >
            <Glyph name={collapsed ? 'chevron-right' : 'chevron-left'} size={15} />
          </button>
        </div>

        <nav className="of-sidebar__nav" aria-label="Primary navigation">
          <section className="of-sidebar__section">
            {PRIMARY_NAV.map((item) => (
              <SidebarLink key={item.to} item={item} pathname={pathname} collapsed={collapsed} />
            ))}
          </section>

          <section className="of-sidebar__section">
            {SECONDARY_NAV.map((item) => (
              <SidebarLink key={item.to} item={item} pathname={pathname} collapsed={collapsed} />
            ))}
            <button
              type="button"
              className={`of-sidebar__link of-sidebar__link--button${launcherOpen ? ' of-sidebar__link--active' : ''}`}
              data-expanded={launcherOpen || undefined}
              aria-haspopup="dialog"
              aria-expanded={launcherOpen}
              onClick={() => (launcherOpen ? setLauncherOpen(false) : openLauncher())}
              title={collapsed ? 'Applications' : undefined}
            >
              <span className="of-sidebar__icon"><Glyph name="view-grid" size={17} /></span>
              <span className="of-sidebar__label">Applications</span>
            </button>
          </section>

          {PINNED_APPS.length > 0 && (
            <section className="of-sidebar__section">
              <div className="of-sidebar__heading">{t('nav.workshop.section')}</div>
              {PINNED_APPS.map((app) => (
                <SidebarLink key={app.to} item={app} pathname={pathname} collapsed={collapsed} />
              ))}
            </section>
          )}
        </nav>

        <section className="of-sidebar__section of-sidebar__section--footer">
          {FOOTER_NAV.map((item) => (
            <SidebarLink key={item.to} item={item} pathname={pathname} collapsed={collapsed} />
          ))}
        </section>
      </aside>

      {launcherOpen && (
        <div className="of-app-launcher" data-sidebar-collapsed={collapsed || undefined}>
          <button
            type="button"
            className="of-app-launcher__backdrop"
            aria-label="Close applications launcher"
            onClick={() => setLauncherOpen(false)}
          />
          <div className="of-app-launcher__surface" role="dialog" aria-modal="true" aria-label="Applications">
            <div className="of-app-launcher__header">
              <label className="of-app-launcher__search">
                <span className="of-app-launcher__search-icon"><Glyph name="search" size={14} /></span>
                <input
                  ref={searchRef}
                  type="search"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder="Search for applications…"
                  aria-label="Search applications"
                />
              </label>
              <button
                type="button"
                className={`of-app-launcher__filters${filtersOpen ? ' is-open' : ''}`}
                aria-pressed={filtersOpen}
                onClick={() => setFiltersOpen((v) => !v)}
              >
                <Glyph name="tag" size={13} />
                <span>{t('launcher.filters')}</span>
              </button>
              <button
                type="button"
                className="of-app-launcher__close"
                aria-label="Close applications launcher"
                onClick={() => setLauncherOpen(false)}
              >
                <Glyph name="x" size={14} />
              </button>
            </div>

            <div className="of-app-launcher__body">
              <div className="of-app-launcher__categories">
                {CATEGORIES.map((c) =>
                  c.isHeading ? (
                    <div key={c.id} className="of-app-launcher__category-heading">{c.label}</div>
                  ) : (
                    <button
                      key={c.id}
                      type="button"
                      className="of-app-launcher__category"
                      data-active={category === c.id || undefined}
                      onClick={() => setCategory(c.id)}
                    >
                      <span>{c.label}</span>
                      <span className="of-app-launcher__category-count">{categoryCounts[c.id] ?? 0}</span>
                    </button>
                  ),
                )}
                <div className="of-app-launcher__category-heading of-app-launcher__category-heading--inline">
                  PROMOTED APPS
                  <button type="button" className="of-app-launcher__promote-add">
                    <Glyph name="check" size={12} />
                    <span>Add</span>
                  </button>
                </div>
                {promotedApps.length === 0 && (
                  <div className="of-app-launcher__category-empty">No promoted apps</div>
                )}
                {promotedApps.map((app) => (
                  <Link
                    key={`promoted-${app.id}`}
                    to={app.href}
                    className="of-app-launcher__category"
                    onClick={() => setLauncherOpen(false)}
                  >
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
                      <Glyph name={app.icon} size={13} tone={app.iconTone} />
                      {app.name}
                    </span>
                  </Link>
                ))}
              </div>

              <div className="of-app-launcher__catalog">
                {visibleApps.length === 0 ? (
                  <div className="of-app-launcher__empty">No applications matched this search.</div>
                ) : (
                  groupedApps.map((group) => (
                    <div key={group.id} className="of-app-launcher__group">
                      <div className="of-app-launcher__group-title">{group.label}</div>
                      {group.apps.map((app) => (
                        <Link
                          key={app.id}
                          to={app.href}
                          className="of-app-launcher__item"
                          data-selected={hoveredAppId === app.id || undefined}
                          data-active={isActive(app.href, pathname) || undefined}
                          onMouseEnter={() => setHoveredAppId(app.id)}
                          onFocus={() => setHoveredAppId(app.id)}
                          onClick={() => setLauncherOpen(false)}
                        >
                          <span
                            className="of-app-launcher__item-icon"
                            style={{
                              background: `${app.iconTone}28`,
                              color: app.iconTone,
                            }}
                          >
                            <Glyph name={app.icon} size={16} tone={app.iconTone} />
                          </span>
                          <span className="of-app-launcher__item-copy">
                            <span className="of-app-launcher__item-name">{app.name}</span>
                            <span className="of-app-launcher__item-description">{app.description}</span>
                          </span>
                        </Link>
                      ))}
                    </div>
                  ))
                )}
              </div>

              <div className="of-app-launcher__detail">
                {hoveredApp ? (
                  <>
                    <div
                      className="of-app-launcher__detail-icon"
                      style={{
                        background: `${hoveredApp.iconTone}28`,
                        color: hoveredApp.iconTone,
                      }}
                    >
                      <Glyph name={hoveredApp.icon} size={20} tone={hoveredApp.iconTone} />
                    </div>
                    <div className="of-app-launcher__detail-copy">
                      <div className="of-app-launcher__detail-badge">
                        {CATEGORIES.find((c) => c.id === hoveredApp.category)?.label ?? ''}
                      </div>
                      <h2>{hoveredApp.name}</h2>
                      <p>{hoveredApp.description}</p>
                    </div>
                    <div className="of-app-launcher__actions">
                      <Link
                        to={hoveredApp.href}
                        className="of-app-launcher__button of-app-launcher__button--primary"
                        onClick={() => setLauncherOpen(false)}
                      >
                        Open
                      </Link>
                    </div>
                  </>
                ) : (
                  <div className="of-app-launcher__detail-empty">
                    <span className="of-app-launcher__detail-empty-icon" aria-hidden>
                      <Glyph name="cube" size={28} tone="rgba(255, 255, 255, 0.18)" />
                    </span>
                    <p>Hover on an application to see details</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// apps/web/src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import Glyph from '$components/ui/Glyph.svelte';
  import type { MessageKey } from '$lib/i18n/messages';
  import { createTranslator, currentLocale } from '$lib/i18n/store';

  const t = $derived.by(() => createTranslator($currentLocale));

  type NavIcon =
    | 'home'
    | 'search'
    | 'bell'
    | 'history'
    | 'folder'
    | 'cube'
    | 'database'
    | 'object'
    | 'ontology'
    | 'code'
    | 'graph'
    | 'help'
    | 'settings'
    | 'sparkles'
    | 'link';

  type NavItem = {
    href: string;
    labelKey: MessageKey;
    icon: NavIcon;
    hint?: string;
  };

  type LocalizedCopy = {
    en: string;
    es: string;
  };

  type LocaleKey = keyof LocalizedCopy;
  type LauncherText = {
    title: string;
    searchPlaceholder: string;
    close: string;
    open: string;
    createNew: string;
    browseCatalog: string;
    favorites: string;
    emptyFavorites: string;
    emptySearch: string;
    searchAriaLabel: string;
  };

  type LauncherCategoryId =
    | 'all'
    | 'platform'
    | 'administration'
    | 'development'
    | 'integration'
    | 'toolchain'
    | 'models'
    | 'ontology'
    | 'governance';

  type LauncherCategory = {
    id: LauncherCategoryId;
    label: LocalizedCopy;
  };

  type LauncherApp = {
    id: string;
    href: string;
    icon: NavIcon;
    name: LocalizedCopy;
    description: LocalizedCopy;
    badge: LocalizedCopy;
    // Keep 'all' first when present so the launcher can prefer the first specific bucket for selection.
    categoryIds: LauncherCategoryId[];
    createHref?: string;
    browseHref?: string;
  };

  const workspaceNav: NavItem[] = [
    { href: '/', labelKey: 'nav.home', icon: 'home' },
    { href: '/search', labelKey: 'nav.search', icon: 'search', hint: 'Ctrl + J' },
    { href: '/object-monitors', labelKey: 'nav.notifications', icon: 'bell' },
    { href: '/dashboards', labelKey: 'nav.recent', icon: 'history' },
    { href: '/projects', labelKey: 'nav.files', icon: 'folder' }
  ];

  const launcherCopy: Record<LocaleKey, LauncherText> = {
    en: {
      title: 'Applications',
      searchPlaceholder: 'Search for applications…',
      close: 'Close applications launcher',
      open: 'Open',
      createNew: 'Create new',
      browseCatalog: 'Browse catalog',
      favorites: 'Favorites & recents',
      emptyFavorites: 'No favorites or recents yet.',
      emptySearch: 'No applications matched this search.',
      searchAriaLabel: 'Search applications'
    },
    es: {
      title: 'Aplicaciones',
      searchPlaceholder: 'Buscar aplicaciones…',
      close: 'Cerrar lanzador de aplicaciones',
      open: 'Abrir',
      createNew: 'Crear nuevo',
      browseCatalog: 'Explorar catálogo',
      favorites: 'Favoritos y recientes',
      emptyFavorites: 'Todavía no hay favoritos ni recientes.',
      emptySearch: 'Ninguna aplicación coincide con esta búsqueda.',
      searchAriaLabel: 'Buscar aplicaciones'
    }
  } as const;

  const launcherCategories: LauncherCategory[] = [
    { id: 'all', label: { en: 'All apps', es: 'Todas las apps' } },
    { id: 'platform', label: { en: 'Platform apps', es: 'Apps de plataforma' } },
    { id: 'administration', label: { en: 'Administration', es: 'Administración' } },
    { id: 'development', label: { en: 'Application development', es: 'Desarrollo de aplicaciones' } },
    { id: 'integration', label: { en: 'Data integration', es: 'Integración de datos' } },
    { id: 'toolchain', label: { en: 'Developer toolchain', es: 'Toolchain de desarrollo' } },
    { id: 'models', label: { en: 'Models', es: 'Modelos' } },
    { id: 'ontology', label: { en: 'Ontology', es: 'Ontología' } },
    { id: 'governance', label: { en: 'Security & governance', es: 'Seguridad y gobierno' } }
  ];

  const launcherApps: LauncherApp[] = [
    {
      id: 'datasets',
      href: '/datasets',
      icon: 'database',
      name: { en: 'Data Catalog', es: 'Catálogo de datos' },
      description: {
        en: 'Search datasets by owner, tags, and quality status from one registry.',
        es: 'Busca datasets por propietario, etiquetas y estado de calidad desde un único registro.'
      },
      badge: { en: 'Data integration', es: 'Integración de datos' },
      categoryIds: ['all', 'platform', 'integration'],
      createHref: '/datasets/upload',
      browseHref: '/datasets'
    },
    {
      id: 'data-connection',
      href: '/data-connection',
      icon: 'link',
      name: { en: 'Data Connection', es: 'Data Connection' },
      description: {
        en: 'Sync data from external systems via sources, egress policies, and batch syncs.',
        es: 'Sincroniza datos de sistemas externos mediante sources, políticas de egress y batch syncs.'
      },
      badge: { en: 'Data integration', es: 'Integración de datos' },
      categoryIds: ['all', 'integration'],
      createHref: '/data-connection/new',
      browseHref: '/data-connection'
    },
    {
      id: 'pipelines',
      href: '/pipelines',
      icon: 'graph',
      name: { en: 'Pipeline Builder', es: 'Constructor de pipelines' },
      description: {
        en: 'Design and monitor operational pipelines, runs, and automation jobs.',
        es: 'Diseña y monitoriza pipelines operativos, ejecuciones y trabajos de automatización.'
      },
      badge: { en: 'Data integration', es: 'Integración de datos' },
      categoryIds: ['all', 'integration'],
      createHref: '/pipelines/new',
      browseHref: '/pipelines'
    },
    {
      id: 'lineage',
      href: '/lineage',
      icon: 'graph',
      name: { en: 'Data Lineage', es: 'Lineage de datos' },
      description: {
        en: 'Inspect upstream and downstream dependencies across the data estate.',
        es: 'Inspecciona dependencias upstream y downstream a través del patrimonio de datos.'
      },
      badge: { en: 'Ontology', es: 'Ontología' },
      categoryIds: ['all', 'integration', 'ontology'],
      browseHref: '/lineage'
    },
    {
      id: 'object-explorer',
      href: '/object-explorer',
      icon: 'object',
      name: { en: 'Object Explorer', es: 'Explorador de objetos' },
      description: {
        en: 'Explore linked operational entities, activity, and related records.',
        es: 'Explora entidades operativas vinculadas, actividad y registros relacionados.'
      },
      badge: { en: 'Platform app', es: 'App de plataforma' },
      categoryIds: ['all', 'platform', 'ontology'],
      browseHref: '/object-explorer'
    },
    {
      id: 'ontology-manager',
      href: '/ontology-manager',
      icon: 'ontology',
      name: { en: 'Ontology Manager', es: 'Gestor de ontología' },
      description: {
        en: 'Shape core object models, semantics, and linked operational concepts.',
        es: 'Modela objetos clave, semántica y conceptos operativos enlazados.'
      },
      badge: { en: 'Ontology', es: 'Ontología' },
      categoryIds: ['all', 'platform', 'ontology'],
      browseHref: '/ontology-manager'
    },
    {
      id: 'apps',
      href: '/apps',
      icon: 'cube',
      name: { en: 'Workshop App Builder', es: 'Workshop App Builder' },
      description: {
        en: 'Build internal applications with widgets, templates, runtime previews, and publishing.',
        es: 'Construye aplicaciones internas con widgets, plantillas, vista previa runtime y publicación.'
      },
      badge: { en: 'Application development', es: 'Desarrollo de aplicaciones' },
      categoryIds: ['all', 'development', 'toolchain'],
      createHref: '/apps',
      browseHref: '/apps'
    },
    {
      id: 'notebooks',
      href: '/notebooks',
      icon: 'code',
      name: { en: 'Workshop', es: 'Workshop' },
      description: {
        en: 'Develop notebook-based workflows, analyses, and collaborative experiments.',
        es: 'Desarrolla workflows basados en notebooks, análisis y experimentos colaborativos.'
      },
      badge: { en: 'Developer toolchain', es: 'Toolchain de desarrollo' },
      categoryIds: ['all', 'development', 'toolchain'],
      browseHref: '/notebooks'
    },
    {
      id: 'code-repos',
      href: '/code-repos',
      icon: 'code',
      name: { en: 'Code Repositories', es: 'Repositorios de código' },
      description: {
        en: 'Browse repositories, reviews, CI gates, commits, and protected merge flows.',
        es: 'Explora repositorios, revisiones, puertas CI, commits y flujos de merge protegidos.'
      },
      badge: { en: 'Developer toolchain', es: 'Toolchain de desarrollo' },
      categoryIds: ['all', 'development', 'toolchain'],
      browseHref: '/code-repos'
    },
    {
      id: 'marketplace',
      href: '/marketplace',
      icon: 'folder',
      name: { en: 'Marketplace', es: 'Marketplace' },
      description: {
        en: 'Discover internal packages, release channels, and one-click rollout bundles.',
        es: 'Descubre paquetes internos, canales de release y bundles de despliegue con un clic.'
      },
      badge: { en: 'Application development', es: 'Desarrollo de aplicaciones' },
      categoryIds: ['all', 'development'],
      browseHref: '/marketplace'
    },
    {
      id: 'ai',
      href: '/ai',
      icon: 'sparkles',
      name: { en: 'AI Platform', es: 'Plataforma AI' },
      description: {
        en: 'Manage providers, prompts, guardrails, agents, and copilots from one control plane.',
        es: 'Gestiona proveedores, prompts, guardrails, agentes y copilots desde un solo plano de control.'
      },
      badge: { en: 'Models', es: 'Modelos' },
      categoryIds: ['all', 'models'],
      browseHref: '/ai'
    },
    {
      id: 'ml',
      href: '/ml',
      icon: 'sparkles',
      name: { en: 'ML Studio', es: 'ML Studio' },
      description: {
        en: 'Track experiments, training jobs, model versions, and online feature flows.',
        es: 'Sigue experimentos, trabajos de entrenamiento, versiones de modelo y flujos de features online.'
      },
      badge: { en: 'Models', es: 'Modelos' },
      categoryIds: ['all', 'models'],
      browseHref: '/ml'
    },
    {
      id: 'streaming',
      href: '/streaming',
      icon: 'graph',
      name: { en: 'Streaming', es: 'Streaming' },
      description: {
        en: 'Operate real-time topologies, windows, joins, and live event tails.',
        es: 'Opera topologías en tiempo real, ventanas, joins y colas de eventos en vivo.'
      },
      badge: { en: 'Data integration', es: 'Integración de datos' },
      categoryIds: ['all', 'integration'],
      browseHref: '/streaming'
    },
    {
      id: 'audit',
      href: '/audit',
      icon: 'bell',
      name: { en: 'Governance Center', es: 'Centro de gobierno' },
      description: {
        en: 'Review policies, approvals, applications, and governance templates.',
        es: 'Revisa políticas, aprobaciones, aplicaciones y plantillas de gobierno.'
      },
      badge: { en: 'Security & governance', es: 'Seguridad y gobierno' },
      categoryIds: ['all', 'administration', 'governance'],
      browseHref: '/audit'
    },
    {
      id: 'settings',
      href: '/settings',
      icon: 'settings',
      name: { en: 'Settings', es: 'Configuración' },
      description: {
        en: 'Configure identity, language, security posture, and account defaults.',
        es: 'Configura identidad, idioma, postura de seguridad y valores por defecto de la cuenta.'
      },
      badge: { en: 'Administration', es: 'Administración' },
      categoryIds: ['all', 'administration', 'governance'],
      browseHref: '/settings'
    }
  ];

  const utilityNav: NavItem[] = [
    { href: '/developers', labelKey: 'nav.support', icon: 'help' },
    { href: '/settings', labelKey: 'nav.account', icon: 'settings' }
  ];

  let applicationsLauncherOpen = $state(false);
  let selectedLauncherCategory = $state<LauncherCategoryId>('all');
  let selectedLauncherAppId = $state('datasets');
  let launcherSearch = $state('');
  let launcherSearchInput = $state<HTMLInputElement | null>(null);

  function isActive(href: string, pathname: string) {
    return href === '/' ? pathname === '/' : pathname === href || pathname.startsWith(`${href}/`);
  }

  function localize(copy: LocalizedCopy) {
    return $currentLocale === 'es' ? copy.es : copy.en;
  }

  function getPreferredCategory(app: LauncherApp | undefined) {
    // Index 0 is the generic "all" bucket; prefer the first specific category when one exists.
    return app?.categoryIds[1] ?? app?.categoryIds[0] ?? 'all';
  }

  const hasActiveApplication = $derived.by(() =>
    launcherApps.some((item) => isActive(item.href, $page.url.pathname))
  );

  const activeLauncherCopy = $derived.by(() => ($currentLocale === 'es' ? launcherCopy.es : launcherCopy.en));
  const launcherCategoryCounts = $derived.by(() =>
    Object.fromEntries(
      launcherCategories.map((category) => [
        category.id,
        category.id === 'all'
          ? launcherApps.length
          : launcherApps.filter((item) => item.categoryIds.includes(category.id)).length
      ])
    ) as Record<LauncherCategoryId, number>
  );
  const visibleLauncherApps = $derived.by(() => {
    const searchTerm = launcherSearch.trim().toLowerCase();
    return launcherApps.filter((item) => {
      const matchesCategory =
        selectedLauncherCategory === 'all' || item.categoryIds.includes(selectedLauncherCategory);
      const localizedName = localize(item.name).toLowerCase();
      const localizedDescription = localize(item.description).toLowerCase();
      const matchesSearch =
        !searchTerm ||
        localizedName.includes(searchTerm) ||
        localizedDescription.includes(searchTerm);
      return matchesCategory && matchesSearch;
    });
  });
  const selectedLauncherApp = $derived.by(
    () =>
      visibleLauncherApps.find((item) => item.id === selectedLauncherAppId) ??
      visibleLauncherApps[0] ??
      null
  );

  $effect(() => {
    if (applicationsLauncherOpen) {
      launcherSearchInput?.focus();
    }
  });

  function closeApplicationsLauncher() {
    applicationsLauncherOpen = false;
  }

  function openApplicationsLauncher() {
    const activeApp = launcherApps.find((item) => isActive(item.href, $page.url.pathname));
    selectedLauncherCategory = getPreferredCategory(activeApp);
    selectedLauncherAppId = activeApp?.id ?? launcherApps[0].id;
    launcherSearch = '';
    applicationsLauncherOpen = true;
  }

  function toggleApplicationsLauncher() {
    if (applicationsLauncherOpen) {
      closeApplicationsLauncher();
      return;
    }
    openApplicationsLauncher();
  }

  function handleWindowKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape' && applicationsLauncherOpen) {
      closeApplicationsLauncher();
    }
  }
</script>

<svelte:window onkeydown={handleWindowKeydown} />

<aside class="of-sidebar of-scrollbar">
  <div class="of-sidebar__brand">
    <a href="/" class="of-sidebar__logo" aria-label={t('nav.home')} title="OpenFoundry">
      <Glyph name="cube" size={18} />
    </a>
    <span class="of-sidebar__brand-meta" aria-hidden="true">
      <Glyph name="menu" size={14} />
    </span>
  </div>

  <nav class="of-sidebar__section" aria-label="Primary">
    {#each workspaceNav as item}
      <a
        href={item.href}
        class="of-sidebar__link"
        data-active={isActive(item.href, $page.url.pathname)}
        title={t(item.labelKey)}
        aria-label={t(item.labelKey)}
      >
        <span class="of-sidebar__icon">
          <Glyph name={item.icon} size={16} />
        </span>
        <span class="of-sidebar__label">{t(item.labelKey)}</span>
        {#if item.hint}
          <span class="of-sidebar__hint">{item.hint}</span>
        {/if}
      </a>
    {/each}

    <button
      type="button"
      class="of-sidebar__link of-sidebar__link--button"
      data-active={hasActiveApplication || applicationsLauncherOpen}
      data-expanded={applicationsLauncherOpen}
      aria-haspopup="dialog"
      aria-expanded={applicationsLauncherOpen}
      onclick={toggleApplicationsLauncher}
    >
      <span class="of-sidebar__icon">
        <Glyph name="cube" size={16} />
      </span>
      <span class="of-sidebar__label">{t('nav.applications')}</span>
      <span class="of-sidebar__caret">
        <Glyph name={applicationsLauncherOpen ? 'chevron-down' : 'chevron-right'} size={14} />
      </span>
    </button>
  </nav>

  <div class="of-sidebar__spacer"></div>

  <nav class="of-sidebar__section of-sidebar__section--footer" aria-label="Utility">
    {#each utilityNav as item}
      <a
        href={item.href}
        class="of-sidebar__link"
        data-active={isActive(item.href, $page.url.pathname)}
        title={t(item.labelKey)}
        aria-label={t(item.labelKey)}
      >
        <span class="of-sidebar__icon">
          <Glyph name={item.icon} size={16} />
        </span>
        <span class="of-sidebar__label">{t(item.labelKey)}</span>
      </a>
    {/each}
  </nav>
</aside>

{#if applicationsLauncherOpen}
  <div class="of-app-launcher">
    <button
      type="button"
      class="of-app-launcher__backdrop"
      aria-label={activeLauncherCopy.close}
      onclick={closeApplicationsLauncher}
    ></button>
    <div
      class="of-app-launcher__surface"
      role="dialog"
      aria-modal="true"
      aria-label={activeLauncherCopy.title}
    >
      <div class="of-app-launcher__header">
        <label class="of-app-launcher__search">
          <span class="sr-only">{activeLauncherCopy.searchAriaLabel}</span>
          <span class="of-app-launcher__search-icon">
            <Glyph name="search" size={14} />
          </span>
          <input
            bind:this={launcherSearchInput}
            bind:value={launcherSearch}
            type="search"
            placeholder={activeLauncherCopy.searchPlaceholder}
            aria-label={activeLauncherCopy.searchAriaLabel}
          />
        </label>
        <button
          type="button"
          class="of-app-launcher__close"
          aria-label={activeLauncherCopy.close}
          onclick={closeApplicationsLauncher}
        >
          <Glyph name="x" size={14} />
        </button>
      </div>

      <div class="of-app-launcher__body">
        <div class="of-app-launcher__categories">
          {#each launcherCategories as category}
            <button
              type="button"
              class="of-app-launcher__category"
              data-active={selectedLauncherCategory === category.id}
              onclick={() => {
                selectedLauncherCategory = category.id;
              }}
            >
              <span>{localize(category.label)}</span>
              <span class="of-app-launcher__category-count">{launcherCategoryCounts[category.id]}</span>
            </button>
          {/each}
        </div>

        <div class="of-app-launcher__catalog">
          {#if visibleLauncherApps.length > 0}
            {#each visibleLauncherApps as app}
              <a
                href={app.href}
                class="of-app-launcher__item"
                data-selected={selectedLauncherApp?.id === app.id}
                data-active={isActive(app.href, $page.url.pathname)}
                onmouseenter={() => {
                  selectedLauncherAppId = app.id;
                }}
                onfocus={() => {
                  selectedLauncherAppId = app.id;
                }}
                onclick={closeApplicationsLauncher}
              >
                <span class="of-app-launcher__item-icon">
                  <Glyph name={app.icon} size={16} />
                </span>
                <span class="of-app-launcher__item-copy">
                  <span class="of-app-launcher__item-name">{localize(app.name)}</span>
                  <span class="of-app-launcher__item-description">{localize(app.description)}</span>
                </span>
              </a>
            {/each}
          {:else}
            <div class="of-app-launcher__empty">{activeLauncherCopy.emptySearch}</div>
          {/if}
        </div>

        <div class="of-app-launcher__detail">
          {#if selectedLauncherApp}
            <div class="of-app-launcher__detail-icon">
              <Glyph name={selectedLauncherApp.icon} size={18} />
            </div>
            <div class="of-app-launcher__detail-copy">
              <div class="of-app-launcher__detail-badge">{localize(selectedLauncherApp.badge)}</div>
              <h2>{localize(selectedLauncherApp.name)}</h2>
              <p>{localize(selectedLauncherApp.description)}</p>
            </div>

            <div class="of-app-launcher__actions">
              <a href={selectedLauncherApp.href} class="of-app-launcher__link" onclick={closeApplicationsLauncher}>
                {activeLauncherCopy.open}
              </a>
              <a
                href={selectedLauncherApp.createHref ?? selectedLauncherApp.href}
                class="of-app-launcher__button of-app-launcher__button--primary"
                onclick={closeApplicationsLauncher}
              >
                {activeLauncherCopy.createNew}
              </a>
              <a
                href={selectedLauncherApp.browseHref ?? selectedLauncherApp.href}
                class="of-app-launcher__button"
                onclick={closeApplicationsLauncher}
              >
                {activeLauncherCopy.browseCatalog}
              </a>
            </div>

            <div class="of-app-launcher__favorites">
              <div class="of-app-launcher__favorites-title">{activeLauncherCopy.favorites}</div>
              <p>{activeLauncherCopy.emptyFavorites}</p>
            </div>
          {/if}
        </div>
      </div>
    </div>
  </div>
{/if}
