// apps/web/src/lib/components/layout/TopBar.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';

import { auth, useCurrentUser, useIsAuthenticated } from '@/lib/stores/auth';
import { ontologySearch } from '@/lib/stores/ontologySearch';
import { createTranslator, getLocaleLabel, setLocale, useCurrentLocale, type AppLocale } from '@/lib/i18n/store';
import type { MessageKey } from '@/lib/i18n/messages';
import { Glyph } from '@/lib/components/ui/Glyph';

import { NotificationBell } from './NotificationBell';

const TITLE_MAP: Record<string, MessageKey> = {
  '/': 'nav.home',
  '/apps': 'nav.applications',
  '/dashboards': 'nav.recent',
  '/datasets': 'nav.datasets',
  '/ml': 'nav.training',
  '/notebooks': 'nav.workshop',
  '/object-explorer': 'nav.objectExplorer',
  '/object-monitors': 'nav.notifications',
  '/ontology': 'nav.ontology',
  '/ontology-manager': 'nav.ontologyManager',
  '/pipelines': 'nav.pipelineBuilder',
  '/projects': 'nav.projects',
  '/queries': 'nav.queries',
  '/reports': 'nav.files',
  '/search': 'nav.search',
  '/settings': 'nav.account',
  '/control-panel': 'common.controlPanel',
};

export function TopBar() {
  const locale = useCurrentLocale();
  const t = useMemo(() => createTranslator(locale), [locale]);
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const isAuthenticated = useIsAuthenticated();
  const user = useCurrentUser();

  const [createMenuOpen, setCreateMenuOpen] = useState(false);
  const [createSearch, setCreateSearch] = useState('');
  const [createCategory, setCreateCategory] = useState<'all' | 'integration'>('all');
  const createMenuRef = useRef<HTMLDivElement | null>(null);

  const supported: AppLocale[] = ['en', 'es'];

  const pageTitle = useMemo(() => {
    const sorted = Object.keys(TITLE_MAP).sort((a, b) => b.length - a.length);
    const match = sorted.find((key) => pathname === key || pathname.startsWith(`${key}/`));
    return match ? t(TITLE_MAP[match]) : t('topbar.pageDefault');
  }, [pathname, t]);

  const isPipelineVisible = useMemo(() => {
    const term = createSearch.trim().toLowerCase();
    const matchesCategory = createCategory === 'all' || createCategory === 'integration';
    const title = t('nav.pipelineBuilder').toLowerCase();
    const description = t('topbar.pipelineBuilderDescription').toLowerCase();
    return matchesCategory && (!term || title.includes(term) || description.includes(term));
  }, [createSearch, createCategory, t]);

  function closeCreateMenu() {
    setCreateMenuOpen(false);
    setCreateSearch('');
    setCreateCategory('all');
  }

  useEffect(() => {
    function onClick(e: MouseEvent) {
      if (!createMenuOpen || !createMenuRef.current) return;
      if (createMenuRef.current.contains(e.target as Node)) return;
      closeCreateMenu();
    }
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape' && createMenuOpen) closeCreateMenu();
    }
    window.addEventListener('click', onClick);
    window.addEventListener('keydown', onKeyDown);
    return () => {
      window.removeEventListener('click', onClick);
      window.removeEventListener('keydown', onKeyDown);
    };
  }, [createMenuOpen]);

  function handleLogout() {
    auth.logout();
    navigate('/auth/login');
  }

  return (
    <header className="of-topbar">
      <div className="of-topbar__crumbs">
        <div className="of-topbar__trail">
          <span className="of-topbar__crumb-icon"><Glyph name="folder" size={13} /></span>
          <span className="of-topbar__crumb">{t('topbar.workspace')}</span>
        </div>
        <span aria-hidden="true"><Glyph name="chevron-right" size={11} /></span>
        <div className="of-topbar__trail of-topbar__trail--current">
          <span className="of-topbar__crumb">{pageTitle}</span>
        </div>
      </div>

      <div className="of-topbar__actions">
        <div className="of-topbar__create-menu" ref={createMenuRef}>
          <button
            type="button"
            className="of-topbar__action of-topbar__action--primary"
            aria-haspopup="dialog"
            aria-expanded={createMenuOpen}
            onClick={() => setCreateMenuOpen((v) => !v)}
          >
            <Glyph name="plus" size={14} />
            <span>{t('topbar.createNew')}</span>
            <Glyph name="chevron-down" size={12} />
          </button>

          {createMenuOpen && (
            <div className="of-topbar__create-panel" role="dialog" aria-label={t('topbar.createNew')}>
              <label className="of-topbar__create-search">
                <span className="of-topbar__create-search-icon"><Glyph name="search" size={14} /></span>
                <input
                  type="search"
                  value={createSearch}
                  onChange={(e) => setCreateSearch(e.target.value)}
                  placeholder={t('topbar.createSearchPlaceholder')}
                  aria-label={t('topbar.createSearchPlaceholder')}
                />
              </label>

              <div className="of-topbar__create-body">
                <div className="of-topbar__create-categories">
                  <button
                    type="button"
                    className="of-topbar__create-category"
                    data-active={createCategory === 'all' || undefined}
                    onClick={() => setCreateCategory('all')}
                  >
                    {t('topbar.createCategoryAll')}
                  </button>
                  <button
                    type="button"
                    className="of-topbar__create-category"
                    data-active={createCategory === 'integration' || undefined}
                    onClick={() => setCreateCategory('integration')}
                  >
                    {t('topbar.createCategoryIntegration')}
                  </button>
                </div>

                <div className="of-topbar__create-results">
                  {isPipelineVisible ? (
                    <button
                      type="button"
                      className="of-topbar__create-item"
                      onClick={() => { closeCreateMenu(); navigate('/pipelines/new'); }}
                    >
                      <span className="of-topbar__create-item-icon"><Glyph name="graph" size={17} /></span>
                      <span className="of-topbar__create-item-copy">
                        <span className="of-topbar__create-item-title">{t('nav.pipelineBuilder')}</span>
                        <span className="of-topbar__create-item-description">{t('topbar.pipelineBuilderDescription')}</span>
                      </span>
                      <span className="of-topbar__create-item-arrow"><Glyph name="chevron-right" size={14} /></span>
                    </button>
                  ) : (
                    <div className="of-topbar__create-empty">{t('topbar.createEmpty')}</div>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>

        <label className="of-topbar__action">
          <span>{t('topbar.userLanguage')}</span>
          <select
            className="bg-transparent text-[11px] font-semibold outline-none"
            value={locale}
            onChange={(e) => setLocale(e.target.value as AppLocale)}
          >
            {supported.map((loc) => (
              <option key={loc} value={loc}>{getLocaleLabel(loc, locale)}</option>
            ))}
          </select>
        </label>

        <button
          type="button"
          className="of-topbar__action"
          onClick={() => ontologySearch.open()}
          aria-label="Search ontology (⌘K)"
          title="Search ontology (⌘K)"
        >
          <Glyph name="search" size={14} />
          <span>Search</span>
          <kbd className="of-topbar__kbd">⌘K</kbd>
        </button>

        <Link to="/apps" className="of-topbar__action">
          <Glyph name="cube" size={14} />
          <span>{t('nav.applications')}</span>
        </Link>

        {isAuthenticated ? (
          <>
            <NotificationBell />
            <div className="of-topbar__user">
              <span className="of-topbar__avatar">OF</span>
              <div className="min-w-0">
                <div className="truncate text-[12px] font-semibold text-[var(--text-strong)]">
                  {user?.name ?? t('topbar.operator')}
                </div>
                <div className="truncate text-[11px] text-[var(--text-muted)]">{t('topbar.workspaceSession')}</div>
              </div>
            </div>
            <button type="button" className="of-topbar__action" onClick={handleLogout} aria-label={t('common.logout')}>
              <Glyph name="logout" size={14} />
            </button>
          </>
        ) : (
          <Link to="/auth/login" className="of-topbar__action">{t('common.login')}</Link>
        )}
      </div>
    </header>
  );
}

// apps/web/src/lib/components/layout/TopBar.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import NotificationBell from '$components/layout/NotificationBell.svelte';
  import Glyph from '$components/ui/Glyph.svelte';
  import type { MessageKey } from '$lib/i18n/messages';
  import {
    createTranslator,
    currentLocale,
    getLocaleLabel,
    setLocale,
    supportedLocales,
    type AppLocale
  } from '$lib/i18n/store';
  import { auth } from '$stores/auth';

  const isAuthenticated = auth.isAuthenticated;
  const user = auth.user;
  const t = $derived.by(() => createTranslator($currentLocale));
  const languageOptions = supportedLocales;
  let createMenuOpen = $state(false);
  let createMenuSearch = $state('');
  let createMenuCategory = $state<'all' | 'integration'>('all');
  let createMenuRef = $state<HTMLDivElement | null>(null);

  const visibleCreateItems = $derived.by(() => {
    const searchTerm = createMenuSearch.trim().toLowerCase();
    const matchesCategory = createMenuCategory === 'all' || createMenuCategory === 'integration';
    const title = t('nav.pipelineBuilder').toLowerCase();
    const description = t('topbar.pipelineBuilderDescription').toLowerCase();
    return matchesCategory && (!searchTerm || title.includes(searchTerm) || description.includes(searchTerm));
  });

  const titleMap: Record<string, MessageKey> = {
    '/': 'nav.home',
    '/apps': 'nav.applications',
    '/dashboards': 'nav.recent',
    '/datasets': 'nav.datasets',
    '/ml': 'nav.training',
    '/notebooks': 'nav.workshop',
    '/object-explorer': 'nav.objectExplorer',
    '/object-monitors': 'nav.notifications',
    '/ontology': 'nav.ontology',
    '/ontology-manager': 'nav.ontologyManager',
    '/pipelines': 'nav.pipelineBuilder',
    '/projects': 'nav.projects',
    '/queries': 'nav.queries',
    '/reports': 'nav.files',
    '/search': 'nav.search',
    '/settings': 'nav.account',
    '/control-panel': 'common.controlPanel'
  };

  const pageTitle = $derived.by(() => {
    const pathname = $page.url.pathname;
    const sorted = Object.keys(titleMap).sort((a, b) => b.length - a.length);
    const match = sorted.find((key) => pathname === key || pathname.startsWith(`${key}/`));
    return match ? t(titleMap[match]) : t('topbar.pageDefault');
  });

  function handleLogout() {
    auth.logout();
    goto('/auth/login');
  }

  function closeCreateMenu() {
    createMenuOpen = false;
    createMenuSearch = '';
    createMenuCategory = 'all';
  }

  function toggleCreateMenu() {
    createMenuOpen = !createMenuOpen;
    if (!createMenuOpen) {
      createMenuSearch = '';
      createMenuCategory = 'all';
    }
  }

  function openPipelineBuilder() {
    closeCreateMenu();
    goto('/pipelines/new');
  }

  function handleWindowClick(event: MouseEvent) {
    if (!createMenuOpen || !createMenuRef) return;
    if (createMenuRef.contains(event.target as Node)) return;
    closeCreateMenu();
  }

  function handleWindowKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape' && createMenuOpen) {
      closeCreateMenu();
    }
  }
</script>

<svelte:window onclick={handleWindowClick} onkeydown={handleWindowKeydown} />

<header class="of-topbar">
  <div class="of-topbar__crumbs">
    <div class="of-topbar__trail">
      <span class="of-topbar__crumb-icon">
        <Glyph name="folder" size={13} />
      </span>
      <span class="of-topbar__crumb">{t('topbar.workspace')}</span>
    </div>
    <span aria-hidden="true">
      <Glyph name="chevron-right" size={11} />
    </span>
    <div class="of-topbar__trail of-topbar__trail--current">
      <span class="of-topbar__crumb">{pageTitle}</span>
    </div>
  </div>

  <div class="of-topbar__actions">
    <div class="of-topbar__create-menu" bind:this={createMenuRef}>
      <button type="button" class="of-topbar__action of-topbar__action--primary" aria-haspopup="dialog" aria-expanded={createMenuOpen} onclick={toggleCreateMenu}>
        <Glyph name="plus" size={14} />
        <span>{t('topbar.createNew')}</span>
        <Glyph name="chevron-down" size={12} />
      </button>

      {#if createMenuOpen}
        <div class="of-topbar__create-panel" role="dialog" aria-label={t('topbar.createNew')}>
          <label class="of-topbar__create-search">
            <span class="of-topbar__create-search-icon">
              <Glyph name="search" size={14} />
            </span>
            <input bind:value={createMenuSearch} type="search" placeholder={t('topbar.createSearchPlaceholder')} aria-label={t('topbar.createSearchPlaceholder')} />
          </label>

          <div class="of-topbar__create-body">
            <div class="of-topbar__create-categories">
              <button type="button" class="of-topbar__create-category" data-active={createMenuCategory === 'all'} onclick={() => (createMenuCategory = 'all')}>
                {t('topbar.createCategoryAll')}
              </button>
              <button type="button" class="of-topbar__create-category" data-active={createMenuCategory === 'integration'} onclick={() => (createMenuCategory = 'integration')}>
                {t('topbar.createCategoryIntegration')}
              </button>
            </div>

            <div class="of-topbar__create-results">
              {#if visibleCreateItems}
                <button type="button" class="of-topbar__create-item" onclick={openPipelineBuilder}>
                  <span class="of-topbar__create-item-icon">
                    <Glyph name="graph" size={17} />
                  </span>
                  <span class="of-topbar__create-item-copy">
                    <span class="of-topbar__create-item-title">{t('nav.pipelineBuilder')}</span>
                    <span class="of-topbar__create-item-description">{t('topbar.pipelineBuilderDescription')}</span>
                  </span>
                  <span class="of-topbar__create-item-arrow">
                    <Glyph name="chevron-right" size={14} />
                  </span>
                </button>
              {:else}
                <div class="of-topbar__create-empty">{t('topbar.createEmpty')}</div>
              {/if}
            </div>
          </div>
        </div>
      {/if}
    </div>

    <label class="of-topbar__action">
      <span>{t('topbar.userLanguage')}</span>
      <select
        class="bg-transparent text-[11px] font-semibold outline-none"
        value={$currentLocale}
        onchange={(event) => setLocale((event.currentTarget as HTMLSelectElement).value as AppLocale)}
      >
        {#each $languageOptions as locale}
          <option value={locale}>{getLocaleLabel(locale, $currentLocale)}</option>
        {/each}
      </select>
    </label>

    <a href="/apps" class="of-topbar__action">
      <Glyph name="cube" size={14} />
      <span>{t('nav.applications')}</span>
    </a>

    {#if $isAuthenticated}
      <NotificationBell />
      <div class="of-topbar__user">
        <span class="of-topbar__avatar">OF</span>
        <div class="min-w-0">
          <div class="truncate text-[12px] font-semibold text-[var(--text-strong)]">
            {$user?.name ?? t('topbar.operator')}
          </div>
          <div class="truncate text-[11px] text-[var(--text-muted)]">{t('topbar.workspaceSession')}</div>
        </div>
      </div>
      <button type="button" class="of-topbar__action" onclick={handleLogout} aria-label={t('common.logout')}>
        <Glyph name="logout" size={14} />
      </button>
    {:else}
      <a href="/auth/login" class="of-topbar__action">{t('common.login')}</a>
    {/if}
  </div>
</header>
