// apps/web/src/lib/components/ui/Tree.svelte
<script lang="ts">
  import Glyph from './Glyph.svelte';

  type Json = unknown;

  let {
    data,
    label = '',
    collapsedByDefault = false
  }: {
    data: Json;
    label?: string;
    collapsedByDefault?: boolean;
  } = $props();

  let expanded = $state(!collapsedByDefault);

  function isObject(value: Json): value is Record<string, Json> {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
  }

  function entries(value: Json): Array<[string, Json]> {
    if (isObject(value)) return Object.entries(value);
    if (Array.isArray(value)) return value.map((item, i) => [String(i), item]);
    return [];
  }

  function isComplex(value: Json) {
    return Array.isArray(value) || isObject(value);
  }

  function formatLeaf(value: Json) {
    if (value === null) return 'null';
    if (value === undefined) return 'undefined';
    if (typeof value === 'string') return JSON.stringify(value);
    return String(value);
  }

  function leafTone(value: Json) {
    if (value === null || value === undefined)
      return 'text-slate-400 dark:text-slate-500';
    if (typeof value === 'string') return 'text-emerald-700 dark:text-emerald-300';
    if (typeof value === 'number') return 'text-blue-700 dark:text-blue-300';
    if (typeof value === 'boolean') return 'text-amber-700 dark:text-amber-300';
    return 'text-slate-700 dark:text-slate-200';
  }
</script>

{#if isComplex(data)}
  <div class="font-mono text-[12px] leading-snug" data-testid="tree">
    {#if label}
      <button
        type="button"
        class="inline-flex items-center gap-1 text-slate-700 hover:text-slate-900 dark:text-slate-200"
        onclick={() => (expanded = !expanded)}
      >
        <Glyph name={expanded ? 'chevron-down' : 'chevron-right'} size={12} />
        <span class="font-semibold">{label}</span>
        <span class="text-[11px] text-slate-400">
          {Array.isArray(data) ? `[${data.length}]` : `{${Object.keys(data as object).length}}`}
        </span>
      </button>
    {/if}
    {#if expanded || !label}
      <ul class="ml-3 mt-1 space-y-0.5 border-l border-slate-200 pl-3 dark:border-gray-700">
        {#each entries(data) as [key, value] (key)}
          <li>
            {#if isComplex(value)}
              <svelte:self data={value} label={key} collapsedByDefault={true} />
            {:else}
              <div class="flex gap-2">
                <span class="text-slate-500 dark:text-slate-400">{key}:</span>
                <span class={leafTone(value)}>{formatLeaf(value)}</span>
              </div>
            {/if}
          </li>
        {/each}
        {#if entries(data).length === 0}
          <li class="text-[11px] italic text-slate-400">empty</li>
        {/if}
      </ul>
    {/if}
  </div>
{:else}
  <div class="font-mono text-[12px]">
    {#if label}<span class="text-slate-500">{label}: </span>{/if}
    <span class={leafTone(data)}>{formatLeaf(data)}</span>
  </div>
{/if}

// apps/web/src/lib/components/ui/Tree.tsx
import { useState } from 'react';

import { Glyph } from './Glyph';

interface TreeProps {
  data: unknown;
  label?: string;
  collapsedByDefault?: boolean;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isComplex(value: unknown) {
  return Array.isArray(value) || isObject(value);
}

function entries(value: unknown): Array<[string, unknown]> {
  if (isObject(value)) return Object.entries(value);
  if (Array.isArray(value)) return value.map((item, i) => [String(i), item]);
  return [];
}

function formatLeaf(value: unknown) {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  if (typeof value === 'string') return JSON.stringify(value);
  return String(value);
}

function leafColor(value: unknown) {
  if (value === null || value === undefined) return '#94a3b8';
  if (typeof value === 'string') return '#10b981';
  if (typeof value === 'number') return '#60a5fa';
  if (typeof value === 'boolean') return '#f59e0b';
  return '#cbd5e1';
}

export function Tree({ data, label = '', collapsedByDefault = false }: TreeProps) {
  const [expanded, setExpanded] = useState(!collapsedByDefault);

  if (!isComplex(data)) {
    return (
      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>
        {label && <span style={{ color: '#94a3b8' }}>{label}: </span>}
        <span style={{ color: leafColor(data) }}>{formatLeaf(data)}</span>
      </div>
    );
  }

  const items = entries(data);
  const summary = Array.isArray(data) ? `[${data.length}]` : `{${Object.keys(data as object).length}}`;

  return (
    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 12, lineHeight: 1.4 }}>
      {label && (
        <button
          type="button"
          onClick={() => setExpanded((e) => !e)}
          style={{ display: 'inline-flex', alignItems: 'center', gap: 4, background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', padding: 0 }}
        >
          <Glyph name={expanded ? 'chevron-down' : 'chevron-right'} size={12} />
          <span style={{ fontWeight: 600 }}>{label}</span>
          <span style={{ fontSize: 11, color: '#94a3b8' }}>{summary}</span>
        </button>
      )}
      {(expanded || !label) && (
        <ul style={{ marginLeft: 12, marginTop: 4, paddingLeft: 12, listStyle: 'none', borderLeft: '1px solid #334155', display: 'grid', gap: 2 }}>
          {items.map(([key, value]) => (
            <li key={key}>
              {isComplex(value) ? (
                <Tree data={value} label={key} collapsedByDefault />
              ) : (
                <div style={{ display: 'flex', gap: 8 }}>
                  <span style={{ color: '#94a3b8' }}>{key}:</span>
                  <span style={{ color: leafColor(value) }}>{formatLeaf(value)}</span>
                </div>
              )}
            </li>
          ))}
          {items.length === 0 && <li style={{ fontSize: 11, fontStyle: 'italic', color: '#94a3b8' }}>empty</li>}
        </ul>
      )}
    </div>
  );
}
