// apps/web/src/lib/components/workspace/MoveDialog.tsx
import { useEffect, useState } from 'react';

import { listProjectFolders, type OntologyProject, type OntologyProjectFolder } from '@/lib/api/ontology';
import { batchApply, moveResource, type BatchAction, type ResourceKind } from '@/lib/api/workspace';

interface BulkTarget {
  kind: ResourceKind;
  id: string;
  label: string;
}

interface MoveDialogProps {
  open: boolean;
  resourceKind: ResourceKind | null;
  resourceId: string | null;
  resourceLabel?: string;
  projects: OntologyProject[];
  initialProjectId?: string | null;
  targets?: BulkTarget[];
  onClose?: () => void;
  onMoved?: () => void;
}

export function MoveDialog({
  open,
  resourceKind,
  resourceId,
  resourceLabel,
  projects,
  initialProjectId,
  targets,
  onClose,
  onMoved,
}: MoveDialogProps) {
  const isBulk = Array.isArray(targets) && targets.length > 0;
  const [targetProjectId, setTargetProjectId] = useState('');
  const [targetFolderId, setTargetFolderId] = useState('');
  const [folders, setFolders] = useState<OntologyProjectFolder[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!open) return;
    setTargetProjectId(initialProjectId ?? projects[0]?.id ?? '');
    setTargetFolderId('');
    setSubmitting(false);
    setError('');
  }, [open, initialProjectId, projects]);

  useEffect(() => {
    if (!open || !targetProjectId) {
      setFolders([]);
      return;
    }
    listProjectFolders(targetProjectId)
      .then(setFolders)
      .catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Unable to load folders'));
  }, [open, targetProjectId]);

  async function submit() {
    if (!targetProjectId) { setError('Pick a destination project.'); return; }
    setSubmitting(true);
    setError('');
    try {
      if (isBulk && targets) {
        const actions: BatchAction[] = targets.map((t) => ({
          op: 'move',
          resource_kind: t.kind,
          resource_id: t.id,
          target_folder_id: targetFolderId || null,
        }));
        await batchApply(actions);
      } else {
        if (!resourceKind || !resourceId) { setError('Pick a destination project.'); setSubmitting(false); return; }
        await moveResource(resourceKind, resourceId, {
          target_project_id: targetProjectId,
          target_folder_id: targetFolderId || null,
        });
      }
      onMoved?.();
      onClose?.();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setSubmitting(false);
    }
  }

  if (!open) return null;
  return (
    <div role="dialog" aria-modal="true" style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16, zIndex: 100 }}>
      <div style={{ width: '100%', maxWidth: 500, background: '#0f172a', color: '#e2e8f0', border: '1px solid #1e293b', borderRadius: 12, boxShadow: '0 20px 50px rgba(0,0,0,0.5)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #1e293b', padding: '12px 16px' }}>
          <div style={{ fontSize: 13, fontWeight: 600 }}>Move {isBulk ? `${targets!.length} items` : resourceLabel || 'resource'}</div>
          <button type="button" onClick={() => !submitting && onClose?.()} style={{ background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: 13 }}>✕</button>
        </div>
        <div style={{ display: 'grid', gap: 8, padding: 16 }}>
          <label style={{ fontSize: 12 }}>
            Project
            <select value={targetProjectId} onChange={(e) => setTargetProjectId(e.target.value)} className="of-input" style={{ marginTop: 4 }}>
              <option value="">— pick —</option>
              {projects.map((p) => <option key={p.id} value={p.id}>{p.display_name || p.slug}</option>)}
            </select>
          </label>
          <label style={{ fontSize: 12 }}>
            Folder (optional)
            <select value={targetFolderId} onChange={(e) => setTargetFolderId(e.target.value)} className="of-input" style={{ marginTop: 4 }}>
              <option value="">— root —</option>
              {folders.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}
            </select>
          </label>
          {error && <p style={{ color: '#fca5a5', fontSize: 11, margin: 0 }}>{error}</p>}
        </div>
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, borderTop: '1px solid #1e293b', padding: '12px 16px' }}>
          <button type="button" onClick={() => onClose?.()} disabled={submitting} className="of-button">Cancel</button>
          <button type="button" onClick={() => void submit()} disabled={submitting || !targetProjectId} className="of-button of-button--primary">
            {submitting ? 'Moving…' : 'Move'}
          </button>
        </div>
      </div>
    </div>
  );
}

// apps/web/src/lib/components/workspace/MoveDialog.svelte
<script lang="ts">
  import { notifications } from '$stores/notifications';
  import { batchApply, moveResource, type BatchAction, type ResourceKind } from '$lib/api/workspace';
  import { listProjectFolders, type OntologyProject, type OntologyProjectFolder } from '$lib/api/ontology';

  type BulkTarget = { kind: ResourceKind; id: string; label: string };

  let {
    open,
    resourceKind,
    resourceId,
    resourceLabel,
    projects,
    initialProjectId,
    targets,
    onClose,
    onMoved,
  }: {
    open: boolean;
    resourceKind: ResourceKind | null;
    resourceId: string | null;
    resourceLabel?: string;
    projects: OntologyProject[];
    initialProjectId?: string | null;
    targets?: BulkTarget[];
    onClose?: () => void;
    onMoved?: () => void;
  } = $props();

  const isBulk = $derived(Array.isArray(targets) && targets.length > 0);

  let targetProjectId = $state<string>('');
  let targetFolderId = $state<string>('');
  let folders = $state<OntologyProjectFolder[]>([]);
  let loadingFolders = $state(false);
  let submitting = $state(false);

  $effect(() => {
    if (!open) return;
    targetProjectId = initialProjectId ?? projects[0]?.id ?? '';
    targetFolderId = '';
    submitting = false;
  });

  $effect(() => {
    if (!open || !targetProjectId) {
      folders = [];
      return;
    }
    void loadFolders(targetProjectId);
  });

  async function loadFolders(projectId: string) {
    loadingFolders = true;
    try {
      folders = await listProjectFolders(projectId);
    } catch (cause) {
      notifications.error(cause instanceof Error ? cause.message : 'Unable to load folders');
      folders = [];
    } finally {
      loadingFolders = false;
    }
  }

  async function submit() {
    if (!targetProjectId) {
      notifications.warning('Pick a destination project.');
      return;
    }
    submitting = true;
    try {
      if (isBulk && targets) {
        const actions: BatchAction[] = targets.map((t) => ({
          op: 'move',
          resource_kind: t.kind,
          resource_id: t.id,
          target_folder_id: targetFolderId || null,
        }));
        const { results } = await batchApply(actions);
        const failed = results.filter((r) => !r.ok);
        if (failed.length === 0) {
          notifications.success(`Moved ${results.length} item(s).`);
        } else {
          notifications.warning(
            `${results.length - failed.length} succeeded, ${failed.length} failed.`,
          );
        }
      } else {
        if (!resourceKind || !resourceId) {
          notifications.warning('Pick a destination project.');
          return;
        }
        await moveResource(resourceKind, resourceId, {
          target_project_id: targetProjectId,
          target_folder_id: targetFolderId || null,
        });
        notifications.success('Moved successfully.');
      }
      onMoved?.();
      onClose?.();
    } catch (cause) {
      notifications.error(cause instanceof Error ? cause.message : 'Unable to move resource');
    } finally {
      submitting = false;
    }
  }

  function close() {
    if (submitting) return;
    onClose?.();
  }
</script>

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"
    role="dialog"
    aria-modal="true"
    aria-label="Move resource"
  >
    <div class="w-full max-w-md rounded-md border border-[var(--border-default)] bg-white shadow-xl">
      <div class="flex items-center justify-between border-b border-[var(--border-default)] px-4 py-3">
        <div>
          <div class="text-sm font-semibold text-[var(--text-strong)]">
            {isBulk ? `Move ${targets?.length ?? 0} item(s)` : 'Move resource'}
          </div>
          {#if !isBulk && resourceLabel}
            <div class="text-xs text-[var(--text-muted)]">{resourceLabel}</div>
          {:else if isBulk && targets}
            <div class="text-xs text-[var(--text-muted)]">
              {targets.slice(0, 3).map((t) => t.label).join(', ')}{targets.length > 3 ? `, +${targets.length - 3} more` : ''}
            </div>
          {/if}
        </div>
        <button type="button" class="text-sm text-[var(--text-muted)] hover:text-[var(--text-strong)]" onclick={close}>
          ✕
        </button>
      </div>
      <div class="space-y-3 p-4">
        <div>
          <label class="block text-xs font-semibold uppercase tracking-wide text-[var(--text-muted)]" for="move-project">
            Target project
          </label>
          <select id="move-project" class="of-select mt-1 w-full" bind:value={targetProjectId}>
            {#each projects as project (project.id)}
              <option value={project.id}>{project.display_name || project.slug}</option>
            {/each}
          </select>
        </div>
        <div>
          <label class="block text-xs font-semibold uppercase tracking-wide text-[var(--text-muted)]" for="move-folder">
            Target folder
          </label>
          <select id="move-folder" class="of-select mt-1 w-full" bind:value={targetFolderId} disabled={loadingFolders}>
            <option value="">— Project root —</option>
            {#each folders as folder (folder.id)}
              <option value={folder.id}>{folder.name}</option>
            {/each}
          </select>
          {#if loadingFolders}
            <div class="mt-1 text-xs text-[var(--text-muted)]">Loading folders…</div>
          {/if}
        </div>
      </div>
      <div class="flex justify-end gap-2 border-t border-[var(--border-default)] px-4 py-3">
        <button type="button" class="of-btn of-btn-ghost" onclick={close} disabled={submitting}>Cancel</button>
        <button type="button" class="of-btn of-btn-primary" onclick={() => void submit()} disabled={submitting}>
          {submitting ? 'Moving…' : 'Move here'}
        </button>
      </div>
    </div>
  </div>
{/if}
