// apps/web-react/src/lib/components/workspace/PrincipalPicker.tsx
import { useEffect, useRef, useState } from 'react';

import { listGroups, listUsers, type GroupRecord, type UserProfile } from '@/lib/api/auth';

interface PrincipalPickerProps {
  kind: 'user' | 'group';
  value: string;
  onChange: (next: { id: string; label: string }) => void;
  placeholder?: string;
}

export function PrincipalPicker({ kind, value, onChange, placeholder = 'Search by name or email…' }: PrincipalPickerProps) {
  const [users, setUsers] = useState<UserProfile[]>([]);
  const [groups, setGroups] = useState<GroupRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState(false);
  const [highlight, setHighlight] = useState(0);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(async () => {
      setLoading(true);
      setError('');
      try {
        if (kind === 'user') {
          setUsers(await listUsers(query ? { q: query, limit: 50 } : { limit: 50 }));
        } else {
          setGroups(await listGroups(query ? { q: query, limit: 50 } : { limit: 50 }));
        }
      } catch (cause) {
        setError(cause instanceof Error ? cause.message : String(cause));
      } finally {
        setLoading(false);
      }
    }, 200);
    return () => { if (debounceRef.current) clearTimeout(debounceRef.current); };
  }, [kind, query]);

  useEffect(() => {
    if (!open) return;
    function onClick(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener('mousedown', onClick);
    return () => document.removeEventListener('mousedown', onClick);
  }, [open]);

  const items = kind === 'user'
    ? users.map((u) => ({ id: u.id, label: u.name, sublabel: u.email }))
    : groups.map((g) => ({ id: g.id, label: g.name, sublabel: g.description ?? '' }));

  return (
    <div ref={containerRef} style={{ position: 'relative' }}>
      <input
        value={query}
        onChange={(e) => { setQuery(e.target.value); setOpen(true); setHighlight(0); }}
        onFocus={() => setOpen(true)}
        onKeyDown={(e) => {
          if (!open) return;
          if (e.key === 'ArrowDown') { e.preventDefault(); setHighlight((h) => Math.min(h + 1, items.length - 1)); }
          else if (e.key === 'ArrowUp') { e.preventDefault(); setHighlight((h) => Math.max(0, h - 1)); }
          else if (e.key === 'Enter' && items[highlight]) {
            e.preventDefault();
            onChange({ id: items[highlight].id, label: items[highlight].label });
            setOpen(false);
          }
        }}
        placeholder={placeholder}
        className="of-input"
        style={{ width: '100%' }}
      />
      {value && !query && (
        <p className="of-text-muted" style={{ fontSize: 11, marginTop: 4 }}>Selected id: <code>{value}</code></p>
      )}
      {open && (
        <div style={{ position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 30, marginTop: 4, background: '#0f172a', border: '1px solid #1e293b', borderRadius: 6, maxHeight: 240, overflow: 'auto' }}>
          {loading && <p style={{ padding: 12, fontSize: 12, color: '#94a3b8', margin: 0 }}>Searching…</p>}
          {error && <p style={{ padding: 12, fontSize: 12, color: '#fca5a5', margin: 0 }}>{error}</p>}
          {items.length === 0 && !loading && <p style={{ padding: 12, fontSize: 12, color: '#94a3b8', margin: 0 }}>No matches.</p>}
          {items.map((it, i) => (
            <button
              key={it.id}
              type="button"
              onMouseEnter={() => setHighlight(i)}
              onClick={() => { onChange({ id: it.id, label: it.label }); setOpen(false); setQuery(''); }}
              style={{
                width: '100%',
                textAlign: 'left',
                padding: '8px 12px',
                background: i === highlight ? '#1e293b' : 'transparent',
                border: 'none',
                color: 'inherit',
                cursor: 'pointer',
                fontSize: 13,
              }}
            >
              <strong>{it.label}</strong>
              {it.sublabel && <p style={{ margin: 0, color: '#94a3b8', fontSize: 11 }}>{it.sublabel}</p>}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// apps/web/src/lib/components/workspace/PrincipalPicker.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { listGroups, listUsers, type GroupRecord, type UserProfile } from '$lib/api/auth';

  export type Principal =
    | { kind: 'user'; id: string; label: string; sublabel?: string }
    | { kind: 'group'; id: string; label: string; sublabel?: string };

  let {
    kind,
    value,
    onChange,
    placeholder = 'Search by name or email…',
  }: {
    kind: 'user' | 'group';
    value: string;
    onChange: (next: { id: string; label: string }) => void;
    placeholder?: string;
  } = $props();

  let users = $state<UserProfile[]>([]);
  let groups = $state<GroupRecord[]>([]);
  let loading = $state(false);
  let loadError = $state('');
  let usersLoaded = false;
  let groupsLoaded = false;

  let query = $state('');
  let open = $state(false);
  let highlightIndex = $state(0);
  let inputEl = $state<HTMLInputElement | null>(null);

  // When `value` changes externally (e.g. parent reset), surface the
  // selected label in the input so the user sees what was committed.
  $effect(() => {
    if (!value) {
      query = '';
      return;
    }
    if (kind === 'user') {
      const match = users.find((u) => u.id === value);
      if (match) query = match.name || match.email;
    } else {
      const match = groups.find((g) => g.id === value);
      if (match) query = match.name;
    }
  });

  $effect(() => {
    if (kind === 'user') void ensureUsers();
    else void ensureGroups();
  });

  async function ensureUsers() {
    if (usersLoaded || loading) return;
    loading = true;
    loadError = '';
    try {
      users = await listUsers();
      usersLoaded = true;
    } catch (cause) {
      loadError = cause instanceof Error ? cause.message : 'Unable to load users';
      users = [];
    } finally {
      loading = false;
    }
  }

  async function ensureGroups() {
    if (groupsLoaded || loading) return;
    loading = true;
    loadError = '';
    try {
      groups = await listGroups();
      groupsLoaded = true;
    } catch (cause) {
      loadError = cause instanceof Error ? cause.message : 'Unable to load groups';
      groups = [];
    } finally {
      loading = false;
    }
  }

  const matches = $derived.by<Principal[]>(() => {
    const q = query.trim().toLowerCase();
    if (kind === 'user') {
      const filtered = q
        ? users.filter(
            (u) =>
              (u.name || '').toLowerCase().includes(q) ||
              (u.email || '').toLowerCase().includes(q),
          )
        : users;
      return filtered.slice(0, 25).map((u) => ({
        kind: 'user' as const,
        id: u.id,
        label: u.name || u.email,
        sublabel: u.email,
      }));
    }
    const filtered = q
      ? groups.filter(
          (g) =>
            (g.name || '').toLowerCase().includes(q) ||
            (g.description || '').toLowerCase().includes(q),
        )
      : groups;
    return filtered.slice(0, 25).map((g) => ({
      kind: 'group' as const,
      id: g.id,
      label: g.name,
      sublabel: g.description ?? undefined,
    }));
  });

  function pick(p: Principal) {
    onChange({ id: p.id, label: p.label });
    query = p.label;
    open = false;
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      open = true;
      highlightIndex = Math.min(highlightIndex + 1, Math.max(matches.length - 1, 0));
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      highlightIndex = Math.max(highlightIndex - 1, 0);
    } else if (event.key === 'Enter') {
      if (open && matches[highlightIndex]) {
        event.preventDefault();
        pick(matches[highlightIndex]);
      }
    } else if (event.key === 'Escape') {
      open = false;
    }
  }

  function handleInput(event: Event) {
    query = (event.currentTarget as HTMLInputElement).value;
    highlightIndex = 0;
    open = true;
    if (!query) onChange({ id: '', label: '' });
  }

  function handleBlur() {
    // delay to allow click on a list item to register
    setTimeout(() => (open = false), 120);
  }

  onMount(() => {
    if (kind === 'user') void ensureUsers();
    else void ensureGroups();
  });
</script>

<div class="relative">
  <input
    bind:this={inputEl}
    class="of-input w-full"
    type="text"
    role="combobox"
    aria-expanded={open}
    aria-autocomplete="list"
    {placeholder}
    value={query}
    oninput={handleInput}
    onfocus={() => (open = true)}
    onblur={handleBlur}
    onkeydown={handleKeydown}
  />

  {#if open && (matches.length > 0 || loading || loadError)}
    <ul
      class="absolute left-0 right-0 top-full z-30 mt-1 max-h-64 overflow-auto rounded-md border border-[var(--border-default)] bg-white py-1 shadow-lg"
      role="listbox"
    >
      {#if loading}
        <li class="px-3 py-2 text-xs text-[var(--text-muted)]">Loading…</li>
      {:else if loadError}
        <li class="px-3 py-2 text-xs text-[#b42318]">{loadError}</li>
      {:else}
        {#each matches as match, index (`${match.kind}:${match.id}`)}
          <li>
            <button
              type="button"
              role="option"
              aria-selected={index === highlightIndex}
              class={`flex w-full flex-col items-start px-3 py-1.5 text-left text-sm ${
                index === highlightIndex ? 'bg-[var(--bg-hover)]' : ''
              }`}
              onmousedown={(event) => {
                // mousedown fires before blur, prevents the dropdown from closing first
                event.preventDefault();
                pick(match);
              }}
              onmouseenter={() => (highlightIndex = index)}
            >
              <span class="font-medium text-[var(--text-strong)]">{match.label}</span>
              {#if match.sublabel}
                <span class="text-xs text-[var(--text-muted)]">{match.sublabel}</span>
              {/if}
            </button>
          </li>
        {/each}
      {/if}
    </ul>
  {/if}
</div>
