// apps/web/src/lib/components/workspace/ResourceDetailsPanel.tsx
import { useEffect, useState } from 'react';

import {
  createFavorite,
  deleteFavorite,
  listResourceShares,
  type ResourceKind,
  type ResourceShare,
} from '@/lib/api/workspace';
import { OpenWithMenu } from './OpenWithMenu';
import { ResourcePermissionsDrawer, type AccessGraphMembership } from './ResourcePermissionsDrawer';
import { ShareDialog } from './ShareDialog';

export interface ResourceSummary {
  id: string;
  rid?: string | null;
  name: string;
  kind: ResourceKind;
  description?: string | null;
  owner_id?: string | null;
  location?: string | null;
  project_id?: string | null;
  project_rid?: string | null;
  open_url?: string | null;
  tags?: string[];
  created_at?: string | null;
  updated_at?: string | null;
}

interface ResourceDetailsPanelProps {
  open: boolean;
  resource: ResourceSummary | null;
  isFavorite?: boolean;
  projectLabel?: string | null;
  projectMemberships?: AccessGraphMembership[];
  onClose?: () => void;
  onFavoriteToggle?: (next: boolean) => void;
}

function fmtDate(v: string | null | undefined) {
  if (!v) return '—';
  try { return new Date(v).toLocaleString(); }
  catch { return v; }
}

export function ResourceDetailsPanel({
  open,
  resource,
  isFavorite = false,
  projectLabel,
  projectMemberships = [],
  onClose,
  onFavoriteToggle,
}: ResourceDetailsPanelProps) {
  const [shares, setShares] = useState<ResourceShare[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [shareOpen, setShareOpen] = useState(false);
  const [permissionsOpen, setPermissionsOpen] = useState(false);

  useEffect(() => {
    if (!open || !resource) { setShares([]); return; }
    setLoading(true);
    setError('');
    listResourceShares(resource.kind, resource.id)
      .then(setShares)
      .catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Unable to load shares'))
      .finally(() => setLoading(false));
  }, [open, resource]);

  async function toggleFavorite() {
    if (!resource) return;
    try {
      if (isFavorite) {
        await deleteFavorite(resource.kind, resource.id);
        onFavoriteToggle?.(false);
      } else {
        await createFavorite({ resource_kind: resource.kind, resource_id: resource.id });
        onFavoriteToggle?.(true);
      }
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Unable to update favorites');
    }
  }

  if (!open || !resource) return null;

  return (
    <>
      <aside className="of-resource-details-panel" style={{ position: 'fixed', top: 0, right: 0, bottom: 0, width: 380, background: '#0f172a', color: '#e2e8f0', borderLeft: '1px solid #1e293b', zIndex: 80, overflow: 'auto', padding: 16, display: 'flex', flexDirection: 'column', gap: 12 }}>
        <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }}>
          <div>
            <p className="of-text-muted" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{resource.kind}</p>
            <h3 style={{ margin: '4px 0 0', fontSize: 16, fontWeight: 600 }}>{resource.name}</h3>
            {resource.description && <p className="of-text-muted" style={{ marginTop: 4, fontSize: 12 }}>{resource.description}</p>}
          </div>
          <button type="button" onClick={onClose} style={{ background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: 16 }} aria-label="Close">✕</button>
        </header>

        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          <OpenWithMenu
            resourceKind={resource.kind}
            resourceId={resource.id}
            resourceRid={resource.rid}
            projectRid={resource.project_rid}
            projectId={resource.project_id}
            openUrl={resource.open_url}
            align="left"
          />
          <button type="button" onClick={() => void toggleFavorite()} className="of-button" style={{ fontSize: 11 }}>
            {isFavorite ? '★ Remove favorite' : '☆ Add to favorites'}
          </button>
          <button type="button" onClick={() => setShareOpen(true)} className="of-button" style={{ fontSize: 11 }}>Share...</button>
          <button type="button" onClick={() => setPermissionsOpen(true)} className="of-button" style={{ fontSize: 11 }}>Permissions</button>
        </div>

        <dl style={{ display: 'grid', gap: 6, fontSize: 12, margin: 0 }}>
          <div>
            <dt style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8' }}>RID</dt>
            <dd style={{ margin: 0, fontFamily: 'var(--font-mono)', fontSize: 11, wordBreak: 'break-all' }}>{resource.rid ?? resource.id}</dd>
          </div>
          {resource.location && (
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8' }}>Location</dt>
              <dd style={{ margin: 0 }}>{resource.location}</dd>
            </div>
          )}
          {resource.owner_id && (
            <div>
              <dt style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8' }}>Owner</dt>
              <dd style={{ margin: 0, fontFamily: 'var(--font-mono)' }}>{resource.owner_id}</dd>
            </div>
          )}
          <div>
            <dt style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8' }}>Created</dt>
            <dd style={{ margin: 0 }}>{fmtDate(resource.created_at)}</dd>
          </div>
          <div>
            <dt style={{ fontSize: 10, textTransform: 'uppercase', color: '#94a3b8' }}>Updated</dt>
            <dd style={{ margin: 0 }}>{fmtDate(resource.updated_at)}</dd>
          </div>
        </dl>

        {resource.tags && resource.tags.length > 0 && (
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
            {resource.tags.map((t) => (
              <span key={t} style={{ background: '#1e3a8a', color: '#bfdbfe', padding: '2px 8px', borderRadius: 999, fontSize: 11 }}>{t}</span>
            ))}
          </div>
        )}

        <section>
          <p className="of-eyebrow" style={{ fontSize: 10 }}>Shares ({shares.length})</p>
          {loading && <p className="of-text-muted" style={{ fontSize: 11, fontStyle: 'italic' }}>Loading…</p>}
          {error && <p style={{ color: '#fca5a5', fontSize: 11 }}>{error}</p>}
          <ul style={{ paddingLeft: 0, listStyle: 'none', display: 'grid', gap: 4, marginTop: 6 }}>
            {shares.map((s) => (
              <li key={s.id} style={{ background: '#1e293b', padding: '4px 8px', borderRadius: 4, fontSize: 11 }}>
                {s.shared_with_user_id || s.shared_with_group_id || '—'} · {s.access_level}
                {s.note && ` · ${s.note}`}
              </li>
            ))}
            {shares.length === 0 && !loading && <li className="of-text-muted" style={{ fontSize: 11, fontStyle: 'italic' }}>Not shared.</li>}
          </ul>
        </section>
      </aside>

      <ShareDialog
        open={shareOpen}
        resourceKind={resource.kind}
        resourceId={resource.id}
        resourceLabel={resource.name}
        onClose={() => setShareOpen(false)}
        onShared={() => {
          setShareOpen(false);
          // refresh shares
          listResourceShares(resource.kind, resource.id).then(setShares).catch(() => {});
        }}
      />
      <ResourcePermissionsDrawer
        open={permissionsOpen}
        resourceKind={resource.kind}
        resourceId={resource.id}
        resourceLabel={resource.name}
        ownerId={resource.owner_id}
        projectLabel={projectLabel}
        projectMemberships={projectMemberships}
        onClose={() => setPermissionsOpen(false)}
        onChanged={() => {
          listResourceShares(resource.kind, resource.id).then(setShares).catch(() => {});
        }}
      />
    </>
  );
}

// apps/web/src/lib/components/workspace/ResourceDetailsPanel.svelte
<script lang="ts">
  import Glyph from '$components/ui/Glyph.svelte';
  import ShareDialog from '$components/workspace/ShareDialog.svelte';
  import { notifications } from '$stores/notifications';
  import {
    createFavorite,
    deleteFavorite,
    listResourceShares,
    type ResourceKind,
    type ResourceShare,
  } from '$lib/api/workspace';

  export interface ResourceSummary {
    id: string;
    name: string;
    kind: ResourceKind;
    description?: string | null;
    owner_id?: string | null;
    location?: string | null;
    tags?: string[];
    created_at?: string | null;
    updated_at?: string | null;
  }

  let {
    open,
    resource,
    isFavorite = false,
    onClose,
    onFavoriteToggle,
  }: {
    open: boolean;
    resource: ResourceSummary | null;
    isFavorite?: boolean;
    onClose?: () => void;
    onFavoriteToggle?: (next: boolean) => void;
  } = $props();

  let shares = $state<ResourceShare[]>([]);
  let loadingShares = $state(false);
  let sharesError = $state('');
  let togglingFavorite = $state(false);
  let shareDialogOpen = $state(false);

  // Reload shares whenever the panel opens for a new resource. Failures
  // are non-fatal — the panel still renders metadata.
  $effect(() => {
    if (!open || !resource) {
      shares = [];
      sharesError = '';
      return;
    }
    void loadShares(resource);
  });

  async function loadShares(target: ResourceSummary) {
    loadingShares = true;
    sharesError = '';
    try {
      shares = await listResourceShares(target.kind, target.id);
    } catch (cause) {
      sharesError = cause instanceof Error ? cause.message : 'Unable to load shares';
      shares = [];
    } finally {
      loadingShares = false;
    }
  }

  async function toggleFavorite() {
    if (!resource || togglingFavorite) return;
    togglingFavorite = true;
    try {
      if (isFavorite) {
        await deleteFavorite(resource.kind, resource.id);
        onFavoriteToggle?.(false);
        notifications.success('Removed from favorites');
      } else {
        await createFavorite({ resource_kind: resource.kind, resource_id: resource.id });
        onFavoriteToggle?.(true);
        notifications.success('Added to favorites');
      }
    } catch (cause) {
      notifications.error(cause instanceof Error ? cause.message : 'Unable to update favorites');
    } finally {
      togglingFavorite = false;
    }
  }

  function formatDate(value: string | null | undefined) {
    if (!value) return '—';
    return new Intl.DateTimeFormat('en', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(new Date(value));
  }

  function shareLabel(share: ResourceShare) {
    if (share.shared_with_user_id) return `User · ${share.shared_with_user_id.slice(0, 8)}…`;
    if (share.shared_with_group_id) return `Group · ${share.shared_with_group_id.slice(0, 8)}…`;
    return 'Unknown principal';
  }
</script>

{#if open && resource}
  <aside
    class="fixed inset-y-0 right-0 z-40 flex w-[380px] max-w-full flex-col border-l border-[var(--border-default)] bg-white shadow-[0_0_24px_rgba(15,23,42,0.12)]"
    aria-label="Resource details"
  >
    <header class="flex items-start justify-between gap-3 border-b border-[var(--border-default)] px-4 py-4">
      <div class="min-w-0">
        <div class="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--text-muted)]">
          {resource.kind.replace(/_/g, ' ')}
        </div>
        <div class="mt-1 truncate text-base font-semibold text-[var(--text-strong)]">
          {resource.name}
        </div>
      </div>
      <div class="flex items-center gap-2">
        <button
          type="button"
          class={`rounded-md p-2 transition ${
            isFavorite
              ? 'bg-[#fff7e0] text-[#a86a00]'
              : 'text-[var(--text-muted)] hover:bg-[var(--bg-hover)]'
          }`}
          aria-pressed={isFavorite}
          aria-label={isFavorite ? 'Remove from favorites' : 'Add to favorites'}
          disabled={togglingFavorite}
          onclick={toggleFavorite}
        >
          <Glyph name="bookmark" size={16} />
        </button>
        <button
          type="button"
          class="rounded-md p-2 text-[var(--text-muted)] hover:bg-[var(--bg-hover)]"
          aria-label="Close details panel"
          onclick={() => onClose?.()}
        >
          <Glyph name="x" size={16} />
        </button>
      </div>
    </header>

    <div class="flex-1 overflow-y-auto px-4 py-4">
      {#if resource.description}
        <p class="m-0 text-sm text-[var(--text-default)]">{resource.description}</p>
      {/if}

      <dl class="mt-4 space-y-3 text-sm">
        {#if resource.location}
          <div class="flex items-start justify-between gap-3">
            <dt class="text-[var(--text-muted)]">Location</dt>
            <dd class="m-0 text-right text-[var(--text-strong)]">{resource.location}</dd>
          </div>
        {/if}
        {#if resource.owner_id}
          <div class="flex items-start justify-between gap-3">
            <dt class="text-[var(--text-muted)]">Owner</dt>
            <dd class="m-0 text-right text-[var(--text-strong)]">{resource.owner_id.slice(0, 8)}…</dd>
          </div>
        {/if}
        <div class="flex items-start justify-between gap-3">
          <dt class="text-[var(--text-muted)]">Created</dt>
          <dd class="m-0 text-right text-[var(--text-strong)]">{formatDate(resource.created_at)}</dd>
        </div>
        <div class="flex items-start justify-between gap-3">
          <dt class="text-[var(--text-muted)]">Last modified</dt>
          <dd class="m-0 text-right text-[var(--text-strong)]">{formatDate(resource.updated_at)}</dd>
        </div>
      </dl>

      {#if resource.tags && resource.tags.length > 0}
        <section class="mt-4">
          <div class="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--text-muted)]">Tags</div>
          <div class="mt-2 flex flex-wrap gap-2">
            {#each resource.tags as tag}
              <span class="of-chip">{tag}</span>
            {/each}
          </div>
        </section>
      {/if}

      <section class="mt-6">
        <div class="flex items-center justify-between">
          <div class="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--text-muted)]">Shared with</div>
          <div class="flex items-center gap-2">
            <span class="text-xs text-[var(--text-soft)]">{shares.length}</span>
            <button
              type="button"
              class="text-xs font-medium text-[var(--text-link)] hover:underline"
              onclick={() => (shareDialogOpen = true)}
            >
              Manage
            </button>
          </div>
        </div>

        {#if loadingShares}
          <div class="mt-3 text-sm text-[var(--text-muted)]">Loading shares…</div>
        {:else if sharesError}
          <div class="mt-3 text-sm text-[#b42318]">{sharesError}</div>
        {:else if shares.length === 0}
          <div class="mt-3 rounded-md border border-dashed border-[var(--border-default)] px-3 py-4 text-sm text-[var(--text-muted)]">
            Nobody else has access yet.
          </div>
        {:else}
          <ul class="m-0 mt-3 list-none space-y-2 p-0">
            {#each shares as share (share.id)}
              <li class="flex items-center justify-between rounded-md border border-[var(--border-default)] bg-[#fbfcfe] px-3 py-2 text-sm">
                <div class="min-w-0">
                  <div class="truncate font-medium text-[var(--text-strong)]">{shareLabel(share)}</div>
                  {#if share.note}
                    <div class="truncate text-xs text-[var(--text-muted)]">{share.note}</div>
                  {/if}
                </div>
                <span class="of-chip">{share.access_level}</span>
              </li>
            {/each}
          </ul>
        {/if}
      </section>
    </div>
  </aside>

  <ShareDialog
    open={shareDialogOpen}
    resourceKind={resource.kind}
    resourceId={resource.id}
    resourceLabel={resource.name}
    onClose={() => (shareDialogOpen = false)}
    onChange={() => {
      if (resource) void loadShares(resource);
    }}
  />
{/if}
