// apps/web/src/lib/components/workspace/FolderTree.svelte
<script lang="ts">
  import Glyph from '$components/ui/Glyph.svelte';

  export interface FolderNode {
    id: string;
    name: string;
    parent_folder_id: string | null;
  }

  let {
    folders,
    selectedId = null,
    rootLabel = 'Project root',
    onSelect,
    onDrop,
    canDrop,
  }: {
    folders: FolderNode[];
    selectedId?: string | null;
    rootLabel?: string;
    onSelect?: (folderId: string | null) => void;
    /** Optional drop handler. `null` = project root, otherwise folder id. */
    onDrop?: (folderId: string | null) => void | Promise<void>;
    /** Predicate so the tree can suppress invalid drop highlights. */
    canDrop?: (folderId: string | null) => boolean;
  } = $props();

  // Highlights the folder (or root) under the cursor while dragging.
  let dragOverId = $state<string | null | undefined>(undefined);

  function acceptsDrop(id: string | null): boolean {
    if (!onDrop) return false;
    return canDrop ? canDrop(id) : true;
  }

  function handleDragOver(event: DragEvent, id: string | null) {
    if (!acceptsDrop(id)) return;
    event.preventDefault();
    if (event.dataTransfer) event.dataTransfer.dropEffect = 'move';
    dragOverId = id;
  }

  function handleDragLeave(id: string | null) {
    if (dragOverId === id) dragOverId = undefined;
  }

  function handleDrop(event: DragEvent, id: string | null) {
    if (!acceptsDrop(id)) return;
    event.preventDefault();
    dragOverId = undefined;
    void onDrop?.(id);
  }

  type TreeNode = FolderNode & { children: TreeNode[] };

  // Build adjacency-style tree from a flat list. Folders missing parents
  // are surfaced as roots so a partial list still renders.
  const tree = $derived.by(() => {
    const byId = new Map<string, TreeNode>(
      folders.map((f) => [f.id, { ...f, children: [] }] as const),
    );
    const roots: TreeNode[] = [];
    for (const node of byId.values()) {
      const parent = node.parent_folder_id ? byId.get(node.parent_folder_id) : undefined;
      if (parent) {
        parent.children.push(node);
      } else {
        roots.push(node);
      }
    }
    const sortRec = (list: TreeNode[]) => {
      list.sort((a, b) => a.name.localeCompare(b.name));
      for (const node of list) sortRec(node.children);
    };
    sortRec(roots);
    return roots;
  });

  // Track expanded state locally — by default expand everything that
  // contains the current selection so the user always sees their context.
  let expanded = $state(new Set<string>());

  $effect(() => {
    if (!selectedId) return;
    const byId = new Map(folders.map((f) => [f.id, f] as const));
    let cursor: string | null = selectedId;
    const next = new Set(expanded);
    while (cursor) {
      const node: FolderNode | undefined = byId.get(cursor);
      if (!node) break;
      next.add(node.id);
      cursor = node.parent_folder_id;
    }
    expanded = next;
  });

  function toggle(id: string) {
    const next = new Set(expanded);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    expanded = next;
  }
</script>

<aside class="flex flex-col gap-1 p-2 text-sm">
  <button
    type="button"
    class={`flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left transition ${
      selectedId === null
        ? 'bg-[#eef4fd] text-[#2458b8] font-semibold'
        : 'text-[var(--text-default)] hover:bg-[var(--bg-hover)]'
    } ${dragOverId === null ? 'ring-2 ring-inset ring-[#3f7be0] bg-[#eef4fd]' : ''}`}
    onclick={() => onSelect?.(null)}
    ondragover={(event) => handleDragOver(event, null)}
    ondragleave={() => handleDragLeave(null)}
    ondrop={(event) => handleDrop(event, null)}
  >
    <Glyph name="home" size={14} />
    <span class="truncate">{rootLabel}</span>
  </button>

  <ul class="m-0 list-none space-y-0.5 p-0">
    {#each tree as root (root.id)}
      {@render branch(root, 0)}
    {/each}
  </ul>
</aside>

{#snippet branch(node: TreeNode, depth: number)}
  {@const hasChildren = node.children.length > 0}
  {@const isOpen = expanded.has(node.id)}
  {@const isSelected = selectedId === node.id}
  <li class="m-0">
    <div
      class={`flex items-center gap-1 rounded-md py-1 pr-2 transition ${
        isSelected
          ? 'bg-[#eef4fd] text-[#2458b8] font-semibold'
          : 'text-[var(--text-default)] hover:bg-[var(--bg-hover)]'
      } ${dragOverId === node.id ? 'ring-2 ring-inset ring-[#3f7be0] bg-[#eef4fd]' : ''}`}
      style={`padding-left: ${8 + depth * 14}px`}
      role="treeitem"
      aria-selected={isSelected}
      ondragover={(event) => handleDragOver(event, node.id)}
      ondragleave={() => handleDragLeave(node.id)}
      ondrop={(event) => handleDrop(event, node.id)}
    >
      {#if hasChildren}
        <button
          type="button"
          class="flex h-5 w-5 items-center justify-center rounded text-[var(--text-muted)] hover:text-[var(--text-strong)]"
          aria-label={isOpen ? 'Collapse folder' : 'Expand folder'}
          onclick={() => toggle(node.id)}
        >
          {#if isOpen}
            <Glyph name="chevron-down" size={12} />
          {:else}
            <Glyph name="chevron-right" size={12} />
          {/if}
        </button>
      {:else}
        <span class="inline-block h-5 w-5"></span>
      {/if}

      <button
        type="button"
        class="flex min-w-0 flex-1 items-center gap-2 truncate text-left"
        onclick={() => onSelect?.(node.id)}
      >
        <Glyph name="folder" size={13} />
        <span class="truncate">{node.name}</span>
      </button>
    </div>

    {#if hasChildren && isOpen}
      <ul class="m-0 list-none space-y-0.5 p-0">
        {#each node.children as child (child.id)}
          {@render branch(child, depth + 1)}
        {/each}
      </ul>
    {/if}
  </li>
{/snippet}

// apps/web-react/src/lib/components/workspace/FolderTree.tsx
import { useEffect, useMemo, useState } from 'react';

import { Glyph } from '@/lib/components/ui/Glyph';

export interface FolderNode {
  id: string;
  name: string;
  parent_folder_id: string | null;
}

interface FolderTreeProps {
  folders: FolderNode[];
  selectedId?: string | null;
  rootLabel?: string;
  onSelect?: (folderId: string | null) => void;
  onDrop?: (folderId: string | null) => void | Promise<void>;
  canDrop?: (folderId: string | null) => boolean;
}

interface TreeNode extends FolderNode { children: TreeNode[] }

export function FolderTree({ folders, selectedId = null, rootLabel = 'Project root', onSelect, onDrop, canDrop }: FolderTreeProps) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [dragOverId, setDragOverId] = useState<string | null | undefined>(undefined);

  const tree = useMemo<TreeNode[]>(() => {
    const byId = new Map<string, TreeNode>(folders.map((f) => [f.id, { ...f, children: [] }]));
    const roots: TreeNode[] = [];
    for (const node of byId.values()) {
      const parent = node.parent_folder_id ? byId.get(node.parent_folder_id) : undefined;
      if (parent) parent.children.push(node);
      else roots.push(node);
    }
    const sortRec = (list: TreeNode[]) => {
      list.sort((a, b) => a.name.localeCompare(b.name));
      for (const node of list) sortRec(node.children);
    };
    sortRec(roots);
    return roots;
  }, [folders]);

  useEffect(() => {
    if (!selectedId) return;
    const byId = new Map(folders.map((f) => [f.id, f]));
    let cursor: string | null = selectedId;
    setExpanded((prev) => {
      const next = new Set(prev);
      while (cursor) {
        const node = byId.get(cursor);
        if (!node) break;
        next.add(node.id);
        cursor = node.parent_folder_id;
      }
      return next;
    });
  }, [selectedId, folders]);

  function accepts(id: string | null) {
    if (!onDrop) return false;
    return canDrop ? canDrop(id) : true;
  }

  function toggle(id: string) {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function renderRow(node: TreeNode, depth: number) {
    const isExpanded = expanded.has(node.id);
    const selected = selectedId === node.id;
    const isOver = dragOverId === node.id;
    return (
      <li key={node.id}>
        <div
          onClick={() => onSelect?.(node.id)}
          onDragOver={(e) => {
            if (!accepts(node.id)) return;
            e.preventDefault();
            if (e.dataTransfer) e.dataTransfer.dropEffect = 'move';
            setDragOverId(node.id);
          }}
          onDragLeave={() => { if (dragOverId === node.id) setDragOverId(undefined); }}
          onDrop={(e) => {
            if (!accepts(node.id)) return;
            e.preventDefault();
            setDragOverId(undefined);
            void onDrop?.(node.id);
          }}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            padding: '4px 8px',
            paddingLeft: 8 + depth * 16,
            cursor: 'pointer',
            background: selected ? '#1e293b' : isOver ? '#1d4ed8' : 'transparent',
            color: selected || isOver ? '#fff' : 'inherit',
            borderRadius: 4,
            fontSize: 12,
          }}
        >
          {node.children.length > 0 ? (
            <button type="button" onClick={(e) => { e.stopPropagation(); toggle(node.id); }} style={{ background: 'transparent', border: 'none', color: 'inherit', cursor: 'pointer', padding: 0 }}>
              <Glyph name={isExpanded ? 'chevron-down' : 'chevron-right'} size={12} />
            </button>
          ) : (
            <span style={{ display: 'inline-block', width: 12 }} />
          )}
          <Glyph name="folder" size={12} />
          <span>{node.name}</span>
        </div>
        {isExpanded && node.children.length > 0 && (
          <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
            {node.children.map((c) => renderRow(c, depth + 1))}
          </ul>
        )}
      </li>
    );
  }

  return (
    <nav aria-label="Folder tree" style={{ fontSize: 12 }}>
      <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 2 }}>
        <li>
          <div
            onClick={() => onSelect?.(null)}
            onDragOver={(e) => { if (!accepts(null)) return; e.preventDefault(); setDragOverId(null); }}
            onDragLeave={() => { if (dragOverId === null) setDragOverId(undefined); }}
            onDrop={(e) => {
              if (!accepts(null)) return;
              e.preventDefault();
              setDragOverId(undefined);
              void onDrop?.(null);
            }}
            style={{
              padding: '4px 8px',
              cursor: 'pointer',
              background: selectedId === null ? '#1e293b' : dragOverId === null ? '#1d4ed8' : 'transparent',
              borderRadius: 4,
              fontWeight: 600,
            }}
          >
            <Glyph name="home" size={12} /> {rootLabel}
          </div>
        </li>
        {tree.map((n) => renderRow(n, 0))}
      </ul>
    </nav>
  );
}
