// apps/web/src/lib/components/workspace/RowActionsMenu.svelte
<script lang="ts">
  import Glyph from '$components/ui/Glyph.svelte';

  export type RowAction = {
    id: string;
    label: string;
    icon?: 'pencil' | 'duplicate' | 'move' | 'delete' | 'share';
    danger?: boolean;
    disabled?: boolean;
  };

  let {
    actions,
    onSelect,
    label = 'Row actions',
  }: {
    actions: RowAction[];
    onSelect: (id: string) => void;
    label?: string;
  } = $props();

  let open = $state(false);
  let container = $state<HTMLDivElement | null>(null);

  function toggle(event: MouseEvent) {
    event.stopPropagation();
    open = !open;
  }

  function handleSelect(event: MouseEvent, action: RowAction) {
    event.stopPropagation();
    if (action.disabled) return;
    open = false;
    onSelect(action.id);
  }

  $effect(() => {
    if (!open) return;
    const handler = (event: MouseEvent) => {
      if (container && !container.contains(event.target as Node)) {
        open = false;
      }
    };
    const keyHandler = (event: KeyboardEvent) => {
      if (event.key === 'Escape') open = false;
    };
    document.addEventListener('mousedown', handler);
    document.addEventListener('keydown', keyHandler);
    return () => {
      document.removeEventListener('mousedown', handler);
      document.removeEventListener('keydown', keyHandler);
    };
  });
</script>

<div bind:this={container} class="relative inline-flex">
  <button
    type="button"
    class="inline-flex h-7 w-7 items-center justify-center rounded-md text-[var(--text-muted)] hover:bg-[var(--bg-hover)] hover:text-[var(--text-strong)]"
    aria-label={label}
    aria-haspopup="menu"
    aria-expanded={open}
    onclick={toggle}
  >
    <span class="text-base leading-none">⋯</span>
  </button>

  {#if open}
    <div
      role="menu"
      class="absolute right-0 top-full z-30 mt-1 min-w-[180px] rounded-md border border-[var(--border-default)] bg-white py-1 shadow-lg"
    >
      {#each actions as action (action.id)}
        <button
          type="button"
          role="menuitem"
          class={`flex w-full items-center gap-2 px-3 py-1.5 text-left text-sm ${
            action.disabled
              ? 'cursor-not-allowed text-[var(--text-soft)]'
              : action.danger
                ? 'text-[#b42318] hover:bg-[#fff5f5]'
                : 'text-[var(--text-default)] hover:bg-[var(--bg-hover)]'
          }`}
          disabled={action.disabled}
          onclick={(event) => handleSelect(event, action)}
        >
          {#if action.icon === 'share'}
            <Glyph name="users" size={13} />
          {:else if action.icon === 'duplicate'}
            <Glyph name="object" size={13} />
          {:else if action.icon === 'move'}
            <Glyph name="folder" size={13} />
          {:else if action.icon === 'delete'}
            <span aria-hidden="true">🗑</span>
          {:else if action.icon === 'pencil'}
            <span aria-hidden="true">✎</span>
          {/if}
          <span>{action.label}</span>
        </button>
      {/each}
    </div>
  {/if}
</div>

// apps/web-react/src/lib/components/workspace/RowActionsMenu.tsx
import { useEffect, useRef, useState } from 'react';

import { Glyph } from '@/lib/components/ui/Glyph';

export interface RowAction {
  id: string;
  label: string;
  icon?: 'pencil' | 'duplicate' | 'move' | 'delete' | 'share';
  danger?: boolean;
  disabled?: boolean;
}

interface RowActionsMenuProps {
  actions: RowAction[];
  onSelect: (id: string) => void;
  label?: string;
}

export function RowActionsMenu({ actions, onSelect, label = 'Row actions' }: RowActionsMenuProps) {
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!open) return;
    function onMouse(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) setOpen(false);
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') setOpen(false);
    }
    document.addEventListener('mousedown', onMouse);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onMouse);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  return (
    <div ref={containerRef} style={{ position: 'relative', display: 'inline-flex' }}>
      <button
        type="button"
        aria-label={label}
        aria-haspopup="menu"
        aria-expanded={open}
        onClick={(e) => { e.stopPropagation(); setOpen((o) => !o); }}
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: 28,
          height: 28,
          borderRadius: 6,
          border: 'none',
          background: 'transparent',
          color: '#94a3b8',
          cursor: 'pointer',
        }}
      >
        ⋯
      </button>
      {open && (
        <div
          role="menu"
          style={{
            position: 'absolute',
            right: 0,
            top: '100%',
            marginTop: 4,
            minWidth: 180,
            zIndex: 30,
            background: '#0f172a',
            color: '#e2e8f0',
            border: '1px solid #1e293b',
            borderRadius: 6,
            padding: 4,
            boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
          }}
        >
          {actions.map((a) => (
            <button
              key={a.id}
              type="button"
              role="menuitem"
              disabled={a.disabled}
              onClick={(e) => {
                e.stopPropagation();
                if (a.disabled) return;
                setOpen(false);
                onSelect(a.id);
              }}
              style={{
                display: 'flex',
                width: '100%',
                alignItems: 'center',
                gap: 8,
                padding: '6px 12px',
                textAlign: 'left',
                fontSize: 13,
                background: 'transparent',
                border: 'none',
                color: a.danger ? '#fca5a5' : 'inherit',
                cursor: a.disabled ? 'not-allowed' : 'pointer',
                opacity: a.disabled ? 0.5 : 1,
              }}
            >
              {a.icon === 'share' && <Glyph name="users" size={13} />}
              {a.icon === 'duplicate' && <Glyph name="object" size={13} />}
              {a.icon === 'move' && <Glyph name="folder" size={13} />}
              {a.icon === 'delete' && <span aria-hidden="true">🗑</span>}
              {a.icon === 'pencil' && <span aria-hidden="true">✎</span>}
              <span>{a.label}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
