// apps/web/src/lib/components/pipeline/RunHistory.tsx
import { useEffect, useMemo, useRef, useState } from 'react';

import { abortBuild, listRuns, retryPipelineRun, triggerRun, type PipelineRun } from '@/lib/api/pipelines';
import { RunLogs } from './RunLogs';
import { LiveLogViewer } from './LiveLogViewer';

interface RunHistoryProps {
  pipelineId: string;
  readOnly?: boolean;
}

const LIVE_STATUSES = new Set([
  'running', 'pending', 'BUILD_RUNNING', 'BUILD_QUEUED',
  'BUILD_RESOLUTION', 'BUILD_ABORTING', 'RUN_PENDING', 'ABORT_PENDING',
]);

const PILL: Record<string, { background: string; color: string }> = {
  running: { background: '#1d4ed8', color: '#dbeafe' },
  completed: { background: '#166534', color: '#d1fae5' },
  failed: { background: '#991b1b', color: '#fee2e2' },
  aborted: { background: '#92400e', color: '#fde68a' },
};

function pill(s: string) {
  return PILL[s] ?? { background: '#334155', color: '#cbd5e1' };
}

function fmt(ts: string | null) {
  return ts ? new Date(ts).toLocaleString() : '—';
}

export function RunHistory({ pipelineId, readOnly = false }: RunHistoryProps) {
  const [runs, setRuns] = useState<PipelineRun[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  async function reload() {
    setLoading(true);
    setError(null);
    try {
      const res = await listRuns(pipelineId, { per_page: 25 });
      setRuns(res.data ?? []);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setLoading(false);
    }
  }

  async function trigger() {
    setBusy('trigger');
    try {
      await triggerRun(pipelineId);
      await reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setBusy(null);
    }
  }

  async function retry(runId: string) {
    setBusy(runId);
    try {
      await retryPipelineRun(pipelineId, runId);
      await reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setBusy(null);
    }
  }

  async function abort(runId: string) {
    if (typeof window !== 'undefined' && !window.confirm('Abort this build?')) return;
    setBusy(runId);
    try {
      await abortBuild(runId);
      await reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setBusy(null);
    }
  }

  useEffect(() => {
    if (pipelineId) void reload();
  }, [pipelineId]);

  useEffect(() => {
    const hasRunning = runs.some((r) => r.status === 'running');
    if (hasRunning && !pollRef.current) {
      pollRef.current = setInterval(() => void reload(), 5000);
    } else if (!hasRunning && pollRef.current) {
      clearInterval(pollRef.current);
      pollRef.current = null;
    }
    return () => {
      if (pollRef.current) {
        clearInterval(pollRef.current);
        pollRef.current = null;
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [runs]);

  const selectedRun = useMemo(() => runs.find((r) => r.id === selectedRunId) ?? null, [runs, selectedRunId]);

  return (
    <section style={{ display: 'flex', flexDirection: 'column', gap: 12, padding: 14, background: '#0b1220', border: '1px solid #1f2937', borderRadius: 8, color: '#e2e8f0' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h3 style={{ margin: 0, fontSize: 14 }}>Build history</h3>
        <div style={{ display: 'flex', gap: 6 }}>
          <button type="button" onClick={() => void reload()} disabled={loading} className="of-button" style={{ fontSize: 12 }}>Refresh</button>
          {!readOnly && (
            <button type="button" onClick={() => void trigger()} disabled={busy === 'trigger'} className="of-button of-button--primary" style={{ fontSize: 12 }}>
              {busy === 'trigger' ? 'Triggering…' : 'Trigger run'}
            </button>
          )}
        </div>
      </header>
      {error && <p style={{ color: '#fca5a5', fontSize: 12, margin: 0 }}>{error}</p>}
      {runs.length === 0 && !loading ? (
        <p style={{ color: '#94a3b8', fontStyle: 'italic', margin: 0, fontSize: 12 }}>No runs yet.</p>
      ) : (
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
          <thead>
            <tr>
              {['Status', 'Trigger', 'Started', 'Finished', 'Attempt', 'Actions'].map((h) => (
                <th key={h} style={{ textAlign: 'left', padding: '6px 8px', borderBottom: '1px solid #1f2937', color: '#94a3b8', fontWeight: 500, textTransform: 'uppercase', fontSize: 11 }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {runs.map((run) => (
              <tr key={run.id} style={{ background: run.id === selectedRunId ? '#1e293b' : 'transparent' }}>
                <td style={{ padding: '6px 8px', borderBottom: '1px solid #1f2937' }}>
                  <span style={{ ...pill(run.status), padding: '2px 8px', borderRadius: 999, fontSize: 11 }}>{run.status}</span>
                </td>
                <td style={{ padding: '6px 8px', borderBottom: '1px solid #1f2937' }}>{run.trigger_type}</td>
                <td style={{ padding: '6px 8px', borderBottom: '1px solid #1f2937' }}>{fmt(run.started_at)}</td>
                <td style={{ padding: '6px 8px', borderBottom: '1px solid #1f2937' }}>{fmt(run.finished_at)}</td>
                <td style={{ padding: '6px 8px', borderBottom: '1px solid #1f2937' }}>#{run.attempt_number}</td>
                <td style={{ padding: '6px 8px', borderBottom: '1px solid #1f2937', display: 'flex', gap: 4 }}>
                  <button type="button" onClick={() => setSelectedRunId(run.id)} className="of-button" style={{ fontSize: 11 }}>Logs</button>
                  {!readOnly && run.status === 'running' && (
                    <button type="button" onClick={() => void abort(run.id)} disabled={busy === run.id} className="of-button" style={{ fontSize: 11 }}>Abort</button>
                  )}
                  {!readOnly && (run.status === 'failed' || run.status === 'aborted') && (
                    <button type="button" onClick={() => void retry(run.id)} disabled={busy === run.id} className="of-button" style={{ fontSize: 11 }}>Retry</button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      {selectedRun && (
        LIVE_STATUSES.has(selectedRun.status) ? (
          <LiveLogViewer jobRid={`ri.foundry.main.job.${selectedRun.id}`} mode="live" />
        ) : (
          <>
            <RunLogs run={selectedRun} onClose={() => setSelectedRunId(null)} />
            <LiveLogViewer jobRid={`ri.foundry.main.job.${selectedRun.id}`} mode="historical" />
          </>
        )
      )}
    </section>
  );
}

// apps/web/src/lib/components/pipeline/RunHistory.svelte
<!--
  RunHistory — runs table for a pipeline (Foundry: "Build history" tab).
  Polls every 5s while at least one run is `running`. Surfaces buttons to
  trigger a fresh run, retry a finished run, abort an in-flight run, and
  open <RunLogs/> for per-node detail.
-->
<script lang="ts">
  import type { PipelineRun } from '$lib/api/pipelines';
  import { listRuns, triggerRun, retryPipelineRun, abortBuild } from '$lib/api/pipelines';
  import RunLogs from './RunLogs.svelte';
  import LiveLogViewer from './LiveLogViewer.svelte';

  // P4 — when the selected run is live, replace the per-node summary
  // with the streaming LiveLogViewer (Foundry doc § Live logs). The
  // legacy summary stays for terminal runs so historical inspections
  // keep their per-node breakdown.
  const LIVE_STATUSES = new Set([
    'running',
    'pending',
    'BUILD_RUNNING',
    'BUILD_QUEUED',
    'BUILD_RESOLUTION',
    'BUILD_ABORTING',
    'RUN_PENDING',
    'ABORT_PENDING'
  ]);

  type Props = {
    pipelineId: string;
    readonly?: boolean;
  };

  let { pipelineId, readonly = false }: Props = $props();

  let runs = $state<PipelineRun[]>([]);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let selectedRunId = $state<string | null>(null);
  let busy = $state<string | null>(null); // run_id or "trigger"

  let pollHandle: ReturnType<typeof setInterval> | null = null;

  async function reload() {
    loading = true;
    error = null;
    try {
      const res = await listRuns(pipelineId, { per_page: 25 });
      runs = res.data ?? [];
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      loading = false;
    }
  }

  async function trigger() {
    busy = 'trigger';
    try {
      await triggerRun(pipelineId);
      await reload();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      busy = null;
    }
  }

  async function retry(runId: string) {
    busy = runId;
    try {
      await retryPipelineRun(pipelineId, runId);
      await reload();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      busy = null;
    }
  }

  async function abort(runId: string) {
    if (!confirm('Abort this build?')) return;
    busy = runId;
    try {
      await abortBuild(runId);
      await reload();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    } finally {
      busy = null;
    }
  }

  function statusClass(s: string): string {
    if (s === 'running') return 'pill running';
    if (s === 'completed') return 'pill ok';
    if (s === 'failed') return 'pill fail';
    if (s === 'aborted') return 'pill warn';
    return 'pill';
  }

  function fmt(ts: string | null): string {
    return ts ? new Date(ts).toLocaleString() : '—';
  }

  $effect(() => {
    if (!pipelineId) return;
    void reload();
  });

  $effect(() => {
    const hasRunning = runs.some((r) => r.status === 'running');
    if (hasRunning && !pollHandle) {
      pollHandle = setInterval(reload, 5000);
    } else if (!hasRunning && pollHandle) {
      clearInterval(pollHandle);
      pollHandle = null;
    }
    return () => {
      if (pollHandle) {
        clearInterval(pollHandle);
        pollHandle = null;
      }
    };
  });

  let selectedRun = $derived(runs.find((r) => r.id === selectedRunId) ?? null);
</script>

<section class="history">
  <header>
    <h3>Build history</h3>
    <div class="actions">
      <button type="button" onclick={reload} disabled={loading}>Refresh</button>
      {#if !readonly}
        <button
          type="button"
          class="primary"
          onclick={trigger}
          disabled={busy === 'trigger'}
        >
          {busy === 'trigger' ? 'Triggering…' : 'Trigger run'}
        </button>
      {/if}
    </div>
  </header>

  {#if error}
    <p class="error">{error}</p>
  {/if}

  {#if runs.length === 0 && !loading}
    <p class="hint">No runs yet.</p>
  {:else}
    <table>
      <thead>
        <tr>
          <th>Status</th>
          <th>Trigger</th>
          <th>Started</th>
          <th>Finished</th>
          <th>Attempt</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {#each runs as run (run.id)}
          <tr class:selected={run.id === selectedRunId}>
            <td><span class={statusClass(run.status)}>{run.status}</span></td>
            <td>{run.trigger_type}</td>
            <td>{fmt(run.started_at)}</td>
            <td>{fmt(run.finished_at)}</td>
            <td>#{run.attempt_number}</td>
            <td class="row-actions">
              <button type="button" onclick={() => (selectedRunId = run.id)}>Logs</button>
              {#if !readonly && run.status === 'running'}
                <button type="button" onclick={() => abort(run.id)} disabled={busy === run.id}>Abort</button>
              {/if}
              {#if !readonly && (run.status === 'failed' || run.status === 'aborted')}
                <button type="button" onclick={() => retry(run.id)} disabled={busy === run.id}>Retry</button>
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}

  {#if selectedRun}
    {#if LIVE_STATUSES.has(selectedRun.status)}
      <!-- Live (SSE-backed) viewer for jobs still in flight. -->
      <LiveLogViewer jobRid={`ri.foundry.main.job.${selectedRun.id}`} mode="live" />
    {:else}
      <!-- Terminal runs: per-node summary + historical REST-backed
           log viewer side by side, so operators see the timeline that
           was captured during the run. -->
      <RunLogs run={selectedRun} onClose={() => (selectedRunId = null)} />
      <LiveLogViewer jobRid={`ri.foundry.main.job.${selectedRun.id}`} mode="historical" />
    {/if}
  {/if}
</section>

<style>
  .history {
    display: flex;
    flex-direction: column;
    gap: 12px;
    padding: 14px;
    background: #0b1220;
    border: 1px solid #1f2937;
    border-radius: 8px;
    color: #e2e8f0;
  }
  header { display: flex; justify-content: space-between; align-items: center; }
  h3 { margin: 0; font-size: 14px; }
  .actions { display: flex; gap: 6px; }
  .actions button, .row-actions button {
    background: #1e293b;
    color: #cbd5e1;
    border: 1px solid #334155;
    border-radius: 4px;
    padding: 4px 10px;
    cursor: pointer;
    font-size: 12px;
  }
  .actions button:hover:not(:disabled), .row-actions button:hover:not(:disabled) {
    background: #334155;
  }
  .actions button:disabled, .row-actions button:disabled { opacity: 0.5; cursor: not-allowed; }
  button.primary { background: #1e3a8a; color: #f1f5f9; border-color: #1d4ed8; }
  button.primary:hover:not(:disabled) { background: #1d4ed8; }
  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
  }
  th, td {
    text-align: left;
    padding: 6px 8px;
    border-bottom: 1px solid #1f2937;
  }
  th { color: #94a3b8; font-weight: 500; text-transform: uppercase; font-size: 11px; }
  tr.selected td { background: #1e293b; }
  .row-actions { display: flex; gap: 4px; }
  .pill {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 999px;
    font-size: 11px;
    background: #334155;
    color: #cbd5e1;
  }
  .pill.running { background: #1d4ed8; color: #dbeafe; }
  .pill.ok { background: #166534; color: #d1fae5; }
  .pill.fail { background: #991b1b; color: #fee2e2; }
  .pill.warn { background: #92400e; color: #fde68a; }
  .hint { color: #94a3b8; font-style: italic; margin: 0; font-size: 12px; }
  .error { color: #fca5a5; font-size: 12px; margin: 0; }
</style>
